### ISSUE TITLE
Limit the number of cache files created

### ISSUE THREAD

**Issue by brianhks** [kairosdb/kairosdb#112]
There is a potential of running out of inodes that causes no such directory errors.

**Comment by brianhks** [comment]
This limit should also consider the size of the cache directory.

**Comment by farzadpanahi** [comment]
This is a much needed feature. A not well crafted query will break the whole TSDB because it fills up the kairosdb cache.

**Comment by brianhks** [comment]
kairosdb.query_cache.keep_cache_files was added that addresses this issue.  It still uses cache files but it doesn't keep them around.
