### ISSUE TITLE
init script won't ever kill -9 an unresponsive daemon

### ISSUE THREAD

**Issue by burtonator** [kairosdb/kairosdb#119]
Due to an infinite while loop in the init script, if a daemon doesn't respond to kill, it will never stop.

What this needs is a timeout.  So if we are trying for more than 120 seconds or so a `kill -9` should be sent.

Something like 

```
duration=0
```

then for each loop use 

```
duration=$(expr $duration + 1)
```

then 

```
if [ "$duration" = "120" ];  then
   kill -9  `cat $KAIROS_PID_FILE`
fi
```

... and while it's controversial, I think systemd does this for us in the future.

```
        kill `cat $KAIROS_PID_FILE` > /dev/null 2>&1
        while kill -0 `cat $KAIROS_PID_FILE` > /dev/null 2>&1; do
                echo -n "."
                sleep 1;
        done
```

**Comment by brianhks** [comment]
SystemD will kill the process after 1 min if it doesn't shutdown.  This can be changed in the service file.
