### ISSUE TITLE
Add 'limit' to the query builder UI.

### ISSUE THREAD

**Issue by burtonator** [kairosdb/kairosdb#123]
The query protocol supports 'limit' on the number of values.  this is specified in the query json.

The problem is that the query builder UI doesn't expose this option.

This has two problems:

1.  It means that even experience people aren't aware of this option. I wasn't and consider myself to have at least an intermediate understanding of KairosDB.

2.  It makes it hard to work with metrics when using limit since you can only use this option when you write and execute your own queries.  There's no way to get it to work with the query builder even if you manually add the limit as the "graph" button re-writes the query.

**Comment by jsabin** [comment]
Limit is now in the UI.
