### ISSUE TITLE
Please update to use newer hector-core client version (>=2.0.0)

### ISSUE THREAD

**Issue by mihaiplesa** [kairosdb/kairosdb#134]
We are having issues with the Cassandra node autodiscovery mechanism in KairosDB which were solved when manually replacing the hector-core version with a newer one.

Related to https://github.com/hector-client/hector/issues/622

**Comment by dayman** [comment]
This one was reverted as part of https://github.com/kairosdb/kairosdb/issues/169. 
So release 1.0.0 doesn't include this change

**Comment by danielkza** [comment]
Node autodiscovery still seems to be broken with a NullPointerException in 1.1.2.

**Comment by francisdb** [comment]
Same problem here on 1.1.3
