### ISSUE TITLE
Question about REST API changes

### ISSUE THREAD

**Issue by iaean** [kairosdb/kairosdb#141]
I'm implementing a connector for [facette](https://github.com/facette/facette) to use KairosDB as a provider. To ensure the correct KairosDB version that supports the used API, I have the following question: _What is the last release prior to 0.9.4 that supports the same REST API then 0.9.4?_ Thanks for some hint.

**Comment by brianhks** [comment]
The big change was with adding custom data types between 0.9.3 and 0.9.4.  This change was mostly confined to the results of a query.  The api will stay the same in 0.9.5 which we intend to release a beta here shortly.
