### ISSUE TITLE
Limit and order filters

### ISSUE THREAD

**Issue by eliavgnessin** [kairosdb/kairosdb#144]
In one of the forums you've mentioned query parameters for LIMIT and ORDER :

"" Basically add "limit": 4 and "order": "desc" (default is asc) to your query requests.""

Can you comment on the version this got in, and whether it works or not? I didn't manage to get it working in 0.9.4

Thx!
Eliav

**Comment by brianhks** [comment]
This is in 9.4

http://kairosdb.github.io/kairosdocs/restapi/QueryMetrics.html
