### ISSUE TITLE
init.d should use "/*" for classpath instead of manually adding each jar.

### ISSUE THREAD

**Issue by burtonator** [kairosdb/kairosdb#146]
Modern JVMs can use all .jars in a directory by specifying:

```
-cp "/path/to/app/lib/*"
```

Right now we're doing this:

```
CLASSPATH="conf/logging"
for jar in $KAIROSDB_LIB_DIR/*.jar; do
        CLASSPATH="$CLASSPATH:$jar"
done
```

which pollutes the command line and makes it difficult to read command line arguments.  

The fix is to just change the -cp argument to 

```
CLASSPATH="conf/logging:$KAIROSDB_LIB_DIR/*"
```

which should work fine.

**Comment by brianhks** [comment]
We had tried to do this in the beginning and for some reason it doesn't work within the confines of our script.  I'm not sure why.  I just tried it again and it doesn't work.  I'm not a bash geneous so I may be doing something wrong.

**Comment by burtonator** [comment]
I think you have to quote the argument.  If you don't bash will expand the * ... 

so instead of:

```
-cp conf/logging:$KAIROSDB_LIB_DIR/*
```

you would have to do

```
-cp "conf/logging:$KAIROSDB_LIB_DIR/*"
```

Does that fix it?

**Comment by burtonator** [comment]
Oh.. and we use this in production so it should work.  Definitely better than having an insanely long command line :)

**Comment by brianhks** [comment]
I know it should work, but it doesn't.  You have to put it in quotes or the shell tries to expand it and then it goes weird.  I tried several different combinations to no avail.  If you have something that works I'd love to see it.
