### ISSUE TITLE
Manually specify -Xmx memory settings.

### ISSUE THREAD

**Issue by burtonator** [kairosdb/kairosdb#147]
Right now we don't specify memory settings for KairosDB.  

Which means the JVM magically determines how much memory is used.

This means that it could accidentally pick the wrong setting.

The best practice that we've adopted (and others in the community) is to explicitly set -Xms and -Xmx to the same value.  This way there's no heap resize and the entire JVM uses the same memory size for the entire lifetime of the app.

I think we should adopt this in KairosDB as well.

**Comment by FrEaKmAn** [comment]
https://github.com/kairosdb/kairosdb/blob/master/src/scripts/kairosdb-env.sh

**Comment by brianhks** [comment]
As Freakman pointed out we have the kairosdb-env.sh file just for that purpose.  It gets sourced in and lets you set memory and other jvm settings without polluting the startup script.

**Comment by burtonator** [comment]
I think that's a decent point. I saw that after I posted this.  Perhaps a reasonable default should be set?
