### ISSUE TITLE
No way to disable internal metrics

### ISSUE THREAD

**Issue by dimas** [kairosdb/kairosdb#148]
There seems to be no way to tell KairosDB to completely disable logging of internal metrics.

We use Kairos with H2 backend to run integration tests and these produce a lot of data. Even though our tests clean up after themselves, H2 database still keeps growing to uncontrollable size over a long periods of time because of stuff it logs internally and which none of us really need in test environment.

Yes, we can set

```
 kairosdb.service.reporter=
```

(to a blank value) but MetricsResource.java will still be logging "kairosdb.datastore.query_sample_size" and others.

For now I guess the only option is to stop Kairos, remove its H2 folder and start it again before each integration test run. Which is probably ok but not ideal.

**Comment by brianhks** [comment]
I'm not against this idea, it has merit.  I'll look to see if this can get into the 0.9.6 release.

**Comment by michaelsembwever** [comment]
Any progress on this @brianhks ? The partition sizes these metrics generate, in the hardcoded 3 week partitions, can be tens of GBs which is not appropriate for Cassandra and will ruin otherwise functioning installations of KairosDB.

**Comment by brianhks** [comment]
Until kairos moves to metrics4j I added a metric filter on ingest that lets you filter any metric.
