### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by rdettai** [kairosdb/kairosdb#149]
Hi!

I was going through the constraint validation mechanism, an I found out that 3 classes in org.kairosdb.core.http.rest.json are unused:
QueryRequest, Metric and Sampling.

Am I correct ? Or maybe there is something that confuses my IDE's "find usage" feature !

**Comment by brianhks** [comment]
Thanks for pointing this out.  It looks suspicious, I'll have to dig into it to find out why these classes are not used in the main code.

**Comment by rdettai** [comment]
I believe these classes are duplicated here and there: there is an other implementation of Sampling in the datastore package and one of Metric as a subclass of the GsonParser... The unused classes are legacy classes from OpenTSDB. For instance you re-created Sampling when your implemented RangeAggregator (cf commit https://github.com/kairosdb/kairosdb/commit/f7b2490f4f870983adafe1819c678335dae40b3c )

Git is great to understand these kind of stuff !

**Comment by rdettai** [comment]
Hi again. In merge of pull request #82 for DST/leap year fix, the Sampling class from org.kairosdb.core.http.rest.json has actually been updated. I believe removing it (if it is actually dead code and I'm not dreaming) could avoid lots of confusions.

**Comment by brianhks** [comment]
Yup totally dead code.
