### ISSUE TITLE
org.kairosdb.core.datastore.TimeUnit class having LGPL Header

### ISSUE THREAD

**Issue by VenkateshSub** [kairosdb/kairosdb#156]
I am not sure if this was a miss when the original cleanup happened or if it is there in purpose. KairosDB is an Apache 2.0 license while this particular class (org.kairosdb.core.datastore.TimeUnit) still has a header with LGPL in it. Is it possible to change the header to Apache 2.0 as well? 

Thanks!

**Comment by brianhks** [comment]
thanks for the catch.
