### ISSUE TITLE
Plugins have different dependencies

### ISSUE THREAD

**Issue by brianhks** [kairosdb/kairosdb#159]
Some plugins may have different dependencies than what is provided by Kairos.  These dependencies may be in conflict and cause Kairos to not work right.

**Comment by brianhks** [comment]
This has been fixed by adding a special plugin class loader.  A new property can be specified to identify where the plugin dependencies reside.  For example the solr plugin properties look like this:
```
kairosdb.service.solr=org.kairosdb.plugin.solr.SolrModule
kairosdb.service_folder.solr=lib/solr
```
The solr plugin libraries will be loaded from lib/solr.

**Comment by lcoulet** [comment]
Wonderful ! 
I was wondering when this kind of conflict would happen to us.

**Comment by brianhks** [comment]
So far it works fine except for logging dependencies, you better use the ones in Kairos.
