### ISSUE TITLE
Add metric meta data store

### ISSUE THREAD

**Issue by brianhks** [kairosdb/kairosdb#161]
Add the ability to store meta data on a per metric name basis.  This would be a key/value (both strings) stored on a per metric name.

API would look something like
get
/api/v1/meta/[metric_name]/[key]

**Comment by FrEaKmAn** [comment]
Probably there would also be POST (to update) and DELETE (for deleting) methods?

Do you think it would make sense to have multiple storages? by default it stores into cassandra (or h2), but somebody could also store this into super fast redis or something similar.

**Comment by brianhks** [comment]
I think I just add it to the datastore interface (h2/cassandra).  This kind of lookup will be really quick in Cassandra.

Probably also need a Get for just /api/meta/[metric-name] that returns a json map of all properties set.

**Comment by FrEaKmAn** [comment]
Yeah, I agree.

**Comment by brianhks** [comment]
A metadata api was added a while back that will work for this purpose.  It is a generic key value type store.
