### ISSUE TITLE
Limit data cache size

### ISSUE THREAD

**Issue by alsonkemp** [kairosdb/kairosdb#165]
This may be a dup of #112, but we're seeing unbounded growth of /tmp/kairos_cache.  After a day of running, we're at about 80GB.  Is there a setting we're missing?  Or is this a known bug?

**Comment by alsonkemp** [comment]
I see this setting in kairosdb.properties:

    kairosdb.query_cache.cache_file_cleaner_schedule=0 0 12 ? * SUN *

Perhaps we should clear the cache more frequently?

**Comment by FrEaKmAn** [comment]
Good question is, are those actually same cache files? maybe there is a bug and it's actually creating new cache files...

**Comment by alsonkemp** [comment]
Unfortunately, we cleaned out the caches, so I don't have a whole lot of data.  That said, a machine that was cleaned 4 hours ago has 151,230 files in the cache directory and they look like:

    -rw-r--r-- 1 root root      109 Apr 15 20:31 a30b0ccda5371139186c31b00fb68227.index
    -rw-r--r-- 1 root root     8448 Apr 15 20:31 a30b0ccda5371139186c31b00fb68227.data
    -rw-r--r-- 1 root root      110 Apr 15 20:31 a2d044759171f082b025b25c5f52263.index
    -rw-r--r-- 1 root root       96 Apr 15 20:31 a2d044759171f082b025b25c5f52263.data
    -rw-r--r-- 1 root root      110 Apr 15 20:31 3668839be5a8fec8c9f949e6d175cd79.index
    -rw-r--r-- 1 root root     8448 Apr 15 20:31 3668839be5a8fec8c9f949e6d175cd79.data
    -rw-r--r-- 1 root root      111 Apr 15 20:31 2d9274dc612b0823b486e749a858276a.index
    -rw-r--r-- 1 root root     8448 Apr 15 20:31 2d9274dc612b0823b486e749a858276a.data

Looks as though it's one file per request?

**Comment by FrEaKmAn** [comment]
Can you verify that it's the same file with checksum?

**Comment by br0th3r** [comment]
They look different because they have different sizes:

```
-rw-r--r-- 1 root root      109 Apr 15 20:31 a30b0ccda5371139186c31b00fb68227.index
-rw-r--r-- 1 root root      110 Apr 15 20:31 a2d044759171f082b025b25c5f52263.index
-rw-r--r-- 1 root root      110 Apr 15 20:31 3668839be5a8fec8c9f949e6d175cd79.index
-rw-r--r-- 1 root root      111 Apr 15 20:31 2d9274dc612b0823b486e749a858276a.index
```

a2d044759171f082b025b25c5f52263.data is 96 bytes:
```
-rw-r--r-- 1 root root     8448 Apr 15 20:31 a30b0ccda5371139186c31b00fb68227.data
-rw-r--r-- 1 root root     8448 Apr 15 20:31 a30b0ccda5371139186c31b00fb68227.data
-rw-r--r-- 1 root root       96 Apr 15 20:31 a2d044759171f082b025b25c5f52263.data
-rw-r--r-- 1 root root     8448 Apr 15 20:31 3668839be5a8fec8c9f949e6d175cd79.data
-rw-r--r-- 1 root root     8448 Apr 15 20:31 2d9274dc612b0823b486e749a858276a.data
```

**Comment by brianhks** [comment]
You get one cache file for every query unless, you set the cache time on the query and it uses a previous one.

If you application is such that you never want to read stale data (even stale for a minute) then the cache file only gets used once.

Yes this is a duplicate of #112 and your only real option for now is to turn up the frequency on the cleaner thread.
