### ISSUE TITLE
Update java dependency to 1.7.0 or above

### ISSUE THREAD

**Issue by arussellsaw** [kairosdb/kairosdb#168]
as of the 0.9.5-b2 release, kairosdb no longer runs on 1.6.0, but the rpm does not have a dependency to say so. when trying to run kairosdb on 1.6.0 a java.lang.UnsupportedClassVersionError is immediately thrown with Unsupported major.minor version 51.0 message

**Comment by brianhks** [comment]
Thanks for catching that.
