### ISSUE TITLE
0.9.5-b2 less tolerant of slow cassandra?

### ISSUE THREAD

**Issue by arussellsaw** [kairosdb/kairosdb#169]
During our evaluation of 0.9.5-b2 we've encountered problems.
Our cassandra cluster is quite slow, we're hoping this will be resolved by 0.9.5 allowing us to write at a consistency of ONE rather than QUORUM (this currently causes cross DC writes) however due to issue #166 we must first upgrade our set of kairosdb query nodes. it seems that in 0.9.5-b2 the hector client is a lot less tolerant of our slowness, causing many more timeouts than 0.9.4 (we saw a few under heavy load), which then leads to all nodes being marked as unavailable, and kairosdb failing to return any results.

the purpose of this issue is to ask whether this behaviour is expected, and ask for any ways to mitigate this problem so that we can complete the rollout of 0.9.5-b2 without killing our entire cluster.

**Comment by brianhks** [comment]
Thanks for the input.  I need to address #166 first and then I'll come back to this issue.

**Comment by brianhks** [comment]
In the 9.5 development we upgraded the hector library from 1.1-4 to 2.0.  It is possible they made the library less tolerant of slow Cassandra.  Can you try swapping out the new hector library for the old one?  You may have to swap out some cassandra libs as well, just compare to the 0.9.4 version.  As far as Kairos is concerned the interface hasn't changed so the new code will run just fine with the old library.

If this fixes the problem we can dump the 2.0 lib and just work on converting to Astyanax.

**Comment by brianhks** [comment]
Reverted library to previous version.
