### ISSUE TITLE
Enhancement: improve data processing algorithms to handle big amount of data

### ISSUE THREAD

**Issue by dayman** [kairosdb/kairosdb#172]
At the moment Kairos loads all datapoints from cache file into memory during grouping\sorting\aggregating etc.
So for instance if we have 250 000 samples in database after requesting I see ~ 1 Gb memory growth.
So as we have lots of data and get requests very often we see MemoryMonitorException.
Would be useful to consider using streams or\and map reduce while processing data.

**Comment by brianhks** [comment]
On the contrary we don't load them all into memory.  As the data is received it is written to the cache file.  During the sorting process we read only the first data point or so from each row returned from cassandra and we got to great lengths to ensure we have only one copy of any given string (tags) in memory.

The sorting is done as a tournament tree and very efficient.  The datapoints are sent through the aggregators as a stream and written to a json response on disk.  The size of the tournament tree is determined by the number of rows the data was on in Cassandra.  The new 0.9.5 code will tell you how many rows in the response.

So what is the makeup of this 250K of data?  Does it all have the same tags, if not what is the cardinality of the tags?

**Comment by FrEaKmAn** [comment]
I tested loading up to 10M records (JSON is 200MB large) with about 15 tags and works just fine on medium size machine...

**Comment by dayman** [comment]
Well, interesting. I connected profiler and performed one query for 500K samples (I've choosen kairosdb.metrics_counter, no tags) and I see this chain of methods allocated 1.5 Gb of objects
```
KairosDatastore.java:495 org.kairosdb.core.datastore.CachedSearchResult.getRows()
  CachedSearchResult.java:340 org.kairosdb.core.datastore.CachedSearchResult$FilePositionMarker.iterator()
    CachedSearchResult.java:398 org.kairosdb.core.datastore.CachedSearchResult$CachedDataPointRow.<init>(CachedSearchResult, Map, long, long, String, int)
      CachedSearchResult.java:450 org.kairosdb.util.BufferedDataInputStream.<init>(RandomAccessFile, long)
        BufferedDataInputStream.java:14 java.io.BufferedInputStream.<init>(InputStream)
```

**Comment by FrEaKmAn** [comment]
Which version are you using?

**Comment by dayman** [comment]
0.9.4-6. will test with 0.9.5 soon and write the results

**Comment by FrEaKmAn** [comment]
Can you just test and set xmx and xms? https://github.com/kairosdb/kairosdb/blob/master/src/scripts/kairosdb-env.sh

**Comment by dayman** [comment]
Without -Xms -Xmx I got 
```
Return Value: {"errors":["org.kairosdb.util.MemoryMonitorException: Insufficient memory to perform request"]}
```

again 1.2Gb in memory shared between these:
```
KairosDatastore.java:456 org.kairosdb.core.datastore.CachedSearchResult.getRows() 560 Mbs
KairosDatastore.java:455 org.kairosdb.datastore.cassandra.CassandraDatastore.queryDatabase(DatastoreMetricQuery, QueryCallback) 280 Mbs
NativeMethodAccessorImpl.java (native) org.kairosdb.core.http.rest.MetricsResource.getMeta(String) 340 Mbs
```
When -Xmx3G -Xms3G specified absolutely same request loads 2.3 Gbs
```
KairosDatastore.java:456 org.kairosdb.core.datastore.CachedSearchResult.getRows() 1.5 Gb
```

**Comment by brianhks** [comment]
I dug into the code and found the following.  It is dependant upon the number of rows your data is on (ie number of tag combinations).  If your data was all in one row you would see dramatically different results.

So for each row that we have written to cache we create a BufferedInputStream that allocates an 8k buffer.  I think the prudent thing to do is add login that takes into account the size of the row on disk (which I have) and the number of rows being read.

Something like this:  
Max buffer size which is between 512 - 8k depending on the number of rows.

Then the buffer will be set to max buffer size or the actual row size, whichever is smaller.

I'll make that change and publish a new beta for testing.

**Comment by brianhks** [comment]
I've addressed the bytebuffer that is loaded for each row which will drastically reduce memory requirements.  I'm saving further enhancements until after 1.0 release.
