### ISSUE TITLE
Kairos fails to start when no logback.xml present

### ISSUE THREAD

**Issue by dayman** [kairosdb/kairosdb#174]
If there is no logback.xml in classpath Kairos doesn't start with

```
Exception in thread "main" java.lang.NullPointerException
  at org.kairosdb.core.Main.main(Main.java:231)
```

**Comment by paladini** [comment]
This issue has been solved, @brianhks ? If so, can we close it?

**Comment by jsabin** [comment]
Looks like this issue has been resolved.
