### ISSUE TITLE
Too many open files error

### ISSUE THREAD

**Issue by kadian1470** [kairosdb/kairosdb#175]
From kairosdb I am getting ""errors"=>["Too many open files"]}"
Kairos version is kairosdb-0.9.5 Beta 2
 ls -l /proc/7921/fd | grep kairos_cache | grep -v '(delete)' | wc -l
1238

ls /proc/7921/fd | grep kairos_cache | grep -v '(delete)'> 

lrwx------ 1 root root 64 May 20 09:21 1000 -> /tmp/kairos_cache/1432127700008/c13a7c4f68b6dcfecfebcd514ca5fb01.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1001 -> /tmp/kairos_cache/1432127700008/f63bf7ef67918daf270950807ed59f22.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1002 -> /tmp/kairos_cache/1432127700008/dfc1d1fca3e7957db23d5c0f71f786c5.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1003 -> /tmp/kairos_cache/1432127700008/fb6485ed654229a803d1a6b3e624f4d9.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1004 -> /tmp/kairos_cache/1432127700008/22090a3b8698aa4cd71ba1ce57d0e495.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1005 -> /tmp/kairos_cache/1432127700008/78310c4098e5a25452826b5827ff4779.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1006 -> /tmp/kairos_cache/1432127700008/f96efa0592271f5f4a4d8fae7083a9e.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1007 -> /tmp/kairos_cache/1432127700008/22090a3b8698aa4cd71ba1ce57d0e495.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1008 -> /tmp/kairos_cache/1432127700008/78310c4098e5a25452826b5827ff4779.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1009 -> /tmp/kairos_cache/1432127700008/f96efa0592271f5f4a4d8fae7083a9e.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1010 -> /tmp/kairos_cache/1432127700008/1c288bc2774aeda793ef0ea06d743f47.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1011 -> /tmp/kairos_cache/1432127700008/ff08838d8c5f4d5b9221823d7a5ce6e.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1012 -> /tmp/kairos_cache/1432127700008/94ed2597d7c6fe5838ecfbea431aa7d0.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1013 -> /tmp/kairos_cache/1432127700008/4ce1b6cc19fb0d4cb204e5b4c78eb177.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1014 -> /tmp/kairos_cache/1432127700008/185601942a37435ac8d4d6f4665a8375.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1015 -> /tmp/kairos_cache/1432127700008/a929c9b08d7a4ea291405964f300b647.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1016 -> /tmp/kairos_cache/1432127700008/133393ff774992ae10137cc06926ed02.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1017 -> /tmp/kairos_cache/1432127700008/4638c722ef71c900552660db77466f1c.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1018 -> /tmp/kairos_cache/1432127700008/30f2db98ccd973fdf451b35333bb82b2.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1019 -> /tmp/kairos_cache/1432127700008/1c288bc2774aeda793ef0ea06d743f47.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1020 -> /tmp/kairos_cache/1432127700008/ff08838d8c5f4d5b9221823d7a5ce6e.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1021 -> /tmp/kairos_cache/1432127700008/94ed2597d7c6fe5838ecfbea431aa7d0.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1022 -> /tmp/kairos_cache/1432127700008/4ce1b6cc19fb0d4cb204e5b4c78eb177.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1023 -> /tmp/kairos_cache/1432127700008/185601942a37435ac8d4d6f4665a8375.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1024 -> /tmp/kairos_cache/1432127700008/a929c9b08d7a4ea291405964f300b647.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1025 -> /tmp/kairos_cache/1432127700008/133393ff774992ae10137cc06926ed02.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1026 -> /tmp/kairos_cache/1432127700008/127fe4b351391e813daba69e9dbb471e.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1027 -> /tmp/kairos_cache/1432127700008/22090a3b8698aa4cd71ba1ce57d0e495.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1028 -> /tmp/kairos_cache/1432127700008/78310c4098e5a25452826b5827ff4779.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1029 -> /tmp/kairos_cache/1432127700008/f96efa0592271f5f4a4d8fae7083a9e.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1030 -> /tmp/kairos_cache/1432127700008/1c288bc2774aeda793ef0ea06d743f47.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1031 -> /tmp/kairos_cache/1432127700008/ff08838d8c5f4d5b9221823d7a5ce6e.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1032 -> /tmp/kairos_cache/1432127700008/94ed2597d7c6fe5838ecfbea431aa7d0.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1033 -> /tmp/kairos_cache/1432127700008/fabc1bd8400396192090de448867639c.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1034 -> /tmp/kairos_cache/1432127700008/7182aea74b1d86fd76e29fa7693570c2.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1035 -> /tmp/kairos_cache/1432127700008/f4db38086f6fd11a2c6f24d2089fa81e.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1036 -> /tmp/kairos_cache/1432127700008/db4f33adf726681bdeeffdcd3901f12e.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1037 -> /tmp/kairos_cache/1432127700008/8b52eda80e5773631e01f2414df6d74a.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1038 -> /tmp/kairos_cache/1432127700008/a80e86190b354615e69a9bc151cb8284.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1039 -> /tmp/kairos_cache/1432127700008/93a97004dce4e440d7945dc561b4edb.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1040 -> /tmp/kairos_cache/1432127700008/c13a7c4f68b6dcfecfebcd514ca5fb01.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1041 -> /tmp/kairos_cache/1432127700008/f63bf7ef67918daf270950807ed59f22.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1042 -> /tmp/kairos_cache/1432127700008/4638c722ef71c900552660db77466f1c.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1043 -> /tmp/kairos_cache/1432127700008/30f2db98ccd973fdf451b35333bb82b2.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1044 -> /tmp/kairos_cache/1432127700008/fabc1bd8400396192090de448867639c.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1045 -> /tmp/kairos_cache/1432127700008/dfc1d1fca3e7957db23d5c0f71f786c5.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1046 -> /tmp/kairos_cache/1432127700008/fb6485ed654229a803d1a6b3e624f4d9.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1047 -> /tmp/kairos_cache/1432127700008/93a97004dce4e440d7945dc561b4edb.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1048 -> /tmp/kairos_cache/1432127700008/c13a7c4f68b6dcfecfebcd514ca5fb01.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1049 -> /tmp/kairos_cache/1432127700008/127fe4b351391e813daba69e9dbb471e.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1050 -> /tmp/kairos_cache/1432127700008/f63bf7ef67918daf270950807ed59f22.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1051 -> /tmp/kairos_cache/1432127700008/93a97004dce4e440d7945dc561b4edb.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1052 -> /tmp/kairos_cache/1432127700008/c13a7c4f68b6dcfecfebcd514ca5fb01.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1053 -> /tmp/kairos_cache/1432127700008/f63bf7ef67918daf270950807ed59f22.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1054 -> /tmp/kairos_cache/1432127700008/4638c722ef71c900552660db77466f1c.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1055 -> /tmp/kairos_cache/1432127700008/30f2db98ccd973fdf451b35333bb82b2.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1056 -> /tmp/kairos_cache/1432127700008/fabc1bd8400396192090de448867639c.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1057 -> /tmp/kairos_cache/1432127700008/7182aea74b1d86fd76e29fa7693570c2.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1058 -> /tmp/kairos_cache/1432127700008/f4db38086f6fd11a2c6f24d2089fa81e.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1059 -> /tmp/kairos_cache/1432127700008/db4f33adf726681bdeeffdcd3901f12e.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 1060 -> /tmp/kairos_cache/1432127700008/8b52eda80e5773631e01f2414df6d74a.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1061 -> /tmp/kairos_cache/1432127700008/4638c722ef71c900552660db77466f1c.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1062 -> /tmp/kairos_cache/1432127700008/30f2db98ccd973fdf451b35333bb82b2.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1063 -> /tmp/kairos_cache/1432127700008/fabc1bd8400396192090de448867639c.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1064 -> /tmp/kairos_cache/1432127700008/b9fc22e7e3c901f6fb55b3d4f23a8ca6.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1065 -> /tmp/kairos_cache/1432127700008/b9fc22e7e3c901f6fb55b3d4f23a8ca6.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1066 -> /tmp/kairos_cache/1432127700008/3af44a5339bf70b9b27d08c226ef6d18.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1067 -> /tmp/kairos_cache/1432127700008/4298aea5fe855d78ede0f808050934fa.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1068 -> /tmp/kairos_cache/1432127700008/b502236cb3e2ad7e0abdce83ea03683c.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1069 -> /tmp/kairos_cache/1432127700008/c12762f6d01644e9226a98a335ef7b03.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1070 -> /tmp/kairos_cache/1432127700008/4117ea8931e8fee5e3ba7032c1772a25.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1071 -> /tmp/kairos_cache/1432127700008/df7e9d1d3b062fbcb81fa6acf4950e5c.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1072 -> /tmp/kairos_cache/1432127700008/3af44a5339bf70b9b27d08c226ef6d18.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1073 -> /tmp/kairos_cache/1432127700008/4298aea5fe855d78ede0f808050934fa.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1074 -> /tmp/kairos_cache/1432127700008/44b1ed3f59012ee0f3f17b2f8a254073.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1075 -> /tmp/kairos_cache/1432127700008/dfc1d1fca3e7957db23d5c0f71f786c5.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1076 -> /tmp/kairos_cache/1432127700008/fb6485ed654229a803d1a6b3e624f4d9.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1077 -> /tmp/kairos_cache/1432127700008/127fe4b351391e813daba69e9dbb471e.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1078 -> /tmp/kairos_cache/1432127700008/b9fc22e7e3c901f6fb55b3d4f23a8ca6.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1079 -> /tmp/kairos_cache/1432127700008/3af44a5339bf70b9b27d08c226ef6d18.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1080 -> /tmp/kairos_cache/1432127700008/4298aea5fe855d78ede0f808050934fa.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1081 -> /tmp/kairos_cache/1432127700008/5e9e2f92956fcb4c1d1c7c9315834225.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1082 -> /tmp/kairos_cache/1432127700008/8089e9a83c803022a4adb49c5799f488.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1083 -> /tmp/kairos_cache/1432127700008/2a064b427ac133411f22b541457e1a1b.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1084 -> /tmp/kairos_cache/1432127700008/9dc8c37fd2c7ee4210ea3385039861ad.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1085 -> /tmp/kairos_cache/1432127700008/dfc1d1fca3e7957db23d5c0f71f786c5.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1086 -> /tmp/kairos_cache/1432127700008/fb6485ed654229a803d1a6b3e624f4d9.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1087 -> /tmp/kairos_cache/1432127700008/127fe4b351391e813daba69e9dbb471e.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1088 -> /tmp/kairos_cache/1432127700008/b9fc22e7e3c901f6fb55b3d4f23a8ca6.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1089 -> /tmp/kairos_cache/1432127700008/3af44a5339bf70b9b27d08c226ef6d18.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1090 -> /tmp/kairos_cache/1432127700008/4298aea5fe855d78ede0f808050934fa.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1091 -> /tmp/kairos_cache/1432127700008/b502236cb3e2ad7e0abdce83ea03683c.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1092 -> /tmp/kairos_cache/1432127700008/c12762f6d01644e9226a98a335ef7b03.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1093 -> /tmp/kairos_cache/1432127700008/4117ea8931e8fee5e3ba7032c1772a25.data (deleted)
lrwx------ 1 root root 64 May 20 09:22 1094 -> /tmp/kairos_cache/1432127700008/df7e9d1d3b062fbcb81fa6acf4950e5c.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1095 -> /tmp/kairos_cache/1432127700008/b44020c8f5ea733688d4ad7cefa4abca.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1096 -> /tmp/kairos_cache/1432127700008/417a3fe2a993f09b75bd74e4fc8f4808.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1097 -> /tmp/kairos_cache/1432127700008/507ab636dc1018a07cdbd352aa00f8f2.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1098 -> /tmp/kairos_cache/1432127700008/8089e9a83c803022a4adb49c5799f488.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1099 -> /tmp/kairos_cache/1432127700008/b44020c8f5ea733688d4ad7cefa4abca.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1100 -> /tmp/kairos_cache/1432127700008/a80e86190b354615e69a9bc151cb8284.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1101 -> /tmp/kairos_cache/1432127700008/5e9e2f92956fcb4c1d1c7c9315834225.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1102 -> /tmp/kairos_cache/1432127700008/2a064b427ac133411f22b541457e1a1b.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1103 -> /tmp/kairos_cache/1432127700008/9dc8c37fd2c7ee4210ea3385039861ad.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1104 -> /tmp/kairos_cache/1432127700008/318bfbcb5ffca5ccc393350cd7d65987.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1105 -> /tmp/kairos_cache/1432127700008/996f5a79868c7dece7c0c9df7ac3cb92.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1106 -> /tmp/kairos_cache/1432127700008/694a7ac72245e1f41d6fcc3bb6a6363a.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1107 -> /tmp/kairos_cache/1432127700008/6fd745c201b837cb20f0b65a54d926dc.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1108 -> /tmp/kairos_cache/1432127700008/a80e86190b354615e69a9bc151cb8284.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1109 -> /tmp/kairos_cache/1432127700008/d79940ae59e5aeb322e277e296523b89.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1110 -> /tmp/kairos_cache/1432127700008/5e9e2f92956fcb4c1d1c7c9315834225.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1111 -> /tmp/kairos_cache/1432127700008/2a064b427ac133411f22b541457e1a1b.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1112 -> /tmp/kairos_cache/1432127700008/9dc8c37fd2c7ee4210ea3385039861ad.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1114 -> /tmp/kairos_cache/1432127700008/33525cfac702a08ce95d54cf682eb891.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1115 -> /tmp/kairos_cache/1432127700008/89866d7a922fbaee79edcb2d08e089e4.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1116 -> /tmp/kairos_cache/1432127700008/53774a93c00596ef083f1c907ad5f19f.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1117 -> /tmp/kairos_cache/1432127700008/f0a6de5f6ab1871fcd974bb4f49d9855.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1118 -> /tmp/kairos_cache/1432127700008/2157031e5b8267e2f9ad614619d9a94d.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1119 -> /tmp/kairos_cache/1432127700008/8089e9a83c803022a4adb49c5799f488.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1120 -> /tmp/kairos_cache/1432127700008/b44020c8f5ea733688d4ad7cefa4abca.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1121 -> /tmp/kairos_cache/1432127700008/a80e86190b354615e69a9bc151cb8284.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1122 -> /tmp/kairos_cache/1432127700008/5e9e2f92956fcb4c1d1c7c9315834225.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1123 -> /tmp/kairos_cache/1432127700008/2a064b427ac133411f22b541457e1a1b.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1124 -> /tmp/kairos_cache/1432127700008/9dc8c37fd2c7ee4210ea3385039861ad.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1125 -> /tmp/kairos_cache/1432127700008/318bfbcb5ffca5ccc393350cd7d65987.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1126 -> /tmp/kairos_cache/1432127700008/996f5a79868c7dece7c0c9df7ac3cb92.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1127 -> /tmp/kairos_cache/1432127700008/694a7ac72245e1f41d6fcc3bb6a6363a.data (deleted)
lrwx------ 1 root root 64 May 20 09:24 1128 -> /tmp/kairos_cache/1432127700008/6fd745c201b837cb20f0b65a54d926dc.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1129 -> /tmp/kairos_cache/1432127700008/81443c9518e61c58c608edc7a2a3dac3.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1130 -> /tmp/kairos_cache/1432127700008/5498633a8d0a1d7fabb807ad1a79ff7e.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1131 -> /tmp/kairos_cache/1432127700008/34143740a5cb150bcb6831dfb4e330a8.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1132 -> /tmp/kairos_cache/1432127700008/176cd0e04d3b282715fe764c8c755a38.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1133 -> /tmp/kairos_cache/1432127700008/a38d05ae422a322458490ee4492a6b1b.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1134 -> /tmp/kairos_cache/1432127700008/5034ec092a5c7f409b505b8fe1a226f2.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1135 -> /tmp/kairos_cache/1432127700008/4abb9dda4734ccd91a8be89fd75037f9.data (deleted)
lrwx------ 1 root root 64 May 20 09:29 1136 -> /tmp/kairos_cache/1432127700008/3eda02f006cb9893cfb69f5f2e26be26.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1137 -> /tmp/kairos_cache/1432127700008/33525cfac702a08ce95d54cf682eb891.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1138 -> /tmp/kairos_cache/1432127700008/f0a6de5f6ab1871fcd974bb4f49d9855.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1139 -> /tmp/kairos_cache/1432127700008/2157031e5b8267e2f9ad614619d9a94d.data (deleted)
lrwx------ 1 root root 64 May 20 09:29 1140 -> /tmp/kairos_cache/1432127700008/1682a9ea4aa0433f0fe1d67c8277de32.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1141 -> /tmp/kairos_cache/1432127700008/33525cfac702a08ce95d54cf682eb891.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1142 -> /tmp/kairos_cache/1432127700008/f0a6de5f6ab1871fcd974bb4f49d9855.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1143 -> /tmp/kairos_cache/1432127700008/2157031e5b8267e2f9ad614619d9a94d.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1144 -> /tmp/kairos_cache/1432127700008/81443c9518e61c58c608edc7a2a3dac3.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1145 -> /tmp/kairos_cache/1432127700008/5498633a8d0a1d7fabb807ad1a79ff7e.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1146 -> /tmp/kairos_cache/1432127700008/34143740a5cb150bcb6831dfb4e330a8.data (deleted)
lrwx------ 1 root root 64 May 20 09:29 1147 -> /tmp/kairos_cache/1432127700008/2612f4957ea1792d3b60251cb07d274d.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1148 -> /tmp/kairos_cache/1432127700008/81443c9518e61c58c608edc7a2a3dac3.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1149 -> /tmp/kairos_cache/1432127700008/5498633a8d0a1d7fabb807ad1a79ff7e.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1150 -> /tmp/kairos_cache/1432127700008/34143740a5cb150bcb6831dfb4e330a8.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1151 -> /tmp/kairos_cache/1432127700008/176cd0e04d3b282715fe764c8c755a38.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1152 -> /tmp/kairos_cache/1432127700008/a38d05ae422a322458490ee4492a6b1b.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1153 -> /tmp/kairos_cache/1432127700008/5034ec092a5c7f409b505b8fe1a226f2.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1154 -> /tmp/kairos_cache/1432127700008/4abb9dda4734ccd91a8be89fd75037f9.data (deleted)
lrwx------ 1 root root 64 May 20 09:29 1155 -> /tmp/kairos_cache/1432127700008/98b5b7ef7bd9bf1ebef4a32576fd761e.data (deleted)
lrwx------ 1 root root 64 May 20 09:29 1156 -> /tmp/kairos_cache/1432127700008/fd7c5445d7ffb694346ae756a8ec7be8.data (deleted)
lrwx------ 1 root root 64 May 20 09:29 1157 -> /tmp/kairos_cache/1432127700008/80f2d02373e0a34a7478362f3f00c062.data (deleted)
lrwx------ 1 root root 64 May 20 09:29 1158 -> /tmp/kairos_cache/1432127700008/53774a93c00596ef083f1c907ad5f19f.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1159 -> /tmp/kairos_cache/1432127700008/723f799410a6ec98ce8f9fdfbc38e4c3.data
lrwx------ 1 root root 64 May 20 09:25 1160 -> /tmp/kairos_cache/1432127700008/33525cfac702a08ce95d54cf682eb891.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1161 -> /tmp/kairos_cache/1432127700008/f0a6de5f6ab1871fcd974bb4f49d9855.data (deleted)
lrwx------ 1 root root 64 May 20 09:25 1162 -> /tmp/kairos_cache/1432127700008/2157031e5b8267e2f9ad614619d9a94d.data (deleted)
...
lrwx------ 1 root root 64 May 20 09:21 997 -> /tmp/kairos_cache/1432127700008/5c5c3bb8aa2eebcad963172d61acfc1.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 998 -> /tmp/kairos_cache/1432127700008/94ed2597d7c6fe5838ecfbea431aa7d0.data (deleted)
lrwx------ 1 root root 64 May 20 09:21 999 -> /tmp/kairos_cache/1432127700008/93a97004dce4e440d7945dc561b4edb.data (deleted)

**Comment by brianhks** [comment]
Can you give me some info about your usage?  These files are created by doing queries.  The cache file cleaner is what deletes them.  What is your cleaning schedule set up for and does the out of file handles coincide with the cleaning?

**Comment by kadian1470** [comment]
I am using the Bin groupby to query multiple records about every 60 seconds. The cache file cleaner schedule is set to 15 minutes. I can't see any out of file handles coincide with the cleaning. I am seeing a lot errors in the logs saying:
ERROR [Group.java:194] - Could not delete group file: /tmp/grouper-......cache

**Comment by brianhks** [comment]
OK this got it done.
