### ISSUE TITLE
Tag order in QueryMetric cache String

### ISSUE THREAD

**Issue by rdettai** [kairosdb/kairosdb#178]
Hi! 

I have a (tiny) problem with the cache string used for the cache file name hash. You use a concatenation of name|tags|start|stop (maybe not in that order).

The hash should be independent of the order the tags are specified in, but it is not the case because you are using a HashSetMultimap. I would recommend a TreeMultimap instead, because both its keys and values are ordered.

I know this should almost never occur, but it still would be an improvement.

Hope I'm not pointing out something that has already been discussed.

Regards

**Comment by rdettai** [comment]
Never mind, I think I got confused. Tags are already deserialized into a TreeMultimap!

**Comment by brianhks** [comment]
No problem, don't mind an extra set of eyes looking through my code.
