### ISSUE TITLE
New confusing dead code

### ISSUE THREAD

**Issue by rdettai** [kairosdb/kairosdb#179]
I ran into some dead code again while trying to extend the API. As it is a bit confusing, I prefer to signal it!

The method `public void format(Writer writer, List<List<DataPointGroup>> data)` is never used. The query response is currently built by `public void formatQuery(List<DataPointGroup> queryResults, boolean excludeTags, int sampleSize)` in JsonResponse.

**Comment by jsabin** [comment]
This code is actually being used in MetricsResource.ValuesStreamingOuput. JsonFormatter is added as a formatter.
