### ISSUE TITLE
package-deb requires X11 display ?

### ISSUE THREAD

**Issue by sebdg** [kairosdb/kairosdb#185]
Hi all, 

I'm trying to build a debian package from the repository.
This is on a remote server without X11 hence the explicit message when i ran  :
java make package-deb
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

Is there a way to get around this X11 requirement by arguments orso ?
What is supposed to require a display in building the packages ?

Building the jar itself works.

Kind Regards

**Comment by brianhks** [comment]
The deb package is created using alien.  Alien requires a root password to run (why? I have no idea).  Anyway the build script pops up a dialog to prompt for the password and then passes it to alien, the magic happens on line 357 of the build.groovy.  You can set resp = 0 and then set password on line 363 to your password and run it again without getting the popup.

Yes total hack, it is on my todo list to improve this.

**Comment by sebdg** [comment]
Hi Brian, 

I 'alienized' the package with alien itself to get me out easy.
I was root (yes i know totally bad and as hacky as above) 
so maybe the script can check for dumb root users like me too :) 
or issue a "sudo" requirement warning

Regards

**Comment by brianhks** [comment]
Just added a command line option -D sudo=<your password>

This gets around the prompt.
