### ISSUE TITLE
duration in setStart should be long type

### ISSUE THREAD

**Issue by jsabin** [kairosdb/kairosdb#198]
This is a request for a change to the client, but needs to be changed first in Kairos:

When quering for DataPoints, it should be possible to enter long value for TimeUnit.MILLISECONDS. For example, last query has timestamp=1413537893570, and next query will be System.currentTimeMillis()-timestamp. Integer.MAX_VALUE is sometimes too small, and changing units to SECONDS/HOURS is not precise enough.

**Comment by brianhks** [comment]
done
