### ISSUE TITLE
Whether the kairosdb relies on the seed node of Cassandra cluster?

### ISSUE THREAD

**Issue by dominicwu1981** [kairosdb/kairosdb#199]
Cassandra version: 2.1.8
kairosdb version: 1.0.0
cluster: 3 machines [A(seed node), B, C]

Details:
It works perfectly when all 3 machines are up and running, but if the seed node is down, the kairosdb CAN NOT write data into cluster anymore.
If using the cqlsh(Cassandra built-in) client, the data still CAN be written into cluster even the seed node is down.
It seems like the kairosdb relies on the seed node. right? If so, could you pls provide a method to let kairosdb does not rely on seed node?

**Comment by lcoulet** [comment]
Hi, what is your replication factor and your KairosDB settings for read and write consistency?

If you have a replication factor greater than one, stop a node, and ask KairosDB to write with Quorum or All the writes will fail.

What nodes did you configure in KairosDB as available coordinators? All of them or just the seed node?

KairosDB is not relying on the seed node, this is Cassandra internal as far as I understand. Maybe however it can affect Hector auto discovery, but I cannot tell.

Oh, there's also something else I recently discovered, whan a node used by KairosDB is unavailable, Hector may be stuck for a long while and fail queries. You may need setup the property kairosdb.datastore.cassandra.hector.cassandraThriftSocketTimeout to fix this.

**Comment by dominicwu1981** [comment]
The first thing I want to say is thank you very much!
You are right. The replication factor and write consistency I set is 2 and Quorum. Now the Kairosdb can write data into cluster after changing the write consistency level to ONE even the seed node is down.

And I have another problem to be solved, hope you can help me, thank you!
As we know, the node Kairosdb used is called coordinator. But if the coordinator is down when writing data into cluster, I think the writes should fail. So, does Kairosdb has some kind of mechanism like DNS? That means just use the name to manipulate the Cassandra cluster.
For example, the cluster name is “DemoCluster”, and there are 3 nodes 192.168.1.1, 192.168.1.2 and 192.168.1.3 in it. We just use cluster name “DemoCluster” to manipulate the cluster, the cluster will use 192.168.1.1 as coordinator. If 192.168.1.1 is down, the cluster will switch the coordinator to 192.168.1.2 automatically to keep the operation not fail.

**Comment by lcoulet** [comment]
You're welcome.

I recommend putting the three nodes in kairosdb.properties (or at least 3 of them). Hector (the library interacting with cassandra) will do load-balancing and failover between the three nodes.

Alternatively you may turn on Hector autodiscovery, but if your coordinator is down and you restart kairosDB it won't be able to reach Cassandra until this single node is restarted.

Loic

**Comment by dominicwu1981** [comment]
As to the write consistency Quorum, could you please tell me why the writes failed if replication factor is 2 and write consistency level is Quorum in a 3 nodes cluster when 1 node is down?
Quorum = (replication factor / 2) + 1
In this case, the Quorum should be 2. So, even if 1 node is down, there are 2 nodes still alive in the cluster. The lived nodes equals to Quorum, I think the writes should be success. Why it failed?

**Comment by lcoulet** [comment]
There are 2 nodes alive on 3, So the node down is serving replica tokens for 1/2 of the data considering the RF of 2, so half of write queries and read queries would fail with consistency QUORUM.
If you want a RF of 2 and extreme availability you should change the consistency to ANY so your queries will succeed.
Alternatively you may change your RF to 3 to solve the quorum issue.
Cf. http://www.datastax.com/dev/blog/modern-hinted-handoff

**Comment by dominicwu1981** [comment]
Thank you very much for helping me a lot!

**Comment by dominicwu1981** [comment]
Closed.
