### ISSUE TITLE
Limitations on the metric field format

### ISSUE THREAD

**Issue by spicoflorin** [kairosdb/kairosdb#215]
Hello!
 I would like to know if the KairosDB has "inherited" the limitation of the OPenTSDB regarding the naming metric:
"Metric names, tag names and tag values have to be made of alpha numeric characters, dash "-", underscore "_", period ".", and forward slash "/", as is enforced by the package-private function Tags.validateString" (http://opentsdb.net/docs/build/html/user_guide/query/timeseries.html#precisions-on-metrics-and-tags)
We have a case study where we have to accept metric names with special chars (such as @,|| etc).
 I look forward for your answers.
Thanks.
 Florin

**Comment by brianhks** [comment]
Well we did at first but now we support anything in the metric name, the tags still have restrictions, see https://github.com/kairosdb/kairosdb/issues/60

**Comment by FrEaKmAn** [comment]
and slash is not recommended also #196
