### ISSUE TITLE
Reset database to default (with no data)

### ISSUE THREAD

**Issue by paladini** [kairosdb/kairosdb#217]
I was inserting a lot of test data inside my KairosDB database and now that I understand how it works, I would like to reset the KairosDB database to default, deleting all data that I've inserted.

I already take a look at the documentation and I just found [how to remove data points by using a query](http://kairosdb.github.io/website/docs/build/html/restapi/DeleteDataPoints.html), but I have created a lot of waste test data and I don't even remember tags and names that I used. Check it manually will take me a lot of time.

There's a easy way to reset my KairosDB database to default?

**Comment by FrEaKmAn** [comment]
You could delete the KairosDB keyspace (if using Cassandra) or H2 data file. KairosDB will recreate it.

Other option is to delete metrics - http://kairosdb.github.io/website/docs/build/html/restapi/DeleteMetric.html

PS: I'm still working on email reply :)

**Comment by paladini** [comment]
Sorry, but how can I delete KairosDB keyspace? 

For the future, I think an API endpoint or documentation on how to do that would be awesome. Also, there's some bugs in KairosDB website, can I help you fixing this bugs and adding some documentation?

**Comment by FrEaKmAn** [comment]
You will need to check the Cassandra docs - http://docs.datastax.com/en/cql/3.0/cql/cql_reference/drop_keyspace_r.html

I don't think there should be an API endpoint as there is no need to delete all the data in the production. Plus one bad request and ALL your data is gone. 

Sure, new contributions are always welcomed.

**Comment by paladini** [comment]
Thank you, I'll take a look in your link.

**Comment by paladini** [comment]
Thank you, this works!

**To reset your KairosDB database to default, run something like that:**
```bash
# Enter Cassandra Query Language terminal
cqlsh
 
# Drop kairosdb keyspace (don't use "cqlsh>" before the command)
cqlsh> DROP KEYSPACE kairosdb ; 

# Exit Cassandra Query Language terminal (don't use "cqlsh>" before the command)
cqlsh> exit

# Stopping KairosDB
sudo /opt/kairosdb/bin/kairosdb.sh stop

# Running KairosDB
sudo /opt/kairosdb/bin/kairosdb.sh start
```

The last command will recreate your kairosdb keyspace. Now it should be empty, enjoy ;)
