### ISSUE TITLE
Adding data points that are not timestamp ordered

### ISSUE THREAD

**Issue by spicoflorin** [kairosdb/kairosdb#218]
Hello!
   I have the following scenario: 
1. A client should add sensor timestamped data representing a day ( e.g.27.09) into a data storage
2. After the client persisted its data into the storage, he wants to persist data from from a previous day (25.09)
 I found out that OpenTSDB cannot cope with this scenario due to a strong validation condition that you cannot add data that is less than latest written timestamp (see https://github.com/OpenTSDB/opentsdb/issues/572) 
Has KairosDB same string condition regarding the data?

**Comment by FrEaKmAn** [comment]
I'm not aware of this problem with KairosDB. We have similar situation where sometimes internet breaks down and clients send old data in random order.

**Comment by lcoulet** [comment]
Hello, there is no such limitation in KairosDB.

You may insert data with any timestamp in any order.



2015-09-23 14:15 GMT+02:00 spicoflorin <notifications@github.com>:

**Comment by brianhks** [comment]
No such limitation here.
