### ISSUE TITLE
start_relative not working in query

### ISSUE THREAD

**Issue by zxwing** [kairosdb/kairosdb#220]
I found the start_relative not working in the query API()tested with both KairosDB 1.0 and 0.9.4-6. The data samples is like:

<pre>
[{
    "name": "archive.file.tracked",
    "timestamp": 1443074690,
    "type": "long",
    "value": 123,
    "tags":{"host":"test"}
},
{
    "name": "archive.file.search",
    "timestamp": 1443074690,
    "type": "double",
    "value": 32.1,
    "tags":{"host":"test"}
}]
</pre>

The query works fine with start_absolute:
<pre>
{
  "start_absolute":1,
  "metrics": [
    {
      "name": "archive.file.tracked"
    }
  ]
}
</pre>

returns:

<pre>
{
    "queries": [
        {
            "sample_size": 1,
            "results": [
                {
                    "name": "archive.file.tracked",
                    "group_by": [
                        {
                            "name": "type",
                            "type": "number"
                        }
                    ],
                    "tags": {
                        "host": [
                            "test"
                        ]
                    },
                    "values": [
                        [
                            1443074690,
                            123
                        ]
                    ]
                }
            ]
        }
    ]
}
</pre>

However, the query returns nothing if I change to start_relative:

<pre>
{
  "start_relative": {
                "value": 10,
                "unit": "years"
  },
  "metrics": [
    {
      "name": "archive.file.tracked"
    }
  ]
}
</pre>

returns:

<pre>
{
    "queries": [
        {
            "sample_size": 0,
            "results": [
                {
                    "name": "archive.file.tracked",
                    "group_by": [
                        {
                            "name": "type",
                            "type": "number"
                        }
                    ],
                    "tags": {
                        "host": [
                            "test"
                        ]
                    },
                    "values": []
                }
            ]
        }
    ]
}
<pre>

**Comment by lcoulet** [comment]
Hi, your data appears to be "somewhen" in 1970, or close to :)

The timestamps is in Unix milliseconds, while you are clearly using Unix
seconds in the absolute start time query.

**Comment by zxwing** [comment]
thanks @lcoulet. I confirm it's the issue of timestamp. Close this ticket.
