### ISSUE TITLE
Cassandra column limit

### ISSUE THREAD

**Issue by weirdy** [kairosdb/kairosdb#224]
Hi, sorry for probably stupid question. But what will happen when I reach the 2 billion columns limit ?

Let's say I'm going to push data points every millisecond to the same metric for several months or years. Will it fail or the data will be spread within several rows automatically ?

**Comment by gdchamal** [comment]
values for a metric and its associated tag are stored in a C* row for 3 weeks. After Kairosdb create a new row to store more values.

See https://kairosdb.github.io/kairosdocs/CassandraSchema.html for details about how row key is made.

**Comment by weirdy** [comment]
Thank you, I've just run the test application which send data each millisecond to one metric. Here the list of row_key_index columns I have after several minutes:
![row_key_index](https://cloud.githubusercontent.com/assets/4169171/10318590/e1dc150c-6c72-11e5-8711-7af2fac076bc.png)

Why kairosdb has created 10 rows for one metric?
How can I interpret these names ?

**Comment by lcoulet** [comment]
Hi,
Are you sure data sent is time stamped with Unix  millisecond (and not
second or microsecond ). Are you using several data types (eg.
Float,int,string...)?

Thank you, I've just run the test application which send data each
millisecond to one metric. Here the list of row_key_index columns I have
after several minutes:
[image: row_key_index]
<https://cloud.githubusercontent.com/assets/4169171/10318590/e1dc150c-6c72-11e5-8711-7af2fac076bc.png>

Why kairosdb has created 10 rows for one metric?
How can I interpret these names ?

—
Reply to this email directly or view it on GitHub
<https://github.com/kairosdb/kairosdb/issues/224#issuecomment-145960270>.

**Comment by weirdy** [comment]
yes, indeed, you were right, I was sending incorrect timestamps. Thank you!
