### ISSUE TITLE
NPE while trying to insert a legacy datapoint

### ISSUE THREAD

**Issue by llange** [kairosdb/kairosdb#227]
I'm facing the following NPE while trying to insert a legacy datapoint:

```
1:16:34.794 [qtp636682417-41 Selector0] DEBUG [SelectorManager.java:843] - created SCEP@4b4a87fb{l(/127.0.0.1:50048)<->r(/127.0.0.1:8080),s=0,open=true,ishut=false,oshut=false,rb=false,wb=false,w=true,i=0}-{AsyncHttpConnection@a25965b,g=HttpGenerator{s=0,h=-1,b=-1,c=-1},p=HttpParser{s=-14,l=0,c=0},r=0}
01:16:34.797 [qtp636682417-46] DEBUG [HttpParser.java:281] - filled 356/356
01:16:34.805 [qtp636682417-46 - /api/v1/datapoints] DEBUG [Server.java:365] - REQUEST /api/v1/datapoints on AsyncHttpConnection@a25965b,g=HttpGenerator{s=0,h=-1,b=-1,c=-1},p=HttpParser{s=2,l=33,c=123},r=1
01:16:34.806 [qtp636682417-46 - /api/v1/datapoints] DEBUG [ContextHandler.java:942] - scope null||/api/v1/datapoints @ o.e.j.s.ServletContextHandler{/,null}
01:16:34.806 [qtp636682417-46 - /api/v1/datapoints] DEBUG [ContextHandler.java:1014] - context=||/api/v1/datapoints @ o.e.j.s.ServletContextHandler{/,null}
01:16:34.806 [qtp636682417-46 - /api/v1/datapoints] DEBUG [ServletHandler.java:415] - servlet |/api|/v1/datapoints -> org.eclipse.jetty.servlet.DefaultServlet-44b58962
01:16:34.808 [qtp636682417-46 - /api/v1/datapoints] DEBUG [ServletHandler.java:477] - chain=com.google.inject.servlet.GuiceFilter-5150252->org.eclipse.jetty.servlet.DefaultServlet-44b58962
01:16:34.810 [qtp636682417-46 - /api/v1/datapoints] DEBUG [ServletHandler.java:1464] - call filter com.google.inject.servlet.GuiceFilter-5150252
01:16:34.822 [qtp636682417-46 - /api/v1/datapoints] DEBUG [LoggingFilter.java:45] - 127.0.0.1 - /api/v1/datapoints
01:16:34.861 [qtp636682417-46 - /api/v1/datapoints] ERROR [MetricsResource.java:267] - Failed to add metric.
org.kairosdb.core.exception.DatastoreException: java.lang.NullPointerException
	at org.kairosdb.datastore.cassandra.CassandraDatastore.putDataPoint(CassandraDatastore.java:379) ~[kairosdb-1.0.0-1.jar:1.0.0-1.20151007235445]
	at org.kairosdb.core.datastore.KairosDatastore.putDataPoint(KairosDatastore.java:182) ~[kairosdb-1.0.0-1.jar:1.0.0-1.20151007235445]
	at org.kairosdb.core.http.rest.json.JsonMetricParser.validateAndAddDataPoints(JsonMetricParser.java:330) ~[kairosdb-1.0.0-1.jar:1.0.0-1.20151007235445]
	at org.kairosdb.core.http.rest.json.JsonMetricParser.parse(JsonMetricParser.java:97) ~[kairosdb-1.0.0-1.jar:1.0.0-1.20151007235445]
	at org.kairosdb.core.http.rest.MetricsResource.add(MetricsResource.java:233) ~[kairosdb-1.0.0-1.jar:1.0.0-1.20151007235445]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_80]
...
Caused by: java.lang.NullPointerException: null
	at org.kairosdb.datastore.cassandra.CassandraDatastore.putDataPoint(CassandraDatastore.java:306) ~[kairosdb-1.0.0-1.jar:1.0.0-1.20151007235445]
	... 60 common frames omitted
01:16:35.023 [qtp636682417-46 - /api/v1/datapoints] DEBUG [Server.java:367] - RESPONSE /api/v1/datapoints  500 handled=true
```

Here is the command line I run:
```
$ curl -s -XPOST -d '[{ "name": "debugkairosdb.spooky", "timestamp": 1413613069978, "value": 1, "tags": {"host": "server2"} , "type": "legacy"}]' http://localhost:8080/api/v1/datapoints | jq .
{
  "errors": [
    "java.lang.NullPointerException"
  ]
}
```

I setup the [configuration file](https://github.com/kairosdb/kairosdb/blob/develop/src/main/resources/kairosdb.properties#L20) with the proper parameter (beware: it should be kairosdb.datapoints.factory.legacy, not kairosdb.datapoint.factory.legacy).

According to my first diagnostic, I found that : 
* Exceptions occurs in [CassandraDatastore.java#L306](https://github.com/kairosdb/kairosdb/blob/2ace7308431dcb3621ac28351a9d1b2682235000/src/main/java/org/kairosdb/datastore/cassandra/CassandraDatastore.java#L306) because dataPoint is null.
* The null datapoint comes from dataPointFactory.createDataPoint() in  [JsonMetricParser.java#L330-L331](https://github.com/kairosdb/kairosdb/blob/2ace7308431dcb3621ac28351a9d1b2682235000/src/main/java/org/kairosdb/core/http/rest/json/JsonMetricParser.java#L330-L331)
* This datapoint is null according to the comment in [LegacyDataPointFactory.java#L78](https://github.com/kairosdb/kairosdb/blob/2ace7308431dcb3621ac28351a9d1b2682235000/src/main/java/org/kairosdb/core/datapoints/LegacyDataPointFactory.java#L78)

For the moment I don't know what would be the best way to deal with that.

Any idea ?

**Comment by FrEaKmAn** [comment]
Interesting bug. I think it's because of really strange implementation of the legacy datapoints.

Any reason why you are using legacy datapoints?

**Comment by llange** [comment]
Because we can... ! =)

In fact this bug occurred during a testing phase in a migration preparation. We were evaluating the ability to run a cluster of mixed-version KairosDB - older 0.9.3 version running alongside newer 1.0.x version ; while still allowing older version to be able to read data stored by new version.
At first we did not understand that new versions were able to read old datapoints without any configuration or tweaks.

But, because of this bug, and thanks to the fact that new versions were able to read old data, we could work around it and upgrade first our reading servers, then our writing ones.

So we are not using legacy datapoints any more.

**Comment by brianhks** [comment]
Yes the newer server was not designed to write to the old format.  If anyone is running the older server they just need to upgrade and not look back.  The new server will read the old format so no data will be lost.
