### ISSUE TITLE
move data from SSD to HDD

### ISSUE THREAD

**Issue by weirdy** [kairosdb/kairosdb#230]
hi, probably it's mostly a question about Cassandra rather than kairosdb, however kairosdb schema could be important here.

Is there any way to move old data points to HDD storage within the same cluster ?

Is it somehow possible to manage what sstables are placed where in Cassandra ?
Looks like it's possible according to the documentation (http://docs.datastax.com/en/cassandra_win/2.2/cassandra/dml/dmlHowDataWritten.html):
> Cassandra creates a subdirectory for each table, which allows you to symlink a table to a chosen physical drive or data volume. This provides the capability to move very active tables to faster media, such as SSDs for better performance, and also divides tables across all attached storage devices for better I/O balance at the storage layer.

But I've no idea how to do that and I couldn't find any info about 'symlink'...

**Comment by lcoulet** [comment]
symlink is a symbolic link.

1. stop Cassandra.
2. Move your files to SSD
3. create symbolink links in the old location to your new location (e.g. ln
-s command)
4. restart Cassandra


2015-10-16 8:47 GMT+00:00 Khorev Ilya <notifications@github.com>:

> hi, probably it's mostly a question about Cassandra rather than kairosdb,
> however kairosdb schema could be important here.
>
> Is there any way to move old data points to HDD storage within the same
> cluster ?
>
> Is it somehow possible to manage what sstables are placed where in
> Cassandra ?
> Looks like it's possible according to the documentation (
> http://docs.datastax.com/en/cassandra_win/2.2/cassandra/dml/dmlHowDataWritten.html
> ):
>
> Cassandra creates a subdirectory for each table, which allows you to
> symlink a table to a chosen physical drive or data volume. This provides
> the capability to move very active tables to faster media, such as SSDs for
> better performance, and also divides tables across all attached storage
> devices for better I/O balance at the storage layer.
>
> But I've no idea how to do that and I couldn't find any info about
> 'symlink'...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kairosdb/kairosdb/issues/230>.
>



-- 


Cordialement,
Loic COULET

**Comment by weirdy** [comment]
Thanks for your anwsers! It would be really nice if you also help with the following questions:

1. Is it any chance to make a symlink to another node in the cluster ?

2. In terms of Kairosdb schema, all datapoints of all metrics are stored within one column family. How can I figure out which data is old and good candidates for moving to slow node ?
There are several .db files in the 'data_points' folder in kairosdb keyspace on my computer. When new .db file is created ? It it correct that the data points of one metric can be placed in several .db files ?
![kairosdb_data_points](https://cloud.githubusercontent.com/assets/4169171/10541569/c56bbb34-741a-11e5-9b79-17d5b2e27bfc.png)

3. Am I right that the only chance to influence on the data distribution (as I need) is to use symlinks ?

Thanks in advance.

**Comment by lcoulet** [comment]
It looks like you are running Cassandra on Windows. It's fine for testing
-  but every big data solution I know about really suck on Windows (when
they are compatible) and Cassandra & Datastax do not perform as well on
Windows as they do on Linux.
Therefore, I would not recommend to run Cassandra on Windows in production,
but to setup a Linux host or cluster then.

for the symlinks on Windows the command is not "ln -s" but mklink.

I would put the whole data_points folder to the SSD (therefore the entire
CF), if you move only some SSTABles it will mess with Cassandra compaction.
Anyway it doesn't make much sense.
Actually if I were you I would put the whole kairosDB keyspace on SSD, the
index tables are tiny compared to data_points, but they would really
benefit a lot from the SSD performances.

If I understand correctly you want to move your older SSTables to spninning
HDD and keep recent data on SSD, is that correct?
I believe you could relocate older SSTables (based on latest modification
time), and it should work, but I am afraid that the Cassandra compaction
would screw it up from time to time.

What is the volume of data you are managing in KairosDB? KairosDB is quite
efficient for storage, and SSD start being quite affordable, so maybe you
don't need spinning HDDs at all.


2015-10-16 12:37 GMT+00:00 Khorev Ilya <notifications@github.com>:

> Thanks for your anwsers! It would be really nice if you also help with the
> following questions:
>
>    1.
>
>    Is it any chance to make a symlink to another node in the cluster ?
>    2.
>
>    In terms of Kairosdb schema, all datapoints of all metrics are stored
>    within one column family. How can I figure out which data is old and good
>    candidates for moving to slow node ?
>    There are several .db files in the 'data_points' folder in kairosdb
>    keyspace on my computer. When new .db file is created ? It it correct that
>    the data points of one metric can be placed in several .db files ?
>    [image: kairosdb_data_points]
>    <https://cloud.githubusercontent.com/assets/4169171/10541569/c56bbb34-741a-11e5-9b79-17d5b2e27bfc.png>
>    3.
>
>    Am I right that the only chance to influence on the data distribution
>    (as I need) is to use symlinks ?
>
> Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kairosdb/kairosdb/issues/230#issuecomment-148705456>.
>



-- 


Cordialement,
Loic COULET

**Comment by weirdy** [comment]
One of the requirements is to store data for 10 and more years. The throughput must be quite big - - ability to write up to 50000 points/sec. So I will probably will end up having several Cassandra nodes.

And another requirement is to have ability to store historic data (let's say - the data which added earlier than 1 year ago) on HDD nodes since they will not frequently used.

**Comment by lcoulet** [comment]
Wow, this is different from what you asked for...I don't think you can
shard data that way.

But you may have a simple and efficient solution using 2 clusters.

One with SSD only and short TTL so you have only recent data.
The other simultaneously stores all the data on  HDD permanently.

As always (and specially in distributed systems): the simpler the better.

The beauty of Cassandra is it's apparently  simple model for sharding and
replicating data. You may put yourself in a difficult mess if you want to
redefine the Cassandra randompartirionner based on time or worst like SST
age (which I don't think is possible anyway unless you use symlinks and NFS
and you shouldn't).

**Comment by weirdy** [comment]
thank you, very helpful as usual!

**Comment by brianhks** [comment]
My gut says to just use hdd but make the cluster large,  If you want to store 10 years of data I'm guessing a 30 node cluster.  A cluster that big will perform really well and I doubt you will need ssd.

OK now for the hypothetical could you do it idea.  In theory the time tiered compaction strategy will compact files until they get to a certain age and then not touch them again.  If you had ssd's and hdds on the same machine you could migrate these SSTables over to the hdd's and then symlink to them.  It would have to be on the same node, trying to move the sstable to another node will cause you nothing but grief.

For a less crazy idea I would just setup two clusters.  One with crazy big drives for historical data and another that has a ttl set to limit the data to just a few months.  The first you configure for space and the second you configure for speed.  With two clusters you can easily scale the systems independently based on the individual requirements.
