### ISSUE TITLE
Build Package and Install on Debian

### ISSUE THREAD

**Issue by sebdg** [kairosdb/kairosdb#234]
Hi Brian, 
I tried to build a package and install from the git repo and there are some errors during the process.
My server is headless and it seams that the packaging build process still requires some X11 display to be attached.

Creating build/jar/kairosdb-1.0.0-SNAPSHOT-1.jar
Building RPM build/rpm/kairosdb-1.0.0-SNAPSHOT-1.rpm
Exception tablesaw.TablesawException: org.codehaus.groovy.runtime.InvokerInvocationException: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
org.codehaus.groovy.runtime.InvokerInvocationException: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

I had this once earlier and went to alien to build the rpm and then covert to debian.
However that path seems broken too :  All went well till the scripts part.
Then i got this error : 

/etc/init.d/kairosdb: line 52: syntax error: unexpected end of file
dpkg: error processing package kairosdb (--install):
 subprocess installed post-installation script returned error exit status 2

It's the last line of the file, so i guess some typo is not closing the case orzo, bu didn't see at first glance.

Hope this helps for future releases.
Kind Regards

**Comment by trikosuave** [comment]
Similar with rpm:
/etc/init.d/kairosdb: line 52: syntax error: unexpected end of file

There is no 'fi' in the service script for 
```
     15 if [ -f /etc/init.d/functions ]
     16     . /etc/init.d/functions
     17
```

**Comment by at15** [comment]
there is a pr for this issue, see #236

**Comment by brianhks** [comment]
I've got a fix for the init script.  Here  is some documentation for building the deb without X11: https://github.com/kairosdb/kairosdb/wiki/Frequently-Asked-Questions#why-does-the-build-for-deb-require-x11
