### ISSUE TITLE
get keyspace size

### ISSUE THREAD

**Issue by weirdy** [kairosdb/kairosdb#237]
Hi

Is it possible to retrieve the keyspace size programmatically? I know there is no such feature in kairosdb, I'm wondering how to do this using any cassandra client (if it's possible).

>nodetool cfstats

This command allows to do that, but it does not fit to me cause I want to get the size within my code remotely.

Any ideas ?

**Comment by brianhks** [comment]
You may be able to do it by doing a cql query against the system partition (totally a guess).  I'm not directly aware of any api to get it.  Try asking on a Cassandra forum.
