### ISSUE TITLE
Providing range while querying KairosDB through pythonscript

### ISSUE THREAD

**Issue by shilpisharma** [kairosdb/kairosdb#240]
Hi,

I am trying to figure out a problem. In my measurement/table in KairosDB one of the tags is insertion_timestamp. Something like '10/03/15'. If I want to query data inserted in last month, so filter such data I want to essentially check if tag value '10/03/15' lies in last month. But when I look at example in documentation it asks for absolute values like insertion_timestamp='1/3/15'. Is there any way to provided a range or use greater than/smaller than for numerical values of tags.

Is there some way I can model this in a JSON query which we pass to Kairos REST API?

Also, does JSON requests support subqueries?

Thanks,
Shilpi

**Comment by brianhks** [comment]
Gah!!! tag values should be static.  This will ultimately kill your performance.  

Each data point has a timestamp associated with it already.  Tags should be used for things like host name or data center.  All data is queried by time (time series) so if you want to grab the data from a certain data it is pretty easy.  Tags let you group your data within a metric, like cpu # or network interface.

Sub queries are not supported.
