### ISSUE TITLE
Data with TTL not deleted after expiration

### ISSUE THREAD

**Issue by spynode** [kairosdb/kairosdb#247]
Hi. I am using two different KairosDB 1.0.1 instances, each with it's own Cassandra server. On both,  kairosdb.datastore.cassandra.datapoint_ttl=1296000 (15 days) is configured. On both Cassandras, DateTieredCompactionStrategy is used for kairosdb keyspace. Right now this period has well passed but old data on both instances is still there. As there is no comprehensive documentation on KairosDB TTL functionality, it is hard to troubleshoot such issue. I have slighty different compaction configuration on each Cassandra:
1) compaction = {'max_sstable_age_days': '365', 'base_time_seconds': '3600', 'timestamp_resolution': 'MICROSECONDS', 'tombstone_compaction_interval': '1', 'tombstone_threshold': '.01', 'class': 'org.apache.cassandra.db.compaction.DateTieredCompactionStrategy'}

2) compaction = {'timestamp_resolution': 'MILLISECONDS', 'max_sstable_age_days': '365', 'base_time_seconds': '3600', 'class': 'org.apache.cassandra.db.compaction.DateTieredCompactionStrategy'}

Is TTL in KairosDB implemented to use Cassandras column TTL and Cassandra is responsible for cleaning up old data? CQL query 'select ttl(value) from kairosdb.data_points;' returns 'null' on each row. Running major compaction does not remove supposedly expired data. Are there any potential pitfalls regarding TTL functionality which I might have missed? Thanks.

**Comment by FrEaKmAn** [comment]
I think this problem should be resolved in 1.1.1 version. Can you please test with newest version?

**Comment by spynode** [comment]
Thanks, I will try it. Do you think this should work with existing data from 1.0.1?

**Comment by brianhks** [comment]
The per metric ttl that you can pass in as part of the data point was introduced in 1.1.0 and subsequently fixed in 1.1.1.  The ttl (in seconds) is passed on to Cassandra.  The ttl is on the data point and not the row.  I honestly do not know if it will show up in a cql query.  We added unit tests that ensure the functionality does work.
