### ISSUE TITLE
kairosdb as windows service

### ISSUE THREAD

**Issue by weirdy** [kairosdb/kairosdb#251]
Hi, sorry probably for stupid question.

Is it somehow possible to create kairosdb as a Windows Service ? It threre any workaround to do this ?

**Comment by at15** [comment]
you can have a look at jetty's doc http://www.eclipse.org/jetty/documentation/current/startup-windows-service.html , it uses https://commons.apache.org/proper/commons-daemon/procrun.html to wrap a java application as service.

**Comment by at15** [comment]
@weirdy have you solved this, problem do you mind post your solution here and close the issue? thx.

**Comment by weirdy** [comment]
Not yet solved, hopefully will be solved soon since I've managed to do the same but for Cassandra.

**Comment by weirdy** [comment]
Here's our solution:
https://github.com/kairosdb/kairosdb/pull/268
