### ISSUE TITLE
Save to Json and Save to CSV buttons no longer work

### ISSUE THREAD

**Issue by sonofaforester** [kairosdb/kairosdb#253]
They pop up in a weird location and nothing happens when you click on them.

**Comment by paladini** [comment]
The question is very generic. Can you give more details about your issue?

**Comment by sonofaforester** [comment]
Well, when using the web ui, the Save to Json and Save to CSV buttons no longer work, they pop up in a weird location and nothing happens when you click on them. I'm sorry if that's generic, not sure how to be more specific.

**Comment by jsabin** [comment]
Fixed
