### ISSUE TITLE
Unit of of the Read and Write Buffers in Configuration File

### ISSUE THREAD

**Issue by juergenc** [kairosdb/kairosdb#254]
Hello,

one question: which unit have the following configuration parameters for that buffers, bytes or kilobytes?
* kairosdb.datastore.cassandra.write_buffer_max_size
* kairosdb.datastore.cassandra.single_row_read_size
* kairosdb.datastore.cassandra.multi_row_read_size

Thanks,
Jürgen

**Comment by brianhks** [comment]
It is the number of data points.  It doesn't translate directly to a size in bytes.  For the read values it is the number of columns to read from Cassandra where each column is a single data point.
