### ISSUE TITLE
Compress old logs to reduce storage space

### ISSUE THREAD

**Issue by paladini** [kairosdb/kairosdb#258]
As [I have reported here](https://groups.google.com/forum/#!topic/kairosdb-group/Iqcv7UD_bZg), KairosDB isn't compressing old logs to reduce storage space. The library that KairosDB use for logging is called [Logback](http://logback.qos.ch/) and already have a feature to enable log compression - we just need to use it.

As I said in the [KairosDB Group on Google Groups](https://groups.google.com/forum/#!forum/kairosdb-group), about 17 logs are taking more than 15GB from my hard disk drive and none of the log files was compressed. 

This's a interesting feature to implement as soon as possible, because it can improve KairosDB overall performance at storing files and managing it's own space.

**Comment by brianhks** [comment]
Merged pull request.
