### ISSUE TITLE
Add metrics together, average and general functions (InfluxDB like)

### ISSUE THREAD

**Issue by paladini** [kairosdb/kairosdb#264]
I'm using [Grafana](http://grafana.org/) to show KairosDB data in a given internal webpage and we have a demand to add some metrics, make the average of other ones, but seems that Grafana can't do that by himself and [expects the database implement these functions](https://github.com/grafana/grafana/issues/490).

I've checked InfluxDB documentation and [they have "functions" to do things like mean, sums, average, etc.](https://docs.influxdata.com/influxdb/v0.10/query_language/functions/), so Grafana can call InfluxDB methods and "execute" this sort of functions for the final user, displaying the desired content.

There's any plans to implement something like that soon? If I would like to code that for KairosDB, what should I know? Which files should I take a look?

**Comment by paladini** [comment]
Aggregators is what I'm looking for? 

http://kairosdb.github.io/docs/build/html/restapi/Aggregators.html

**Comment by brianhks** [comment]
Yes aggregators are what you are looking for.  And we have a truck load of them.
