### ISSUE TITLE
Will some data be lost when stopping Kairosdb ?

### ISSUE THREAD

**Issue by weirdy** [kairosdb/kairosdb#266]
I know that data is stored in buffer before sending it to Cassandra. 
Am I right that this buffer is persisted only in memory which means that some data can be lost after stopping Kairosdb ? Are such cases somehow handled in Kairosdb ?

**Comment by weirdy** [comment]
OK, I will answer to my questions by myself.
Looks like such cases are handled in the code, and the background buffer writer threads will be normally finished if the shutdown action is triggered. 
Here is the code which is responsible for this part:
https://github.com/kairosdb/kairosdb/blob/develop/src/main/java/org/kairosdb/core/Main.java#L284-L302

Now I'm wondering why there is no "stop" command. It would be much convenient to run this command instead of terminating the process within Windows service.

**Comment by brianhks** [comment]
The trick is passing a command to a running process.  In the code we try to catch the kill command and shutdown.  if there is another way of signalling a java process in windows I'm all ears.

**Comment by weirdy** [comment]
Thanks for clarifications.

**Comment by weirdy** [comment]
So, I've checked this and looks like this code is not executed on Windows.
There is nothing connected with `logger.info("Shutting down");` in the log file.

I was trying to stop the process by closing the console or by running of the following command: 
`taskkill /pid 9060 /f` 

Any ideas ? This is super critical for us

**Comment by weirdy** [comment]
#268
