### ISSUE TITLE
Implement health check api end point to return 200 

### ISSUE THREAD

**Issue by farzadpanahi** [kairosdb/kairosdb#271]
Right now /api/v1/health/check returns 204 if everything is good, which makes totally sense. But some not so smart load balancers such as Amazon ELB treat anything other that 200 as unhealthy. 

I suggest to add an endpoint like /api/v1/health/checkElbComptabile (I bet we can name it better), to return 200 instead of 204 so that we can use kairosdb behind Amazon ELB with good confidence. 

I know in general, this is really more Amazon's issue, but they are not listening: 
https://forums.aws.amazon.com/thread.jspa?messageID=706087&#706087

If this makes sense I can send a pull request.

**Comment by FrEaKmAn** [comment]
I would probably make more sense to have /api/v1/health/check/200 where 200 is the status you want to have returned if everything is OK.

**Comment by farzadpanahi** [comment]
You mean /api/v1/health/check/<response-code-if-ok>  ? I don't think letting the user choose the response code that wide is a good idea. But having a fixed endpoint like /api/v1/health/check/200 looks ok to me.

**Comment by brianhks** [comment]
Simple solution was to make the response code configurable so, that is what I did.
