### ISSUE TITLE
/health endpoint should not require authorization

### ISSUE THREAD

**Issue by farzadpanahi** [kairosdb/kairosdb#279]
load balancers usually need to check the health of the nodes using an endpoint and usually you don't get to have the option of setting username password in the load balancer for health check endpoint.

I propose removing the authorization for health check endpoint.

**Comment by FrEaKmAn** [comment]
Health check has authorization?

**Comment by farzadpanahi** [comment]
When you enable basic authorization for jetty in config, /health endpoint asks for authorization too!

**Comment by gillesdemey** [comment]
I'm having the same issue using GCE healthchecks on Kubernetes
