### ISSUE TITLE
Limit access to measurements in kairosdb (access permission, user-roles)

### ISSUE THREAD

**Issue by shilpisharma** [kairosdb/kairosdb#282]
Hi,

I wanted to ask if there is a provision or feature in kairosdb where we can control access to different measurements in kairosdb. Say I have 3 measurements and I want user to be able to access only one of those, is there a way I can handle that?

Also what level of control is possible: Admin/owner/user (view only) or (read/write).

**Comment by FrEaKmAn** [comment]
There is nothing in the KairosDB. You can solve this with a plugin or with API gateway..
