### ISSUE TITLE
how to post data to kairosdb with basic_auth

### ISSUE THREAD

**Issue by james1986** [kairosdb/kairosdb#284]
I just enable kairodb's http basic authentication, then I get 401 when post data to the db. how to post data through the account password authentication?

**Comment by BrianJoyce** [comment]
Same here ...

**Comment by brianhks** [comment]
I just tested this with the master branch which is 1.1.1 and the develop branch and both work.

Here is what I set in the kairosdb.properties
`kairosdb.jetty.basic_auth.user=admin`
`kairosdb.jetty.basic_auth.password=stinker`

Then I used the following curl statement to post data
`curl --user admin:stinker --data-binary @$1 --header "Content-Type: application/json" http://$host/api/v1/datapoints`

This worked for both cases.  $1 is a file that contains the json post of data.

**Comment by BrianJoyce** [comment]
Thanks for the quick reply.  Yes you're right this works when using curl or the api.  The issue is when it's used with the grafana/kairosdb-datasource plugin it doesn't work.  I'm guessing the issue is on the grafana/kairosdb-datasource side.  Will raise it there.

**Comment by biswaKL** [comment]
Is this still wotking?
