### ISSUE TITLE
Handle Empty Queries Consistently

### ISSUE THREAD

**Issue by andremleblanc** [kairosdb/kairosdb#285]
This issue occurs when querying data from `/api/v1/datapoints/query`. 

When using a POST request, an error message is returned:
`{"errors":["query.metric[] must have a size of at least 1"]}` - if body contains an empty hash. 
`{"errors":["Not a JSON Object: null"]}` - if body is completely empty.

When using a GET request, a 500 is returned as HTML.
It would be preferable if the GET request returned the same message as the POST request in JSON.

**Comment by brianhks** [comment]
Can you give us an example of a query that will produce this?  We are not able to reproduce it.

**Comment by brianhks** [comment]
Found the problem and fixed it.
