### ISSUE TITLE
Add tags to existing data

### ISSUE THREAD

**Issue by paladini** [kairosdb/kairosdb#287]
I have hundreds of thousands of data and I would like to add some new tags to this data. There's a simple way to do that without needing to query all the data, delete all old point values and reinsert all the data with the new tags?

**Comment by nuebar** [comment]
+1

**Comment by bmandrade** [comment]
Anyone have more info on this?

**Comment by brianhks** [comment]
The problem is that the tags are essentially part of the primary key in C*.  In the case of C* the primary/partition key determines where the data is stored in the cluster.  If C* let you modify the partition key it would most likely require moving the data to another node.

**Comment by Abouzeid** [comment]
@brianhks 
Any new update on this because I am facing the same problem. 
Do I still need to delete the data and reinsert them again with the new tag?
Thanks.
