### ISSUE TITLE
Official docker support

### ISSUE THREAD

**Issue by at15** [kairosdb/kairosdb#288]
[Docker](https://www.docker.com/) can make it easier for people to get started with Kairosdb, There are already some unofficial images. But most of them do not have multiple versions, ie: only have 1.1.0. Also we can use [docker compose](https://docs.docker.com/compose/overview/) to have Kairosdb run with Cassandra easily. 

Possible scenarios:
- run Kairosdb locally without installing JDK and Cassandra on local machine.
- use Kairosdb in CI. (GitLab CI supports using docker image)
- use Docker image for production deployment

Existing docker images on [dockerhub](https://hub.docker.com/):
- https://hub.docker.com/r/wangdrew/kairosdb/ 100k+ pulls
- https://hub.docker.com/r/mbessler/archlinux-kairosdb/ 5.5k pulls
- https://hub.docker.com/r/kowens/kairosdb-statsd/ 1.4k pulls (but does not have description)

I have already made one following [this dockerfile](https://hub.docker.com/r/mbessler/archlinux-kairosdb/~/dockerfile/), it is not published yet, the repo is [here](https://github.com/cit-lab/kairosdb/tree/master). And I have a few questions for Kairosdb environment setup
- Which version of JDK is prefered? JDK7 or JDK8.
- Which version of Cassandra is prefered?

Thanks~

**Comment by gillesdemey** [comment]
I'd also like to see some of these questions answered to move this issue forward. 

Being able to use docker would be helpful for both local development as well as setting up a test environment.

It gets the installation hassle out of the way and like @at15 mentioned is helpful for Jenkins and other CI systems.

**Comment by zbintliff** [comment]
The docker file I use looks like this (alpine is much smaller):

```
FROM java:8-alpine

RUN apk upgrade libssl1.0 --update-cache && \
    apk add wget ca-certificates bash
RUN wget -O /tmp/kairosdb_1.1.1-1.tar.gz \
    https://github.com/kairosdb/kairosdb/releases/download/v1.1.1/kairosdb-1.1.1-1.tar.gz

RUN mkdir -p /opt/ && \
    cd /opt/ && \
    tar -xvf /tmp/kairosdb*

COPY conf/kairosdb.properties /opt/kairosdb/conf/kairosdb.properties

EXPOSE 4242 8080 2003 2004
ENTRYPOINT [ "/opt/kairosdb/bin/kairosdb.sh"]
CMD [ "run" ]
```

Then my docker-compose just uses the Version '2' to create a network so cassandra and kairos can talk.

**Comment by brianhks** [comment]
So either java 7 or 8.  Cassandra 2.2 is probably best, make sure thrift is turned on.

I've used docker once or twice and it is cool.  What is the best way to maintain such an image?  Anyone have any pointers?

**Comment by at15** [comment]
@brianhks docker images can be managed via [docker-hub](https://docs.docker.com/docker-hub/). Most opensource projects I know use it. (Private and self host are also provided with [price](https://www.docker.com/pricing)). Some examples are listed below

Grafana
- on docker hub https://hub.docker.com/r/grafana/grafana/
- source https://github.com/grafana/grafana-docker
- official doc for usage http://docs.grafana.org/installation/docker/

Opentsdb
- on docker hub https://hub.docker.com/r/petergrace/opentsdb-docker/
- source https://github.com/PeterGrace/opentsdb-docker

I haven't play with docker for a while and know little about docker compose, other guys subscribed to this issue may provide you with more useful information. The one provided by @zbintliff is pretty nice, alpine is indeed much smaller and he is using [docker compose](https://docs.docker.com/compose/)

**Comment by at15** [comment]
@zbintliff when using docker-compose, you must wait for several seconds so Cassandra is running and listening on the Thrift port, otherwise KaiorsDB will fail at start #307. I use [a fork of wait for it sh](https://github.com/vishnubob/wait-for-it/pull/6) to handle [this problem](https://docs.docker.com/compose/startup-order/) I have a complete example [here](https://github.com/xephonhq/xephon-b/tree/master/script/kairosdb) based on your comment, thanks for the hints.

Also Cassandra complains about not using Oracle JDK, does KairosDB have similar requirement @brianhks . It seems Oracle JDK images are no longer available in docker hub due to copyright issue from Oracle.

**Comment by brianhks** [comment]
Kairos doesn't care what jre it runs on.  I know C* is pretty picky.  I'll look into this with the CQL driver to see how much I have to go through to get kairos up without C*.

**Comment by Itja** [comment]
So the milestone here is probably a 1.2.x version?

**Comment by ivan-gallego** [comment]
I made a sample docker-compose file for running Kairos with a Cassandra node as a backend:

[](https://github.com/ivan-gallego/kairosdb-docker)

Hope it helps!

**Comment by brianhks** [comment]
I've just used docker compose and it is really powerful.  Ivan I like what you have done but running with C* is completely unnecessary.  Just use the H2 datastore.  What I would like to setup is a compose file running Kairos and grafana together.  That would be very nice.

**Comment by ivan-gallego** [comment]
If you need another backend or different configuration for Kairos, you can modify 'kairosdb.properties' in the /conf folder and rebuild the docker image.

Also, stay tuned for the grafana + kairos! I'll post any updates here.

**Comment by viktorsmari** [comment]
Is there an official one yet?
Or should I use this instead: https://hub.docker.com/r/wangdrew/kairosdb/ ?

**Comment by brianhks** [comment]
Nothing official yet.  I'll post something when 1.2 is finalized.

**Comment by gucharbon** [comment]
@brianhks  Any update on the subject? Do you plan to ship it with th e1.3 release? 

I'm still working on docker images and docker-compose scenarios involving using HAProxy and Docker swarm, I stopped working on it for a whole month but I'm back on it. Our goal is to have a ready-to-use secured KairosDB cluster served with minimal configuration and Cassandra as backend. 

Do you think about specific requirements that the images or Dockerfiles shoud fulfill ?

**Comment by gucharbon** [comment]
What about :

**Comment by kirapwn** [comment]
I still do not see any official docker images. Will there be one anytime soon? 
Otherwise, I will have to host my own one.
