### ISSUE TITLE
Need Kairosdb Grafana Templated Queries Example

### ISSUE THREAD

**Issue by gitvegas** [kairosdb/kairosdb#292]
In the Value Options Query im simply saying - "tag_names()". But nothing comes up in the list. Can some one provide an example of a Query i can use. Im keeping everything else default.

**Comment by samuelbenhamou** [comment]
Hi,
tbh it was a bit obscure for me to but managed to get it working. You need to specify a metric you are storing as the kairos module does not call the tagnames or tagvalues endpoint (http://ip:8080/api/v1/tagnames/ or http://ip:8080/api/v1/tagvalues/) but goes through a query:

- tag_names(collectd.cpu.percent.active.value)
- tag_values(collectd.cpu.percent.active.value,host)

One thing which did not work though was filtering through the grafana UI (like selecting a set of hosts ) which made me alter the grafana plugin directly to make it work (originally if you put something like tags:host=$host, the list was returned as a single array index as a string and kairos did not understand it)
I'll contact the plugin maintainers to ask them about it
