### ISSUE TITLE
Kairosdb Log file

### ISSUE THREAD

**Issue by JavadMajidi** [kairosdb/kairosdb#294]
Hi,
i need to find kairosdb log file to see the input data points time or query time or used space for data points and etc. but what i as log file found is full of kairos activity but no such information.
how can i find these information?

**Comment by priyankt68** [comment]
I believe what you want is not logged 'by default' in kairosdb. You might have to add those logs yourselves and then you should be able to see logs for query time and data points storage space.

**Comment by brianhks** [comment]
What you are after is in the metrics reported by Kairos.  http://kairosdb.github.io/docs/build/html/Statistics.html
