### ISSUE TITLE
the last-aggregator problem

### ISSUE THREAD

**Issue by zhaoyn2016** [kairosdb/kairosdb#297]
the two dataPoints {10.2，1465883270}，{20.2，1465969670} ，when I use last-aggregator ，I hope 
return {20.2，1465969670}，but it return {20.2，1465883270}，It seems that the timestamp did not update.
see code on org.kairosdb.core.aggregator.LastAggregator  63 line，I think it need add a line 
returnTime=dp.getTimestamp()  after 63 line

**Comment by brianhks** [comment]
So if align start time is false then it will report the timestamp of the last data point.
