### ISSUE TITLE
Chaining aggregated data from non-numeric types doesn't work properly

### ISSUE THREAD

**Issue by lcoulet** [kairosdb/kairosdb#298]
After aggregating non-numeric data types (e.g. count per minute of strings data points), the results data set is still within a group with "type"="string". Therefore the plotting doesn't happen in the Web UI.
Fixing plotting can be done by deactivating the check if the data type to plot is numeric (and let the plotting library -e.g. flot - deal with the data), but it's only fixing the symptom not the problem.

The real problem is more annoying: Aggregators interface are missing a method to define what type is provided as an outcome. E.g. daily average of a 5-minutes count of a string metric will simply not work,  because the average aggregator cannot aggregate strings (it is simply noit aware that it gets numbers out from the previous level of aggregation thanks to count aggregator).

There is a design issue that must be addressed for using properly the data types with all the aggregation possibilities. 

In fixing the issue, an aggregator shall be capable or returning the same type as was provided in input whatever it is (e.g. first/last) or a fixed type (e.g. count).

**Comment by brianhks** [comment]
Pull request #304 addresses some of this.  I'll need to modify it to pass the resulting type out to the query results.
