### ISSUE TITLE
Slow read

### ISSUE THREAD

**Issue by rangilboa** [kairosdb/kairosdb#300]
Hi,
I am new to KairosDB, 
We are use 1 KairosDB Node and 3 Cassandra Nodes to monitor our deployment resources.
Each resource has 30 metrics, each metric has 3 tags (Resource ID, Resource Type, Business-Unit) 

The system is running for few months, 
The max number kairosdb.datastore.write_size is 2000/sec (average of 1500/sec)
The batch insert is very fast (interval between samples is 1min).

Reading is very slow (few good seconds) when reading all 30 metrics for 1 week for 1 resource (Resource ID) 

is it typical?
What can I do to improve the read, target is 200ms?

stats:
kairosdb.http.request_time : 5000 ms
kairosdb.http.query_time: 1021 ms
kairosdb.datastore.query_time: 800 ms
kairosdb.datastore.query_row_count 200 ms

**Comment by brianhks** [comment]
If you are querying for all 30 metric in one request the queries are handled sequentially.  What is the sample size?

The change to CQL that is underway will also improve the query performance.
