### ISSUE TITLE
Cannot connect to Cassandra 2.2 and higher

### ISSUE THREAD

**Issue by aplsek** [kairosdb/kairosdb#308]
kairosdb can't connect to newer versions of cassandra.
Probably due to thrift-client deprecation.

Tried 3.3 and 2.7. The 2.1 worked.

**Comment by FrEaKmAn** [comment]
afaik, thrift is removed/disabled from version 3.0, so 2.x with thrift manually enabled is required. 

Cassandra version 2.7?

**Comment by sciffer** [comment]
2.2 works for me.

**Comment by killerwhile** [comment]
thrift (RPC) is disabled by default. Set `start_rpc: true` in `cassandra.yaml` for future restarts, and enable thrift at runtime with `nodetool enablethrift`.

**Comment by RamakrishnaAddanki** [comment]
I tried with 3.3 Cassandra by setting start_rpc: true and it is creating keyspace of kairosdb with data_points and other columnfamilies. This means it is working with 3.3 cassandra right??

**Comment by brianhks** [comment]
Yes you can still use it with Cassandra 3.x but you have to turn thrift on in order to do so.  We are adding cql support as part of another issue.
