### ISSUE TITLE
Kairosdb TTL support for Telnet

### ISSUE THREAD

**Issue by gitvegas** [kairosdb/kairosdb#309]
We submit data via telnet, is there a way we can include TTL?

**Comment by burtonator** [comment]
I would love to see this happen...

**Comment by burtonator** [comment]
oh.. ok.. so you basically reserve a custom tag and the parse that out?

What if there were a namespace for custom kairosdb tags?

For example... kairosdb.ttl as a tag would automatically fix the TTL?  This way people could just start using it now and we could also add other kairosdb options in the future.

**Comment by brianhks** [comment]
I've made a change so if you add kairos_opt.ttl=30 as a tag to your telnet call it will set the ttl to 30.  The tag doesn't show up in your data.
