### ISSUE TITLE
Duration in REST API is inconsistent: sometimes uses string, sometimes number for value in JSON

### ISSUE THREAD

**Issue by thomastoye** [kairosdb/kairosdb#311]
The [`Duration`](https://github.com/kairosdb/kairosdb/blob/develop/src/main/java/org/kairosdb/core/datastore/Duration.java) class tracks a duration using a time unit and a value. In JSON, the value is sometimes represented as a string, sometimes as a number.

Example of unit as a number in JSON (https://kairosdb.github.io/docs/build/html/restapi/Aggregators.html#range-aggregator):

```
"aggregators": [
{
  "name": "sum",
  "align_sampling": true,
  "align_start_time": true,
  "sampling": {
    "value": 1, // <---
    "unit": "minutes"
  }
}]
```

Example of unit as a string in JSON (https://kairosdb.github.io/docs/build/html/restapi/TimeGrouping.html#example):

```
"group_by": [
      {
        "name": "time",
        "group_count": "168",
        "range_size": {
          "value": "1", // <---
          "unit": "hours"
        }
      }
]
```

Which one should be used? Are they parsed the same by the JSON parser?

**Comment by brianhks** [comment]
This is already addressed in the develop branch.
