### ISSUE TITLE
Publish tgz in maven central

### ISSUE THREAD

**Issue by tsachev** [kairosdb/kairosdb#319]
We are building an app that is going to be a kairosdb package with some preconfigured plugins. Our build is maven based and it cloud be awesome if the `tgz` package was in central.

Another option would be to publish two more artifacts with the bin scripts and webroot.

**Comment by brianhks** [comment]
The tgz is published here to github (https://github.com/kairosdb/kairosdb/releases/tag/v1.1.1), is that the one you want?  I wasn't aware that maven central would allow us to publish a tar file of our binaries.

**Comment by tsachev** [comment]
Yes that's the one I want but I want to use it in my maven build. I could download the tgz with maven wagon, but instead I would like to declare it as dependency like

```
<groupId>org.kairosdb</groupId>
<artifactId>kairosdb</artifactId>
<type>tgz</type>
```


Jetty is one example project that publishes its tgz in central 
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.3.11.v20160721/

**Comment by brianhks** [comment]
Excellent, I will look into it.

**Comment by brianhks** [comment]
I have augmented the build to add the tar.gz.  I just released it so it may take a few hours to show up in maven central.
