### ISSUE TITLE
Delete single datapoint from a time range

### ISSUE THREAD

**Issue by bugsend** [kairosdb/kairosdb#320]
How can I delete just one datapoint from a specified time range, which has lots of datapoints there ?

Consider I have a very simple DataPoint of `String someField` . And values of `someField` can be the same across lots of datapoints. 

So, asking KairosDB for datapoints for time range I will get lots of datapoints with some part of them containing the same values ( this stuff relates to my business domain, not KairosDB ). So, narrowing my question - does query's result contains **timestamp** next to each datapoint so it would be possible to use those timestamps in a future queries ?

**Comment by brianhks** [comment]
The only way to delete is by submitting a query and whatever data that is used to create that query will be deleted.  Kairos doesn't have a single data point delete call.

When running a query the results that come back have a timestamp on each data point so in theory you can narrow the query to just the time of the single data point and then delete it.
