### ISSUE TITLE
Feature Request: Log Queries Longer Than Some Threshold

### ISSUE THREAD

**Issue by ehatch90** [kairosdb/kairosdb#321]
It would be nice if KairosDB would log queries that take too long to return to a separate log file. The threshold for which queries took too long would be configurable. To go a step further, you could configure KairosDB to ingest data about those queries as a separate metric or metrics. That data would hold the query, the source of the query, and how long it took. In a large deployment of KairosDB, this would help a lot with monitoring and would still keep this extra monitoring lightweight.

**Comment by brianhks** [comment]
Fixed as part of 985e7ec798ee2ff7a15f9f75b7b2b2f107756c45
