### ISSUE TITLE
Help with tracking down large queries

### ISSUE THREAD

**Issue by brianhks** [kairosdb/kairosdb#323]
Use Case: When Kairos is used in large organizations where employees are allowed to create graphs/dashboard with tools like graphana, sometimes queries are created that put extreme load on the system and could be optimized.  Identifying these heavy queries is difficult.  Need a way to identify what the query is and where it came from.

Solution: Add two new metrics that are optionally turned on, `kairosdb.log.query.remote_address` and `kairosdb.log.query.json`.  These are string metrics that will contain the remote address and the actual query being made.  Add a configurable ttl for these metrics as they can be large and take up a lot of space.

**Comment by brianhks** [comment]
Added three new properties for controlling this feature:
kairosdb.log.queries.enable=false
kairosdb.log.queries.ttl=86400
kairosdb.log.queries.greater_than=60

You can turn the feature on and off (defaults to off) and set it to log only queries that are longer that a specified amount.  Also configurable is the ttl to apply to the new metrics.

**Comment by joeyhub** [comment]
It's not entirely clear how you turn it off completely.
