### ISSUE TITLE
Escaping colon in tag value

### ISSUE THREAD

**Issue by francisdb** [kairosdb/kairosdb#324]
I looked for a way to escape colons in tag values but have not found anything except this:
https://groups.google.com/d/topic/kairosdb-group/sp4aabCtgAE/discussion

Currently we get:
`tag[resource].value may contain any character except colon ':', and equals '='`

This sounds like a unneeded limitation to me, http has escape codes for these and kairos can always implement it's own escapes?

**Comment by brianhks** [comment]
Yes, it is a sad remnant of a broken initial implementation.  Just need to implement an internal escaping mechanism.

**Comment by francisdb** [comment]
Any strategy on how/where to tackle this? Are there tests covering this?

**Comment by brianhks** [comment]
Fixed in develop.

**Comment by francisdb** [comment]
👍

**Comment by francisdb** [comment]
What is the reason not to escape spaces?

**Comment by brianhks** [comment]
You don't need to escape spaces.  At least not with the rest protocol.  Could add something to let you escape them for telnet.  Telnet uses spaces to delimit the bits of the request.

**Comment by francisdb** [comment]
hmm, don't remember what I was testing that did not work out but can't reproduce it so there is no issue
