### ISSUE TITLE
Support wildcards for query tags filter (globbing)

### ISSUE THREAD

**Issue by hjacobs** [kairosdb/kairosdb#326]
KairosDB currently only allows exact matches when [filtering a query by tags](https://kairosdb.github.io/docs/build/html/restapi/QueryMetrics.html#metric-properties).

It would be useful to allow filtering tags with wildcards (globbing), e.g.:
- a metric "latency" might have a tag "path" for the requested HTTP path and the user wants to get latencies for all paths matching "/foobar/*.json" 
- a metric "cpu" might have a tag "fqdn" and the user wants to get the CPU usage for all hosts with staging in the name ("fqdn" to match "*-staging.*")

These are just two examples. Both could also be solved by storing additional (derived) tags, but this requires prior knowledge about what the user might want to query for.

We already have this [implemented in our fork](https://github.com/zalando-zmon/kairosdb/commit/7a055e627118d75af61237c4eea80b3bf582e396), so I can create a PR :smile:

**Comment by brianhks** [comment]
Pull request please.  Make sure to do it against the develop branch

**Comment by kreeser00** [comment]
Newbie to github.  I need this feature.  How do I help get it into the next release?

**Comment by brianhks** [comment]
My only concern with what was done above is speed.  They force everything to go through a regex match even if it doesn't have glob characters.  One of the problems we face is performance because of lots of row keys.  The filtering process needs to be fast.

I'd also like to add code that lets you say tag != foo.

**Comment by brianhks** [comment]
In 1.3 we added a tag regex prefix.  If you prefix the tag name with this keyword then the tag in the query is treated as a regex.
