### ISSUE TITLE
Data lost if Cassandra is temporary down

### ISSUE THREAD

**Issue by PierreF** [kairosdb/kairosdb#346]
If Cassandra is down, during that downtime any data wrote to KairosDB is lost. There is no retry, no backlog or error sent back to the client.

I would expected that KairosDB retry writing data to Cassandra when it's back online and/or reply an error to client trying to push data to KairosDB.

KairosDB 1.1.2-1 is using the default configuration (only kairosdb.service.datastore is changed to use Cassandra)
Cassandra 3.9 is using default configuration but I've to run "nodetool enablethrift".
I'm writing continuously (every 10 seconds) to KairosDB using the REST API and always get a 204.
To reproduce, I restart the Cassandra node and see that some value are missing.

**Comment by PierreF** [comment]
After few digging in code I think I've found the cause: WriteBuffer that is responsible to send data to Cassandra have a broken retry:

* If [execute](https://github.com/kairosdb/kairosdb/blob/6244bc55d8589b71da6804944bda8ad6f271b01a/src/main/java/org/kairosdb/datastore/cassandra/WriteBuffer.java#L301) fail by raising an exception, we log the error & reduce buffer size
* Few line below, in a while() we retry to call execute (in the hope to re-send mutation that just failed)
* Sadly this does not work, because first call to execute() emptied the mutation list. See [execute code](https://github.com/hector-client/hector/blob/a302e68ca8d91b45d332e8c9afd7d98030b54de1/core/src/main/java/me/prettyprint/cassandra/model/MutatorImpl.java#L277), it empty the list of mutation before trying to run them.

**Comment by brianhks** [comment]
Thank you for finding this issue.  I was quite sure I coded this to handle the situation but I didn't understand what Hector was doing underneath.

The CQL branch I'm working on changes the way the data flows.  I'm writing to disk before acknowledging the data to the client.  This will be much more resilient than holding it in memory.  I'm not sure it is worth trying to fix this at this point or just push ahead with the new code.

**Comment by brianhks** [comment]
I felt like this was a big enough issue that it needed prompt fixing.  I also found that in some cases errors to C* would cause the write thread to die - which I believe some have reported on the message boards.
