### ISSUE TITLE
how to develop kairosdb with idea?

### ISSUE THREAD

**Issue by xsank** [kairosdb/kairosdb#351]
i have read the document of `http://kairosdb.github.io/docs/build/html/kairosdevelopment/IntelliJSetup.html`
but after settings there still have some package problems.
i have used maven and gradle, but how to do about the kairosdb?

**Comment by h7kanna** [comment]
Install IvyIdea plugin

**Comment by brianhks** [comment]
Crap that documentation is a little out of date.  We are using 1.7 java and yes you need to install the ivyidea plugin.  Point it to the ivy.xml and ivysettings.xml and off you go.  I'll leave this issue open to update the documentation.

**Comment by xsank** [comment]
i have install the plugins and configure the ivy settings, and it blocks without information everytime after i click the resolve-dependenct button, that is so sad...

**Comment by carysyd** [comment]
Echo @xsank, I tried to open KairosDB project in IntelliJ 2017 with IvyIdea plugin, but resolve dependency doesn't seem to do anything.

Eclipse works but would be great if you get it working in IntelliJ.

**Comment by brianhks** [comment]
We have checked in a pom.xml that was generated by the build, you can use it to open the project in IntelliJ
