### ISSUE TITLE
Ivy and intellij

### ISSUE THREAD

**Issue by tmalaska** [kairosdb/kairosdb#357]
Having trouble getting this building in intellij.  Any thoughts, also any thoughts on using Maven or Ivy?

**Comment by brianhks** [comment]
You can run the following command that will generate a pom.xml with all the dependencies in it.

Look at the how_to_build.txt for the setup.
>java make project-pom

The code does use Ivy and I've setup the Intellij ivy plugin and it works well.  I just had to point it at the ivy.xml and ivysettings.xml files.

**Comment by h7kanna** [comment]
Intellij IvyIdea plugin is helpful

**Comment by TedBear42** [comment]
Thanks I got it working with Java make.  

Also I'm looking for a small bug or feature to patch.  So you have something I could grab?
