### ISSUE TITLE
Incorrect query results after upgrade from 1.1.0-1 to any recent version

### ISSUE THREAD

**Issue by jgbruosk** [kairosdb/kairosdb#366]
I'm seeing strange query results after replacing Kairos 1.1.0-1 with any recent version (including 1.1.3).  This is the scenario:

1. Install Kairos 1.1.0 and connect it to Cassandra 3.9.
2. Store some metric data.  
3. Query the data using group by tag. 
4. Replace Kairos 1.1.0 with Kairos 1.1.3.
5. Re-run the same query used in number 3.

When the query is run in step 3, the returned data looks like this:

```
{
	"queries": [{
		"sample_size": 2,
		"results": [{
			"name": "Test_110.responseTime",
			"group_by": [{
				"name": "tag",
				"tags": ["locationID"],
				"group": {
					"locationID": "ABC_Location_Here"
				}
			},
			{
				"name": "type",
				"type": "number"
			}],
			"tags": {
				"locationID": ["ABC_Location_Here"]
			},
			"values": [[1488129989685,
			25]]
		},
		{
			"name": "Test_110.responseTime",
			"group_by": [{
				"name": "tag",
				"tags": ["locationID"],
				"group": {
					"locationID": "THE_Location_Somewhere"
				}
			},
			{
				"name": "type",
				"type": "number"
			}],
			"tags": {
				"locationID": ["THE_Location_Somewhere"]
			},
			"values": [[1488129998685,
			60]]
		}]
	}]
}
```

When the same query is run in step 5 (after replacing Kairos 1.1.0 with 1.1.3), the returned data looks like this:

```
{
	"queries": [{
		"sample_size": 2,
		"results": [{
			"name": "Test_110.responseTime",
			"group_by": [{
				"name": "tag",
				"tags": ["locationID"],
				"group": {
					"locationID": ""
				}
			},
			{
				"name": "type",
				"type": "number"
			}],
			"tags": {
				"locationID#": ["ABC_Location_Here#",
				"THE_Location_Somewhere#"]
			},
			"values": [[1488129989685,
			25],
			[1488129998685,
			60]]
		}]
	}]
}
```

So the group by no-longer works, and the tags have # inserted.  If I store brand new data using 1.1.3 and run a similar query, the query result looks the same as step 3 (i.e.group by works correctly, and no # symbols appear).

I've attached the sample data plus the query that was used to replicate this problem.  I've repeated this test multiple times, and see the same behavior each time that I run the test.  Please let me know if you need anything else to help diagnosis this issue.  Thanks!  John.

[SampleMetrics.txt](https://github.com/kairosdb/kairosdb/files/802470/SampleMetrics.txt)
[SampleQuery.txt](https://github.com/kairosdb/kairosdb/files/802471/SampleQuery.txt)

**Comment by jgbruosk** [comment]
Since the editor didn't maintain the formatting of the query output, I'm attaching the files here to make it easier to read.
[Kairos1.1.0_query_response.txt](https://github.com/kairosdb/kairosdb/files/802491/Kairos1.1.0_query_response.txt)
[Kairos1.1.3_query_response.txt](https://github.com/kairosdb/kairosdb/files/802492/Kairos1.1.3_query_response.txt)

**Comment by brianhks** [comment]
So I installed a local C* node running 3.9.  I downloaded off the github site kairos 1.1.0 and loaded the data with that version.  I then tried querying the data with 1.1.0, 1.1.3, develop and my cql branch.  All queries returned the same data with no pound(#).

So what is different about what you have setup and what I'm running?  I'm running on Ubuntu 16.04, java 1.7 sun jdk.

Do you have any plugins loaded?  Any special configuration from the defaults?

**Comment by jgbruosk** [comment]
I'm running on RHEL 7 using IBM JRE 1.8 SR3 FP21.  Here are my configuration changes:

kairosdb.service.datastore=org.kairosdb.datastore.cassandra.CassandraModule
kairosdb.datastore.cassandra.keyspace=metricdb
kairosdb.datastore.cassandra.write_consistency_level=ONE
kairosdb.datastore.cassandra.datapoint_ttl=31622400

Could it possibly be the JRE?  I could try switch to the Oracle 1.8 JRE to see if that makes a difference.

**Comment by brianhks** [comment]
We need to find out if what is in C* is right or not.  Run this query in cqlsh
`>  select * from row_key_index where key = 0x546573745f3131302e726573706f6e736554696d65;`

This should return two rows of data, here is the output from my query:
`0x546573745f3131302e726573706f6e736554696d65 | 0x546573745f3131302e726573706f6e736554696d65000000015a68447000000d6b6169726f735f646f75626c656c6f636174696f6e49443d4142435f4c6f636174696f6e5f486572653a |    0x
0x546573745f3131302e726573706f6e736554696d65 | 0x546573745f3131302e726573706f6e736554696d65000000015a68447000000d6b6169726f735f646f75626c656c6f636174696f6e49443d5448455f4c6f636174696f6e5f536f6d6577686572653a |    0x`

Paste what you get and we can compare.

**Comment by jgbruosk** [comment]
cql query result:

`0x546573745f3131302e726573706f6e736554696d65 |           0x546573745f3131302e726573706f6e736554696d65000000015a68447000000d6b6169726f735f646f75626c656c6f636174696f6e4944233d4142435f4c6f636174696f6e5f48657265233a |    0x
 0x546573745f3131302e726573706f6e736554696d65 | 0x546573745f3131302e726573706f6e736554696d65000000015a68447000000d6b6169726f735f646f75626c656c6f636174696f6e4944233d5448455f4c6f636174696f6e5f536f6d657768657265233a |    0x
`

**Comment by jgbruosk** [comment]
I re-ran the test on several versions of Kairos DB, including a fresh download of 1.1.0.  The query you provided returned the same row data that you listed above.  I took a closer look at what we are running with, and it appears that someone altered our version of Kairos DB 1.1.0; the DataPointsRowKeySerializer class plus a few others don't match what is in "stock" Kairos DB 1.1.0.  I'm going to need to do some internal research to see who altered it and why, as the version we have seems to no-longer be compatible.  
I really appreciate your helping me to investigate this; the cql query you provided was invaluable in pinpointing the problem.  Thank you!  John.
