### ISSUE TITLE
Internal Server Error on easy Query

### ISSUE THREAD

**Issue by muglar** [kairosdb/kairosdb#372]
Internal Server Error on query metric for one hour.  Metric currently has 813468 timestamp/value pairs being logged every second.
![image](https://cloud.githubusercontent.com/assets/17802517/24502273/0ea8b62e-151b-11e7-98bb-c67eded69191.png)

**Comment by brianhks** [comment]
The error looks like you have a replica offline.  Try running >nodetool status 
on one of your C* nodes to see if they are all up.

**Comment by muglar** [comment]
Hi Brian,

So I don't believe this is the issue.

This is the output from nodetool status

[image: Inline image 1]

I have a 3 node cluster with all nodes up.

I've sent the following database parameters

RF =3
Write = 2
Read =1

So even if one node was done it would still be good.

For testing I have many metrics/tag - approx 450.

some come in every second
some every every 30 seconds

This is the number of date/value data-points for three different metrics

[image: Inline image 2]

The second metric will pull data no problem and it only has 28106 points
over 9 days
[image: Inline image 3]

The third metric fails and has 857368 points over the same 9 day period
[image: Inline image 4]

This same problem happened before in testing after x number of days - I
dropped and deleted the keyspace and all metrics were fine again.  Again
after 9 days, the metrics with high datapoints will not pull data, even on
simple requests and fail with the message above.

Any thoughts?

**Comment by brianhks** [comment]
For some reason your inline images didn't make it to the post.
Is there anything in the Kairos or cassandra log files that would hint as to what is going on?
Can you post the data so I can import and try it?

**Comment by muglar** [comment]
Here is the Kairosdb log file for the error.  I could try and post the data
but it is over 14 gigs...

04-03|18:25:17.427 [qtp1634723627-1220] ERROR [MetricsResource.java:563] -
Query failed.
org.kairosdb.core.exception.DatastoreException:
me.prettyprint.hector.api.exceptions.HCassandraInternalException: Cassandra
encountered an internal error processing this request: TApplicationError
type: 0 message:Internal server error: Operation timed out for
scadadata.data_points - received only 0 responses from 1 CL=ONE.
at
org.kairosdb.core.datastore.KairosDatastore$DatastoreQueryImpl.execute(KairosDatastore.java:492)
at
org.kairosdb.core.http.rest.MetricsResource.runQuery(MetricsResource.java:494)
at
org.kairosdb.core.http.rest.MetricsResource.postQuery(MetricsResource.java:456)
at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at
com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
at
com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
at
com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
at
com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
at
com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
at
com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
at
com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
at
com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
at
com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
at
com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
at
com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
at
com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
at
com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
at
com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
at
com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
at
com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
at
com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
at
com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
at
com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
at org.kairosdb.core.http.MonitorFilter.doFilter(MonitorFilter.java:81)
at
com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
at
com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
at org.kairosdb.core.http.LoggingFilter.doFilter(LoggingFilter.java:48)
at
com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
at
com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
at
org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:82)
at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:294)
at
com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
at
com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
at
com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
at
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
at
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
at
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
at
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
at org.eclipse.jetty.server.Server.handle(Server.java:370)
at
org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
at
org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
at
org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
at
org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
at
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
at
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
at
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
at
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
at java.lang.Thread.run(Thread.java:745)
Caused by:
me.prettyprint.hector.api.exceptions.HCassandraInternalException: Cassandra
encountered an internal error processing this request: TApplicationError
type: 0 message:Internal server error: Operation timed out for
scadadata.data_points - received only 0 responses from 1 CL=ONE.
at
me.prettyprint.cassandra.service.ExceptionsTranslatorImpl.translate(ExceptionsTranslatorImpl.java:31)
at
me.prettyprint.cassandra.service.KeyspaceServiceImpl$15.execute(KeyspaceServiceImpl.java:563)
at
me.prettyprint.cassandra.service.KeyspaceServiceImpl$15.execute(KeyspaceServiceImpl.java:549)
at
me.prettyprint.cassandra.service.Operation.executeAndSetResult(Operation.java:104)
at
me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:253)
at
me.prettyprint.cassandra.service.KeyspaceServiceImpl.operateWithFailover(KeyspaceServiceImpl.java:132)
at
me.prettyprint.cassandra.service.KeyspaceServiceImpl.multigetSlice(KeyspaceServiceImpl.java:567)
at
me.prettyprint.cassandra.model.thrift.ThriftMultigetSliceQuery$1.doInKeyspace(ThriftMultigetSliceQuery.java:68)
at
me.prettyprint.cassandra.model.thrift.ThriftMultigetSliceQuery$1.doInKeyspace(ThriftMultigetSliceQuery.java:59)
at
me.prettyprint.cassandra.model.KeyspaceOperationCallback.doInKeyspaceAndMeasure(KeyspaceOperationCallback.java:20)
at
me.prettyprint.cassandra.model.ExecutingKeyspace.doExecute(ExecutingKeyspace.java:101)
at
me.prettyprint.cassandra.model.thrift.ThriftMultigetSliceQuery.execute(ThriftMultigetSliceQuery.java:58)
at
org.kairosdb.datastore.cassandra.QueryRunner.runQuery(QueryRunner.java:112)
at
org.kairosdb.datastore.cassandra.CassandraDatastore.queryWithRowKeys(CassandraDatastore.java:491)
at
org.kairosdb.datastore.cassandra.CassandraDatastore.queryDatabase(CassandraDatastore.java:425)
at
org.kairosdb.core.datastore.KairosDatastore$DatastoreQueryImpl.execute(KairosDatastore.java:486)
... 57 common frames omitted

**Comment by muglar** [comment]
this is the log file from Scylla that is thrown at the same time the query
fails.

Apr  6 22:49:10 scylladb2 collectd[1233]: message repeated 187 times: [
network plugin: parse_part_string: Buffer too small: Output buffer holds 64
bytes, which is too small to hold the received 65 byte string.]
Apr  6 22:49:11 scylladb2 scylla:  [shard 1] storage_proxy - Exception when
communicating with 192.168.3.116: std::bad_alloc
Apr  6 22:49:13 scylladb2 collectd[1233]: network plugin:
parse_part_string: Buffer too small: Output buffer holds 64 bytes, which is
too small to hold the received 65 byte string.
Apr  6 22:50:22 scylladb2 collectd[1233]: message repeated 47 times: [
network plugin: parse_part_string: Buffer too small: Output buffer holds 64
bytes, which is too small to hold the received 65 byte string.]
Apr  6 22:50:25 scylladb2 systemd[1]: Started Session 1137 of user jason.
Apr  6 22:50:25 scylladb2 collectd[1233]: network plugin:
parse_part_string: Buffer too small: Output buffer holds 64 bytes, which is
too small to hold the received 65 byte string.
Apr  6 22:50:43 scylladb2 collectd[1233]: message repeated 13 times: [
network plugin: parse_part_string: Buffer too small: Output buffer holds 64
bytes, which is too small to hold the received 65 byte string.]
Apr  6 22:50:43 scylladb2 systemd[1]: Started Session 1138 of user jason.

**Comment by muglar** [comment]
At this is the new error message - I deleted the database again and started
from scratch...after three days this the output.  The odd part is if you
run a kairosdb.metric_counters for the metric that fail, they are still
storing at the exact rate as expected....just can't get the data out.

Status Code: 500
Status: Internal Server Error
Return Value:
{"errors":["me.prettyprint.hector.api.exceptions.HCassandraInternalException:
Cassandra encountered an internal error processing this request:
TApplicationError type: 0 message:Internal server error: Operation timed
out for scadadata.data_points - received only 2 responses from 1 CL=ONE."]}

**Comment by muglar** [comment]
So based on this error

Apr  6 22:49:11 scylladb2 scylla:  [shard 1] storage_proxy - Exception when
communicating with 192.168.3.116: std::bad_alloc

I restarted the scylla node with this IP and the queries started to work
again.

I believe the kairosdb querying half a million data points and throwing an
error caused this node to semi fail, even though nodetool status was
showing it as up.  Once the large query failed, all the small queries there
after also failed.

Very odd behavior

With a replication factor of 3 on a 3 node cluster this shouldn't happen
should it?

**Comment by brianhks** [comment]
This one has been a while and I think it may have been addressed by #570 and some others.  I'm going to close this.
