### ISSUE TITLE
Rollups: creation of a rollup from web UI doesn't load aggregators if no rollup exist

### ISSUE THREAD

**Issue by lcoulet** [kairosdb/kairosdb#377]
List of aggregator would no show up, a sum(1h)  is applied without possibility to change. A rollup can only be created with sum(1h) then changed after page reload. 

As soon as one rollup is created using the API, the UI works and seems to propose aggregators properly in both branches.

**Comment by jsabin** [comment]
This has been fixed in the latest version of Karios 1.2.1.
