### ISSUE TITLE
Optimizing queries for batch metric/tag queries.

### ISSUE THREAD

**Issue by Yengas** [kairosdb/kairosdb#385]
There seems to be no optimization for the thrift queries, which causes the same queries to `row_key_index` be made multiple times for a single query.

For example a query like this:
```
{
    "start_absolute": 0,
    "metrics": [
        {  "name": "xxx", "tags": { "host": "a" } },
        {  "name": "xxx", "tags": { "host": "a" } },
        {  "name": "xxx", "tags": { "host": "b" } }
    ]
}
```
will cause 3 get_slice queries to be made to the `row_key_index` with `xxx` metric. Wouldn't having an optimization for this speed up batch queries which has same metric name but different tags? The performance boost would be more apparent for data models which results in high number of `row_key_index` counts. Is there anything preventing this?

**Comment by Yengas** [comment]
As far as i see, its the same situation with the kairosdb that released 13 days ago with CQL support.

**Comment by brianhks** [comment]
The solution here is to use the group by option.  Query the metric select the host tags you want and then select to group by host.  Hits the rowkey index once.
