### ISSUE TITLE
KairosDB not cleaning up file handles (kairos_cache)

### ISSUE THREAD

**Issue by benthorner** [kairosdb/kairosdb#386]
We're running KairosDB 1.1.2 and are seeing the kairos_cache directory periodically filling the disk with deleted file handles. Running `lsof | grep tmp` shows it's because of these...

     175112192  185599506 /tmp/kairos_cache/1501789200000/kairos7688537514314791540.json (deleted)

Is there a way for KairosDB to automatically clean up these hanging files without us doing it manually? We currently do this by restarting KairosDB on the offending node.

**Comment by davidflam** [comment]
@benthorner I'm also experiencing this problem. It is intermittent. As far as I know, there is a property called **kairosdb.query_cache.cache_file_cleaner_schedule** in kairosdb.properties that is used to setup a schedule to clean cache files. So I think that should take care of those handles, but for some unknown reason sometimes (frequently when kairosdb is being hammered with queries) it doesn't work.

**Comment by benthorner** [comment]
It does seem to be intermittent. We've got the cleanup schedule set to every 5 minutes, but we're seeing the issue creep up over a longer period than that. I'll take a look to see if it's correlated with queries.

**Comment by benthorner** [comment]
...and yeah, it does seem to be correlated with query spikes. Not sure what's happening with Kairos thought :-|

**Comment by rilott** [comment]
I'm also experiencing this, even with **kairosdb.query_cache.keep_cache_files=false** on v1.1.3

**Comment by brianhks** [comment]
Fixed this in the 1.2 beta 3
