### ISSUE TITLE
Suggest using TWCS for data_points / row_key_index

### ISSUE THREAD

**Issue by benthorner** [kairosdb/kairosdb#387]
We're running KairosDB with a Cassandra backend using STCS (i.e. the defaults), which has caused us some issues. We're currently investigating TWCS and expect this should improve things.

Is TWCS a better default strategy for KairosDB? If so, we could save people some pain by either making it the default or suggesting it in the documentation (or both :-).

**Comment by brianhks** [comment]
I have the commands to do it here:
https://github.com/kairosdb/kairosdb/wiki/Frequently-Asked-Questions

I think you are right, it may be worth changing the defaults in the new release.
