### ISSUE TITLE
Remove dead metrics from string_index

### ISSUE THREAD

**Issue by benthorner** [kairosdb/kairosdb#389]
Currently metrics with no datapoints persist in the namespace forever. Is there an easy way to determine which ones are dead and remove them, without having to query all of the data?

**Comment by benthorner** [comment]
If you disabled string_index_cache, one way to achieve this would be to apply a TTL to the string_index table. When the cache is disabled, each metric name gets 'updated' every time a new data point is added; so dead metrics would not be updated and the TTL would eventually mean they get deleted by Cassandra.

**Comment by benthorner** [comment]
And if the cache was enabled, you could still set the TTL to the data point TTL + cache time. That said, it looks like the current cache policy for string_index doesn't evict old entries.

**Comment by raffraffraff** [comment]
I would love a workaround for this. I have an unfortunate cluster that has 4.3 million _metric names_ due to somebody doing _something very stupid_. Hitting the API for a list of metric names take a while, and results in a 360mb file. Any ideas here, even for a once-off purge?

**Comment by raffraffraff** [comment]
So I did that ^ and it worked right up until I hit the cassandra tombstone limit. So instead of trying to delete millions of metric names I'm just dropping and recreating the string_index table, and then restarting my kairosdb instances. (I tested this on a dev instance and it worked fine)

**Comment by raffraffraff** [comment]
Update on that ^ because I forgot to do it before now: **don't drop/create a table in Cassandra**. It sucks. Even though you're supposed to be able to safely do it on the version I'm using, you can't.

https://stackoverflow.com/questions/27829972/drop-table-or-truncate-table-in-cassandra-which-is-better

It was a mess. Use truncate instead.
