### ISSUE TITLE
String data points are read wrong.

### ISSUE THREAD

**Issue by Yengas** [kairosdb/kairosdb#391]
Querying string data points returns `ByteBuffer#toString` instead of converting the bytes to a UTF8 string. The write operation is done with the `DataOutput#writeUTF` so the read should be done with `DataInput#readUTF` these methods generate bytes in a custom format. So using the String constructor would not work. I think fixing the read instead of the write makes more sense because of backwards compatability? 

The read operation is done wrongly [here](https://github.com/kairosdb/kairosdb/blob/e8612947fc5a49755b429bc3d9e16c591ffa9cc5/src/main/java/org/kairosdb/util/ByteBufferDataInput.java#L118). And you can see the write operation [here](https://github.com/kairosdb/kairosdb/blob/e8612947fc5a49755b429bc3d9e16c591ffa9cc5/src/main/java/org/kairosdb/core/datapoints/StringDataPoint.java#L27).

Example:
![Read Wrong Example](http://i.imgur.com/2V9m5XC.png)

**Comment by brianhks** [comment]
Schema was wrong and didn't match the thrift schema.  I just fixed it and checked it into develop.

**Comment by Yengas** [comment]
Unfortunately, the commit you made solves another issue. This one is caused by [this line](https://github.com/kairosdb/kairosdb/blob/e8612947fc5a49755b429bc3d9e16c591ffa9cc5/src/main/java/org/kairosdb/util/ByteBufferDataInput.java#L118). To test it out, i tried changing the line to:
```
	@Override
	public String readUTF() throws IOException
	{
		return new DataInputStream(new ByteArrayInputStream(m_buffer.array())).readUTF();
	}
```
and it works. I leave making it more performant to you :+1:

**Comment by brianhks** [comment]
Sorry I mistook this for another issue.

**Comment by brianhks** [comment]
I'll create a unit test to make sure this gets fixed and stays fixed.

**Comment by brianhks** [comment]
Now I got it.
