### ISSUE TITLE
add more column into data point

### ISSUE THREAD

**Issue by infordb** [kairosdb/kairosdb#394]
I'd like to store more data into data point table
but now kairosdb supports one value column.
Using custom data types seems to be able to store more information.
https://kairosdb.github.io/docs/build/html/kairosdevelopment/CustomData.html
Is there any problem when using custom data type like performance..?

CREATE TABLE kairosdb.data_points (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH COMPACT STORAGE

**Comment by brianhks** [comment]
I would try to use existing types if possible but there is nothing wrong with creating a custom type (that is why they are there).  Performance seems like it could be just a numeric type.

When I think of a custom type I think of something complex like a speed and a direction that are saved together.  Then I could make a aggregator that acts like a filter and filters out the speed as a regular data point.  Using this aggregator I could get the average velocity over a period of time.

Or I could make an aggregator that calculates the change in velocity based on both speed and direction, etc...
