### ISSUE TITLE
Aggregator for Custom Data Type

### ISSUE THREAD

**Issue by ban4785** [kairosdb/kairosdb#395]
i want Aggregator for Custom Data Type, 
for example
metric : metric1
tag : host=server1
value : VO java class 
public class VO {
	private int col1;
	private int col2;
	private String col3;
}

i want to develop Custom Aggregator for VO class.
language is java.
ex) min, max, avg for col1 or col2.
is there any way to make Aggregator for Custom Data Type?

related issue is  #394

**Comment by brianhks** [comment]
Yes you just need the aggregator to be able to handle the same group type that your custom data point is.  Have a look at the other aggregators, most if not all handle group type number.
