### ISSUE TITLE
error "For input string" when inserting a string containing a big number

### ISSUE THREAD

**Issue by francisdb** [kairosdb/kairosdb#402]
This seems to be caused by #91 where if a string looks like a number it is going to be stored as a number where in case of a big number it will not fit into a long.

Personally I would avoid this kind of type conversion magic or at least return 400 instead of 500 if input is invalid.

This could be fixed in the future by avoiding the use of json for writing and come up with a line protocolo like influxdb has (https://docs.influxdata.com/influxdb/v1.3/write_protocols/line_protocol_tutorial/)
See also #401 where for json there is no global convention for defining precision

```
curl localhost:8080/api/v1/datapoints -d '[{"name":"test","tags":{"a":"b"},"datapoints":[[2, "81040000800000800000800000000000"]]}]' -vvvv
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /api/v1/datapoints HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 89
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 89 out of 89 bytes
< HTTP/1.1 500 Internal Server Error
< Access-Control-Allow-Origin: *
< Pragma: no-cache
< Cache-Control: no-cache
< Expires: 0
< Content-Type: application/json; charset=UTF-8
< Transfer-Encoding: chunked
< Server: Jetty(8.1.16.v20140903)
< 
* Connection #0 to host localhost left intact
{"errors":["For input string: \"81040000800000800000800000000000\""]}
```

Stack trace:
```
10:15:25.051 [qtp832432849-72] ERROR [MetricsResource.java:347] - Failed to add metric.
java.lang.NumberFormatException: For input string: "81040000800000800000800000000000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:592)
	at java.lang.Long.parseLong(Long.java:631)
	at com.google.gson.JsonPrimitive.getAsLong(JsonPrimitive.java:238)
	at org.kairosdb.core.datapoints.LongDataPointFactoryImpl.getDataPoint(LongDataPointFactoryImpl.java:66)
	at org.kairosdb.core.GuiceKairosDataPointFactory.createDataPoint(GuiceKairosDataPointFactory.java:109)
	at org.kairosdb.core.http.rest.json.DataPointsParser.validateAndAddDataPoints(DataPointsParser.java:374)
	at org.kairosdb.core.http.rest.json.DataPointsParser.parse(DataPointsParser.java:94)
	at org.kairosdb.core.http.rest.MetricsResource.add(MetricsResource.java:323)
```

**Comment by brianhks** [comment]
If you specify the type of string in the command it works:
curl vm-server:8080/api/v1/datapoints -d '[{"name":"test","type":"string","tags":{"a":"b"},"datapoints":[[2, "81040000800000800000800000000000"]]}]'

The reason we left number interpretation is that there are applications out there sending data with quotes and we would have broken them if we changed.

I'm not opposed to another protocol.  Json has worked well and works well for custom types which several users have implemented.
