### ISSUE TITLE
Deleting datapoints and reclaiming disk space with Cassandra backend

### ISSUE THREAD

**Issue by Ahuri3** [kairosdb/kairosdb#404]
Hello !

Quick information : I am using KairosDB 1.1.1 with a Cassandra 3.0.9 for the backend.

I have been trying to delete all of my datapoints older than june 2017 via the api  : 

>   curl -X POST  http://kairosserver:8080/api/v1/datapoints/delete  -H 'cache-control: no-cache' -d "{'metrics': [ {'tags': {}, 'name': '${line}', 'aggregators': [ { 'name': 'sum', 'align_sampling': true, 'sampling': {'value': '1', 'unit': 'milliseconds' } } ] } ], 'cache_time': 0, 'start_relative': {'value': '24', 'unit': 'months'},'end_absolute': 1496750000000}"

Using this I have deleted old datapoints for about 33k metrics.
However I have seen no changes in my Cassandra disk usage. I have tried to launch a `nodetool cleanup` and `nodetool repair` but the disk space simply doesn't seem the be reclaimed.

Is there something I am missing about how deleting data-points works ?

Regards,

Leo

**Comment by brianhks** [comment]
Two things have to happen before disk space is reclaimed.  First the gc-grace period hast to expire (this is a C* configuration usually set to 10 days), then a compaction of the data must occur.  What compaction strategy are you using?

**Comment by Ahuri3** [comment]
The gc-grace period has expired by now, we kept it at the 10 days period.

We use `org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy` compaction method and more than a handfull of repairs has been run on the cluster since.

**Comment by brianhks** [comment]
A repair is not a compaction.  You can trigger a major compaction with nodetool but it will compact all your data into a single file.  I much prefer using leveled compaction it handles removing data better.
