### ISSUE TITLE
Encrypting configuration files

### ISSUE THREAD

**Issue by infordb** [kairosdb/kairosdb#405]
I have questions about authentication.
 
1. The user and password are specified in the unencrypted configuration file.
    so  Is there a way to encrypt it?

#To enable http basic authentication uncomment the following lines and specify
#the user name and password for authentication.
kairosdb.jetty.basic_auth.user=admin
kairosdb.jetty.basic_auth.password=admin

2.  Can I use kerberos for authentication

**Comment by brianhks** [comment]
There isn't a way to encrypt the file and have it still readable by Kairos.  What you can do is pass those parameters via the environment if you want.  Just set KAIROSDB_JETTY_BASIC_AUTH_USER and KAIROSDB_JETTY_BASIC_AUTH_PASSWORD as environment variables before starting kairos.  This assumes you have a way of setting those env variables in a secure way.

Kerberos is not supported.

**Comment by infordb** [comment]
Thanks for the answer.
