### ISSUE TITLE
question about batch size 

### ISSUE THREAD

**Issue by infordb** [kairosdb/kairosdb#406]
Hello

I got 1,100,000 write throughput performance on six nodes. (batch size = 100)
I think it is good performance.

Extremely rare, but for business that can not be batch processed, we performed additional tests with a batch size of 1.

throughput dropped to 120,000.  (1,100,000 => 120,000)

Is this result appropriate? Or if batch size is 1, do I need to change the settings ?

**Comment by brianhks** [comment]
Yes performance sucks if you don't batch data.  You need to batch a little bit, good to see that 100 gave you such good performance.

Is that number 1,100,000/sec?  How many Kairos nodes?

**Comment by infordb** [comment]
1,100,000/sec, using 6 nodes.
When batch is not used, throughput is reduced much more than expected.
Is there a way to increase throughput without using batch?

**Comment by brianhks** [comment]
The problem is when you don't batch there are several things that work against you.  For one compression does almost nothing if you are not batching.  Also if you don't batch you have round trip network overhead for every data point.  I suggest you play with the batching until you get a throughput that is satisfactory to you and your use case.

If you are getting 1 million inserts / sec  and the batch is 100 that means it takes about 100ns to insert data, not bad.

**Comment by infordb** [comment]
@brianhks Thanks
another question about kairosdb
 1. Is the write transaction of the kairosdb client guaranteed to write to cassandra or to memory of kairosdb?

 2. Is the meaning of kairosdb.datastore.cassandra.write_delay=1000 to write to cassandra every 1 seconds?

**Comment by brianhks** [comment]
Are you talking about the beta or the 1.1.3 version?

First in 1.1.3 when you got a 200 back it just meant that the data is in memory on the Kairos node.  The write_delay is how often it flushed the buffer.  So data would always have a 1sec delay before getting into C*.

No for the 1.2 beta, things are much cooler.  So depending on which queue processor you use a 200 means different things.  If you are using the MemoryQueueProcessor then a 200 response means the same as it did in 1.1.3, data is in memory on Kairos.  If you are using the FileQueueProcessor a 200 response means it has been persisted on disk using a file backed queue.

In the beta the batch size works like this:  There is a thread who's only job is to pull data from the queue and hand it off to executors to asynchronously send the data to C*.  This thread will look at the queue and if there is not enough data to make a batch it will wait 1/2sec and then flush whatever is there (this keeps the system from thrashing when at low volume).  If there is enough for a batch the thread takes off a batch and farms it out to the executors and immediately goes back for more.  The only thing that will delay processing of a batch is if all the executors are busy then the loading thread will wait.

Does that explain it?

**Comment by infordb** [comment]
@brianhks Thank you for the detailed explanation.
I am currently testing version 1.1.3
Do you mean that data in memory is lost if kairosdb is killed abnormally?
and If  using version 1.2 of  FileQueueProcessor, there is no data loss.

**Comment by brianhks** [comment]
You are exactly right.

**Comment by infordb** [comment]
@brianhks  Thanks a lot
