### ISSUE TITLE
new+old style row index causes result duplication

### ISSUE THREAD

**Issue by zakk4223** [kairosdb/kairosdb#416]
Using 1.2.0beta3

If you have an active kairosdb system and you switch the writer(s) over to beta3 they start writing row key indexes into the new table(s). If you query a metric soon after anything 'recent' returns duplicate data points, and it looks like the duplicate is due to the old and new row key indexes containing entries that cover the same time range.

I can also reproduce this by setting up a completely empty schema, writing metrics into it and then loading an 'old' row key index via sstableloader from a 1.1.3 live system. Once the old row key index is streamed in all queries start returning duplicates.

**Comment by brianhks** [comment]
Oh yes they would, good catch.  This must be fixed.  I need to keep track of what rows I query data from and only do it once in a query.  Should be simple enough.
