### ISSUE TITLE
Is there support for per-user access control in Kairosdb?

### ISSUE THREAD

**Issue by gmuehlenberg** [kairosdb/kairosdb#417]
Hello, I am working for a company which is migrating its machine data to Kairosdb. From the documentation, I could not learn anything about a role model for the Kairosdb users. The company wants to restrict access to metrics for certain database user groups. Is there any support for this use case?

**Comment by brianhks** [comment]
Kairos doesn't have any per user authentication.  If you want to just restrict who can query data that can be done by putting other applications in front of Kairos, like apache or grafana.  If you want to restrict who can access what metrics that is currently not available today.  Can you be more specific about what you are trying to restrict?

**Comment by gmuehlenberg** [comment]
Hello Brian, thank You for Your answer.
Basically, the company wants to run n application servers, one for each customer account, but only one Kairosdb cluster that holds all data. Each account should become an own group, e.g. "companyname" could be one group. The application server should then only be able to access metrics that start with "companyname". To realize this, we could use user groups in the kairos cluster and metric accessibility restrictions.

**Comment by brianhks** [comment]
Having your application prefix every metric with a unique customer id is a great way of segregating the data.  All enforcement would be on your application server.  If you wanted to enforce it at the Kairos level you would need some way of identifying the app server to kairos so it could enforce the prefix.  That seems like overkill when you control the application server.
