### ISSUE TITLE
if the cassandra cluster to add a new node, should i stop the kairosdb and edit the kairosdb.properties file?

### ISSUE THREAD

**Issue by flykarry** [kairosdb/kairosdb#418]
if the cassandra cluster to add a new node, should i stop the kairosdb and edit the kairosdb.properties file?
and whether the kairosdb support hot deployment?

**Comment by brianhks** [comment]
Yes you can add nodes with it up and running.  The soon to be released 1.2 handles new nodes a lot better than the old one.

**Comment by flykarry** [comment]
When I add a new node, do I need to edit the kairosdb.properties files and restart kairosdb？

**Comment by brianhks** [comment]
You will need to update it for 1.1.3 but in 1.2 you only need to specify the seed nodes.
