### ISSUE TITLE
Query the count over 50 million will get the exception of MemoryMonitorException

### ISSUE THREAD

**Issue by flykarry** [kairosdb/kairosdb#421]
3 virtual machine on the other computer
2 core CPU
3GB ram
50G 7200 turn hard disk
one of them running kairos
I have built 2 cassandra cluster at the rest of two machine

**Comment by brianhks** [comment]
If you want to query that much data you will need to give Kairos more memory.

**Comment by flykarry** [comment]
Is there any way for me to query the total count for all data?

**Comment by brianhks** [comment]
One way is to create a rollup of the data - which goes through periods of time summing them up into another metric - then you can query the entire set of rollup data.
