### ISSUE TITLE
how to release all space?

### ISSUE THREAD

**Issue by flykarry** [kairosdb/kairosdb#422]
I have delete all datapoints and metric, But the cassandra have still take up a lot of space. what should I do to release them?

**Comment by brianhks** [comment]
Depends on your compaction strategy but this usually does the trick
http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsCompact.html

You will most likely have to wait 10 days before it will work.  C* keeps data for the GC grace period (which defaults to 10 days) before removing it from disk.
