### ISSUE TITLE
Cassandra timeout during write query at consistency LOCAL_ONE

### ISSUE THREAD

**Issue by flykarry** [kairosdb/kairosdb#423]
[kairosdb.log](https://github.com/kairosdb/kairosdb/files/1676430/kairosdb.log)
I got this Exception and Lost the data I have post to kairosdb

**Comment by brianhks** [comment]
The data should not be lost.  Looks like you are using the file backed queue in Kairos.  If it cannot send it will sit in the queue until it can send it.  It looks like your only C* node went down, if you get it back up then Kaiors will send all the data it received in the file queue.

**Comment by flykarry** [comment]
OK, i got it
