### ISSUE TITLE
Query Tags and Datapoints do not match

### ISSUE THREAD

**Issue by mahdianpeyman** [kairosdb/kairosdb#425]
I have used the same payload for both '/datapoints/query' and '/datapoints/query/tags' APIs, and as it is stated [here](https://kairosdb.github.io/docs/build/html/restapi/QueryMetricTags.html), I expected that both results have the same tag list and values, but it was different.

I would like to get the values of a specific tag in a period of time. It seems like the query tag API is not precise and does not return the correct set of values.

I am using kairosdb_1.1.3-1 release with Cassandra as backend.

**Comment by lcoulet** [comment]
Can you please expand on your problem?

Probable answer:
You may have more tags in '/datapoints/query/tags' API, because it will
find the matching tags in the relevant cassandra rows, which span on a
3-weeks time - that will be longer more than your query time span in almost
any case.
It's a trade-off for performances, otherwise '/datapoints/query/tags' would
be almost as slow as querying the data itself.





2018-01-31 19:14 GMT+01:00 Peyman Mahdian <notifications@github.com>:

**Comment by mahdianpeyman** [comment]
Thanks for fast response. Then, if I understand correctly, it is not "the exact same as the query". Is there a way I can make it more fine tuned. For example, instead of 3-weeks time span, I get 3-days?

**Comment by brianhks** [comment]
lcoulet is correct.  the tag query just queries the row keys and so it may be off.  Can you give more detail into your use case?  There may be other ways of getting what you want.

**Comment by mahdianpeyman** [comment]
I want to have all values of an specific tag in a period of time.

My other approach was to query data with the tag set in group_by and with limit set to 1. Will I get in all the values of the tag in this case? How much lighter it would be rather than running the query with no limit?

**Comment by brianhks** [comment]
Yes doing a group by and using the limit of 1 is a good solution.  It will be heavier than the get tags call because it has to go and get one data point from each row to ensure there is something there, but it only gets one value from each row instead of the entire row of data for the time range.

**Comment by mahdianpeyman** [comment]
Thanks @brianhks, I was going to use group_by with limit 1, but the kairosdb-client does not support the limit yet. That's why I tend to use the tag query. I will add a feature request on kairosdb-client then.
