### ISSUE TITLE
kairosdb.sh start cause NullPointerException

### ISSUE THREAD

**Issue by flykarry** [kairosdb/kairosdb#427]
![image](https://user-images.githubusercontent.com/14309127/35950553-0e95a82e-0cb2-11e8-9580-2d22ed181763.png)

**Comment by Loki-Afro** [comment]
@flykarry what version are you using? ;)

**Comment by flykarry** [comment]
the latest release version 1.2.0-1
and my system is ubuntu 16.04.3

**Comment by brianhks** [comment]
Sorry for not seeing this.  This was fixed back in 1.2.1.
