### ISSUE TITLE
It's doesn't work, if one cassandra node is down

### ISSUE THREAD

**Issue by flykarry** [kairosdb/kairosdb#428]
I have a 3 nodes cassandra cluster. I start the kairosdb and insert some data, and then I stop one of the cassandra node(not the seed node), then I can't insert any data at all.

**Comment by saurabhjinturkar** [comment]
What is the consistency and replication factor from your kairosdb.properties file?

**Comment by brianhks** [comment]
Default replication is 1 and write consistency is quorum.  If you didn't change it then having a node down means 1/3 of your data is offline and Kairos will not be able to write.  You will need to change the replication to 3 and do a repair across the nodes so they have all the data they are supposed to, then you can take one down and it will continue to work.

**Comment by brianhks** [comment]
I just tested a 3 node cluster with replication factor of 3 and read and write consistency level set to ONE.
While loading data I took one node down and verified it was out of the ring.  Kairos continued to load data without any errors.
