### ISSUE TITLE
Kairosdb 1.2.0-1 jars not published to maven central

### ISSUE THREAD

**Issue by ddimensia** [kairosdb/kairosdb#430]
It looks like the latest release hasn't been published to maven central. Could it be published so those that depend on it via maven can migrate to the latest?

**Comment by francisdb** [comment]
Where did you find that version? There is no 1.2.0-1 tag on github.
https://github.com/kairosdb/kairosdb/tags

**Comment by brianhks** [comment]
I published it last night.  I just checked and it still isn't there,but it should be soon.

**Comment by vjkoskela** [comment]
Sorry, I'm looking for this as well; but it does not appear in central. 

http://central.maven.org/maven2/org/kairosdb/kairosdb/
