### ISSUE TITLE
Q: What is the best approach for an migration?

### ISSUE THREAD

**Issue by Loki-Afro** [kairosdb/kairosdb#431]
Hi,

I want to batch insert a lot of data insert kairosdb as fast as possible and ensure that all data has been written at some point. What is the best way to do so?

**Comment by brianhks** [comment]
Just write it in.  Telnet will be faster unless you can chunk it via the http protcol.  Kiaros will internally batch it into C*.  A single Kairos instance can handle sever 100k/sec inserts, depending on your C* cluster size.

**Comment by Loki-Afro** [comment]
Well but when the cluster is overloaded random errors will appear minutes later in kairosdb that indicate that the cluster is overloaded.
The kairosdb cache gets filled and kairosdb will sporadically stop responding.

Just writing data to kairosdb seems like a very naive way

**Comment by brianhks** [comment]
Give me sizes.  How much data?  How many Kairos nodes?  How many C* nodes?

If you are trying to insert 1 billion data points into a single node Kairos/C* cluster then yes you will have problems.  You will need to adjust the client speed to what your cluster can handle.

**Comment by Loki-Afro** [comment]
But adjusting the client speed depends on so many factors.

10 000 - 40 000 chunks a second with parallel reads.

A blocking option to insert data would be very neat
