### ISSUE TITLE
KairosDB 1.2 logs missing date in timestamp

### ISSUE THREAD

**Issue by rdzimmer** [kairosdb/kairosdb#432]
In the KairosDB logs, only the time is included.  This can make debugging difficult if spanning more than one day.  
For example:
`22:39:56.858 [Ingest worker-23] INFO  [QueueProcessor.java:63] - Reducing queue batch size to 250`
Could a date please be included?  Thanks!

**Comment by brianhks** [comment]
Weird, mine has the date.  The format is found in /opt/kairosdb/conf/logging/logback.xml  

Check to make sure your format looks something like this:
%d{MM-dd|HH:mm:ss.SSS} [%thread] %-5level [%file:%line] - %msg%n

**Comment by rdzimmer** [comment]
Weird, for some reason `docker logs <id>` is cutting off the date and just showing the time.  The data is in the logs inside the container.  I'll post back if I figure out why docker logs is doing that.  I confirmed I have that settings, thanks!

**Comment by rdzimmer** [comment]
`docker logs -t` works.

**Comment by brianhks** [comment]
Ah thanks, good to know.  More and more people are running kairos on docker.
