### ISSUE TITLE
Configurable metric name box in UI

### ISSUE THREAD

**Issue by rdzimmer** [kairosdb/kairosdb#433]
I remember seeing in a final 1.2 beta build that the KairosDB UI metric name box was made larger/wider.  Would it be possible to expose that size in the configuration properties file?  Some of my metric names are still a little too large for it.  Or is that size setting already somewhere that could be changed without rebuilding the jar?  Thanks!

**Comment by brianhks** [comment]
The width is on line ~796 in index.html which is under the webroot folder.  Modify to your heart's content it is just a static html page.

**Comment by rdzimmer** [comment]
Thank you!

**Comment by rdzimmer** [comment]
That line expands the tabs div, but the Name* drop-down stayed the same.  I don't really have much html experience.  Seems like it should be straight forward but I haven't been able to figure it out yet.  I did get the refresh button and other things on that line to move around, just not the dropdown.  
If there's an easy change let me know, otherwise it's really not that important.  
![image](https://user-images.githubusercontent.com/17729406/36978588-e2547330-2052-11e8-9b56-9c9468e11b45.png)

**Comment by brianhks** [comment]
Line 81 of style.css will change that.

**Comment by rdzimmer** [comment]
Those two places did it, thanks!
