### ISSUE TITLE
Multicluster Branch: Read Only Cluster Throws Delete Error When it Doesn't Have the Metric

### ISSUE THREAD

**Issue by ehatch90** [kairosdb/kairosdb#434]
This error is found on the multicluster branch.

If you run a metric level delete and only the write cluster has the metric the client will receive a 500 error from the read-only cluster even though the data is deleted in the write cluster. Makes the client think the delete didn't work when it actually did. It also throws an error in the KairosDB logs claiming "Delete failed...org.kairosdb.core.exception.DatastoreException: java.lang.NullPointerException". The Read-only Cassandra cluster should probably fail the delete silently if it doesn't have the metric but the other cluster does.

**Comment by kyleboyle** [comment]
Why would you ask the **read only** cluster to perform the delete in the first place?

**Comment by brianhks** [comment]
Technically they are called read clusters not read only.  So doing a delete across the read cluster is approved.

**Comment by brianhks** [comment]
commit 9efde1f was supposed to be linked to this issue.
