### ISSUE TITLE
How can I make sure the data has been inserted ?

### ISSUE THREAD

**Issue by flykarry** [kairosdb/kairosdb#438]
How can I make sure the data has been inserted ? because there is another opertion based on those datas.
I can't query any data for this code as follow.

![1](https://user-images.githubusercontent.com/14309127/37024212-2a7162c0-2163-11e8-8a02-e70f782bd334.jpg)

**Comment by brianhks** [comment]
Kairos internally batches data before sending to C*.  The data is persisted in kairos before a response is sent back to the client, but it takes an average of .5 sec to get to C*.  If you add a sleep in between your insert and query and the data will be there.  If you are using the kairos h2 backend it does write it immediately.

**Comment by flykarry** [comment]
If there is lots of thread inserting and querying, whether it will work after a sleep of 0.5 second?

**Comment by brianhks** [comment]
The more data you are sending the faster it will get into C*.  As soon as kairos has the minimum batch size it will send the data or after .5 sec whichever is first.

**Comment by brianhks** [comment]
I'm closing this in favor of #441
