### ISSUE TITLE
NullPointerException if logback doesn't have a 'stdout' logback appender

### ISSUE THREAD

**Issue by ddimensia** [kairosdb/kairosdb#440]
If using a command other than 'run' Kairos assumes there is a 'stdout' appender in the logback config.  If no stdout appender exists then Kairos will throw a NPE.  

Kairos should be tolerant of not having a 'stdout' appender and ideally allow the user to determine if they wish to log to console or not when using a command other than 'run'.  I understand why this was done but it almost makes more sense to add a console appender when calling the 'run' command and have no stdout in the default logback.xml than go the other way.

**Comment by brianhks** [comment]
Funny thing is, that code was actually turning off the stdout logger when you use a command other than run.  I changed the code to check for the appender before filtering it.
