### ISSUE TITLE
Some pages to REST API documentation are missing

### ISSUE THREAD

**Issue by umbs** [kairosdb/kairosdb#449]
Metadata: http://kairosdb.github.io/docs/build/html/restapi/Metadata.html
and everything linking from there:
- Add the Value: http://kairosdb.github.io/docs/build/html/restapi/Metadata.html#add-the-value
- Get the Value: http://kairosdb.github.io/docs/build/html/restapi/Metadata.html#get-the-value
- Link Service Keys: http://kairosdb.github.io/docs/build/html/restapi/Metadata.html#list-service-keys
- List Keys: http://kairosdb.github.io/docs/build/html/restapi/Metadata.html#list-keys
- Delete Keys: http://kairosdb.github.io/docs/build/html/restapi/Metadata.html#delete-key

**Comment by brianhks** [comment]
Fixed it, thanks for noticing.
