### ISSUE TITLE
Add trip to DataGapsMarkingAggregator

### ISSUE THREAD

**Issue by brianhks** [kairosdb/kairosdb#453]
As per discussion: https://groups.google.com/forum/#!topic/kairosdb-group/d91JLed3hf8

**Comment by ae3e** [comment]
Hi Brian,

Could you confirm if this feature is still planned to be included in v1.3.0?
I really use it and I would like to be able to migrate to v1.3.0 easily... 😉
Thanks

**Comment by brianhks** [comment]
I merged the pull request.
