### ISSUE TITLE
Roll-Ups queries are not prepared

### ISSUE THREAD

**Issue by tkozybski** [kairosdb/kairosdb#455]
Every time roll-up starts, I'm seeing a lot of un-prepared warnings. This caused performance issues

> 04-14|16:53:17.549 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query INSERT INTO row_key_time_index (metric, table_name, row_time) VALUES (?, 'data_points', ?) USING TTL ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:17.589 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query INSERT INTO row_keys (metric, table_name, row_time, data_type, tags, mtime) VALUES (?, 'data_points', ?, ?, ?, now()) USING TTL ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.073 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query select mtime from service_index WHERE service = ? AND service_key = ? LIMIT 1 is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.829 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:74] - Executing Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:25.831 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT column1 FROM row_key_index WHERE key = ? AND column1 >= ? AND column1 < ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.831 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query SELECT row_time FROM row_key_time_index WHERE metric = ? AND table_name = 'data_points' AND row_time >= ? AND row_time <= ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.857 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT row_time, data_type, tags FROM row_keys WHERE metric = ? AND table_name = 'data_points' AND row_time = ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.899 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 DESC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.918 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Sat Apr 14 15:43:17 CEST 2018 End time: Sat Apr 14 16:53:25 CEST 2018
04-14|16:53:25.984 [cluster1-nio-worker-2] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.984 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.985 [cluster1-nio-worker-2] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.985 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.985 [cluster1-nio-worker-3] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.985 [cluster1-nio-worker-2] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.986 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.986 [cluster1-nio-worker-3] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.986 [cluster1-nio-worker-2] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.986 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.986 [cluster1-nio-worker-3] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.986 [cluster1-nio-worker-2] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.987 [cluster1-nio-worker-3] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.988 [cluster1-nio-worker-3] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.996 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.996 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.997 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.997 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.998 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:25.998 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:26.202 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:95] - Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:26.205 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query INSERT INTO service_index (service, service_key, key, value, mtime) VALUES (?, ?, ?, ?, now()) is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:26.273 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:74] - Executing Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:26.295 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Sat Apr 14 15:43:15 CEST 2018 End time: Sat Apr 14 16:53:26 CEST 2018
04-14|16:53:26.445 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:95] - Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:26.454 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:74] - Executing Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:26.498 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Sat Apr 14 15:45:07 CEST 2018 End time: Sat Apr 14 16:53:26 CEST 2018
04-14|16:53:26.594 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:95] - Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:26.597 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:74] - Executing Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:26.756 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Sat Apr 14 15:43:10 CEST 2018 End time: Sat Apr 14 16:53:26 CEST 2018
04-14|16:53:26.789 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:95] - Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:26.797 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:74] - Executing Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:26.843 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Sat Apr 14 15:43:18 CEST 2018 End time: Sat Apr 14 16:53:26 CEST 2018
04-14|16:53:26.999 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:95] - Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:27.022 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:74] - Executing Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:27.062 [cluster1-nio-worker-3] INFO  [RequestHandler.java:646] - Query INSERT INTO string_index (key, column1, value) VALUES (?, ?, 0x00) is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.084 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Sat Apr 14 15:43:18 CEST 2018 End time: Sat Apr 14 16:53:27 CEST 2018
04-14|16:53:27.224 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:95] - Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:27.226 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:74] - Executing Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:27.245 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Sat Apr 14 15:54:27 CEST 2018 End time: Sat Apr 14 16:53:27 CEST 2018
04-14|16:53:27.265 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:95] - Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:27.284 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.288 [cluster1-nio-worker-2] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.288 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.288 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.288 [cluster1-nio-worker-2] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.288 [cluster1-nio-worker-3] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.289 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.289 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.290 [cluster1-nio-worker-2] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.290 [cluster1-nio-worker-3] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.290 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.291 [cluster1-nio-worker-2] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.292 [cluster1-nio-worker-3] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.292 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.293 [cluster1-nio-worker-3] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.293 [cluster1-nio-worker-1] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.305 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT column1, value FROM data_points WHERE key = ? AND column1 >= ? AND column1 < ? ORDER BY column1 ASC LIMIT ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:53:27.370 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Sat Apr 14 16:27:45 CEST 2018 End time: Sat Apr 14 16:53:27 CEST 2018
04-14|16:53:27.405 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:106] - Datapoint exists for time range, advancing forward for Rollup ROLLUP
04-14|16:53:27.427 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:74] - Executing Rollup Task: XXX's for Rollup ROLLUP
04-14|16:53:27.614 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Sat Apr 14 15:52:05 CEST 2018 End time: Sat Apr 14 16:53:27 CEST 2018
04-14|16:53:27.728 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:95] - Rollup Task: XXX's for Rollup ROLLUP
04-14|16:54:04.608 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT key FROM service_index WHERE service = ? AND service_key = ? ORDER BY key ASC is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
04-14|16:54:04.625 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query SELECT value, WRITETIME(value) FROM service_index WHERE service = ? AND service_key = ? AND key = ? is not prepared on /IP:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems

**Comment by brianhks** [comment]
I don't see how this is possible.  All CQL queries are prepared.  What is the setup in which you are running this?  Number of C* nodes and what versions?

**Comment by tkozybski** [comment]
This is a testing setup. One KairosDB node version 1.2.1 and one ScyllaDB version 2.1.1

**Comment by jsabin** [comment]
Must be a bug in SyllaDB. This does not happen with Cassandra.

**Comment by jason-es** [comment]
@tkozybski any workarounds identified? I am facing the same issue
