### ISSUE TITLE
Roll-Ups not working correctly after long-downtime

### ISSUE THREAD

**Issue by tkozybski** [kairosdb/kairosdb#457]
Config:
KairosDB 1.2.1, ScyllaDB 2.1.1

After several (~5) hours of no datapoints being added, my rollup queries stopped working. Datapoints are there because Grafana shows proper values, but roll-up finds no datapoints. I'm doing rollup every 1 hour with aggregation relative to 1 hour. I'm attaching the logs. As you can see it tries endlessly to summarize 4 hours, but there's no data so it fails.

> 04-18|10:03:15.031 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:74] - Executing Rollup Task: TestRollup's for Rollup  kairosdb.test_rollup
> 04-18|10:03:15.167 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Wed Apr 18 00:03:53 CEST 2018 End time: Wed Apr 18 04:03:53 CEST 2018
> 04-18|10:03:15.455 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:95] - Rollup Task: TestRollup's for Rollup kairosdb.test_rollup data point count of 0
> 04-18|10:03:15.616 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Wed Apr 18 00:03:59 CEST 2018 End time: Wed Apr 18 04:03:59 CEST 2018
> 04-18|10:03:15.787 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:106] - Datapoint exists for time range, advancing forward for Rollup Task: TestRollup's for Rollup kairosdb.test_rollup data point count of 0
> 
> 04-18|11:03:15.032 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:74] - Executing Rollup Task: TestRollup's for Rollup  kairosdb.test_rollup
> 04-18|11:03:15.063 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Wed Apr 18 00:03:59 CEST 2018 End time: Wed Apr 18 04:03:59 CEST 2018
> 04-18|11:03:15.152 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:95] - Rollup Task: TestRollup's for Rollup kairosdb.test_rollup data point count of 0
> 04-18|11:03:15.262 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Wed Apr 18 00:03:59 CEST 2018 End time: Wed Apr 18 04:03:59 CEST 2018
> 04-18|11:03:15.307 [QuartzScheduler_Worker-1] INFO  [RollUpJob.java:106] - Datapoint exists for time range, advancing forward for Rollup Task: TestRollup's for Rollup kairosdb.test_rollup data point count of 0
> 
> 04-18|12:03:15.031 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:74] - Executing Rollup Task: TestRollup's for Rollup  kairosdb.test_rollup
> 04-18|12:03:15.162 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Wed Apr 18 00:03:59 CEST 2018 End time: Wed Apr 18 04:03:59 CEST 2018
> 04-18|12:03:15.546 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:95] - Rollup Task: TestRollup's for Rollup kairosdb.test_rollup data point count of 0
> 04-18|12:03:15.840 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:160] - Execute Rollup: Start time: Wed Apr 18 00:04:01 CEST 2018 End time: Wed Apr 18 04:04:01 CEST 2018
> 04-18|12:03:16.086 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:106] - Datapoint exists for time range, advancing forward for Rollup Task: TestRollup's for Rollup kairosdb.test_rollup data point count of 0

**Comment by jsabin** [comment]
I have identified the problem and am working on a fix.

**Comment by jsabin** [comment]
I have reworked roll-ups and have resolved this issue. The code has been checked into the develop branch for commit #401143ca309ac5d8a0db3152379fb268c87dc98e.
