### ISSUE TITLE
Memory leak in queueMemoryQueueProcessor

### ISSUE THREAD

**Issue by rdzimmer** [kairosdb/kairosdb#458]
I'm running kairosdb-1.2.0-1.  I've been running well with it since it was released.  I recently switched to a different set of metrics coming from new data collectors.  Unfortunately, every ~2 hours my KairosDB is heap dumping.  Based on my load I don't expect it to be and think it could be a leak?  With the old metrics set I was doing ~1M metrics per minute.  With these new tests I was doing <200K/minute.  I don't see any errors in the logs (other than the heap dumps).  

The heap dump shows:
![kairosdb_heap_dump](https://user-images.githubusercontent.com/17729406/38998397-799b2a08-43bd-11e8-868f-a06b833bd8f3.PNG)

Here are the write_batch_size.sum for data_points (blue), row_keys (red), string_index (green).  I have KAIROSDB_ROW_KEY_CACHE_SIZE 1,500,000 and KAIROSDB_STRING_CACHE_SIZE 500,000 with a 2GB Xmx.  In my previous testing, ~2M cache items took up ~1.5GB.  And based on the heap dump and key/index write I don't believe that was the problem.
![batch sizes](https://user-images.githubusercontent.com/17729406/38998420-87558922-43bd-11e8-8caa-088ffe00f421.PNG)

Here is the jvm.free_memory.  Around 09:00 is when I stopped things and at ~10:00 switched to the old data collectors (which so far have not caused memory problems).  
![image](https://user-images.githubusercontent.com/17729406/39000650-86f81a4e-43c2-11e8-8af7-74a048a57294.png)

I've checked kairosdb.queue.memory_queue.size and it's normally tiny, at most 1500 occasionally (8000 temporarily after the crash and restart).  I'm using the org.kairosdb.core.queue.MemoryQueueProcessor, not the new file system.  Any KairosDB logging that might help?  Perhaps there's a new metric that's getting stuck in the queue?

**Comment by rdzimmer** [comment]
The memory has stabilized after switch to the other/old data collectors, even though they're sending more.  
I'll try to narrow down if there's a specific new metric being sent causing the memory problems.  
![image](https://user-images.githubusercontent.com/17729406/39007264-6e703dba-43d3-11e8-9e86-b545fd71b891.png)

**Comment by rdzimmer** [comment]
I've identified a new metric causing the trouble.  I'll look into what it is doing more.

**Comment by brianhks** [comment]
Yes please keep us posted, I'm not aware of anything that could cause a leak.  Maybe the client is sending an extremely large batch of metrics to kairos?

**Comment by rdzimmer** [comment]
@brianhks From the heapdump, do you recognize that hashmap?  Any ideas from that where the memory storage is building up?  I know it's always hit or miss if those things show enough info for developers to know exactly.  It's okay if not, just looking for hints as I work with the data collectors dev team on what their new metrics/tags look like.

**Comment by rdzimmer** [comment]
Someone had a typo and was putting a TIMESTAMP(!!!) into the new tags.

**Comment by rdzimmer** [comment]
@brianhks Could we add some logging to show the size of the two caches?  Or even better than putting it in the logs would be making it a kairosdb metric like memory or batches (I believe in here? kairosdb.service.reporter=org.kairosdb.core.reporting.MetricReportingModule).  If that sounds good I can open an issue for that since I don't see one already.

**Comment by brianhks** [comment]
not ideal but an current option to look at.  The purpose of the cache is to minimize writes to the row key index.  You can look at the metrics for writes to the index as compared to the data points table and if the index jumps up it is an indicator that the cache isn't doing its job for whatever reason.
