### ISSUE TITLE
Restart KairosDB when stopped abnormally without manual intervention

### ISSUE THREAD

**Issue by chrispetsos** [kairosdb/kairosdb#459]
Currently, if KairosDB is terminated unexpectedly (e.g. crashes), its pid file remains at `/var/run/kairosdb.pid`, so if one tries to restart the service with something like `sudo service kairosdb start` you get a `Service already running` message and service won't start.
So, to reproduce this:
1) `sudo service kairosdb start`
2) `kill -9 <kairosdb_pid>`
3) `sudo service kairosdb start`
`Service already running`

Would it be possible to enhance the startup scripts somehow so that it takes care of such orphaned pid files? Or would you have anything else to suggest apart from deleting the `/var/run/kairosdb.pid` file manually?

**Comment by brianhks** [comment]
I agree it should be possible to check for the pid to make sure it is really running.

**Comment by brianhks** [comment]
I changed the startup script to use systemctl which handles this situation much better.  d822637431ea07d0edd4a8c73afecff97965ad34
