### ISSUE TITLE
How can I use limit in java client? 

### ISSUE THREAD

**Issue by flykarry** [kairosdb/kairosdb#460]

**Comment by wuwulala** [comment]
QueryMetric
![image](https://user-images.githubusercontent.com/10803868/41964388-695d6d5e-7a2c-11e8-9ad3-9fe0b8880857.png)

**Comment by jsabin** [comment]
QueryBuilder queryBuilder = QueryBuilder.getInstance();
		queryBuilder.setStart(2, TimeUnit.HOURS)
				.addMetric("testMetric").setLimit(1);
