### ISSUE TITLE
How to update the value of a time point ？

### ISSUE THREAD

**Issue by flykarry** [kairosdb/kairosdb#461]
example
I have an point at 2018-05-08 10:00:00.000, value = 30
I want to update the time point value with 40, how to do this ?

**Comment by flykarry** [comment]
I wrote two type of data one is long and another is String, the second has didn't overwrite the first one.

**Comment by wuwulala** [comment]
The kairosdb primary key contains the type parameter. If the first time is 10, and does not specify the type, it will automatically help you store it as a numeric type. After second modifications to test, it is considered to be string type, and these two will be stored.
![image](https://user-images.githubusercontent.com/10803868/41964284-29076eb2-7a2c-11e8-8a94-00fa3b921531.png)

**Comment by brianhks** [comment]
If you send the value with the same metric name, tags, timestamp and type of data (ie. float, integer, string) it will overwrite the previous value.
