### ISSUE TITLE
I always got an exception about WriteTimeoutException when I write too fast.

### ISSUE THREAD

**Issue by flykarry** [kairosdb/kairosdb#470]
![_20180525083912](https://user-images.githubusercontent.com/14309127/40520232-27fe872a-5ff7-11e8-950f-25142fe9df5f.png)
How to deal with it ? 
My cluster is 3 virtual machine, one of them is kairosdb, and the last is cassandra cluster

**Comment by brianhks** [comment]
Looks like you are using 1.2 it lakes retry logic for the C* driver.  The timeout is an indication that your cluster is too small for the amount of data you are trying to send.  Retry is added to the 1.3 code but I may make a patch fix for the 1.2 code to get it in.

**Comment by jsabin** [comment]
Fixed in 1.2.2.
