### ISSUE TITLE
Metric creation after cassandra connection recovery.

### ISSUE THREAD

**Issue by xelex** [kairosdb/kairosdb#471]
Configuration:

- KairosDB 1.2.1
- Cassandra (latest, from docker)
- 100% reproducible
- Default config + In-memory queue

How to reproduce:

1. Bring Cassandra and KairosDB up and running.
2. Stop Cassandra, KairosDB is still running.
3. Push some data to the new series A.
4. Pushes are successfull, result is 204.
5. Brind Cassandra back.
6. Kairos reconnects and commits the "pending" batch.

Expected:

- New metric A created.
- Data is present in DB

Actual results:

- A not created.
- I can not query data from A.
- Metric name cache is dirty after this test and I can not recreate the metric A anymore.

**Comment by xelex** [comment]
The problem is here: BatchHandler.java, line 140.

We add a new metric name to the cache on the batch load, not on the batch sucessfull commit.

**Comment by brianhks** [comment]
Excellent, thanks for the pull request.  I will get it in as soon as possible.
