### ISSUE TITLE
How to use Cassandra with KairosDB on Mac and remove the default H2

### ISSUE THREAD

**Issue by tushartripathi1998** [kairosdb/kairosdb#473]

**Comment by raffraffraff** [comment]
This doesn't look like a valid issue or a bug. It seems to me that you're asking for step by step instructions. If you just want to 'kick the tires', so why not search the docker hub? This
[This image](https://hub.docker.com/r/wangdrew/kairosdb/) looks popular. The instructions in its [GitHub project](https://github.com/wangdrew/docker-kairosdb) are easy to follow. So try this:
`
docker run -d --name cassandra -e CASSANDRA_START_RPC=true cassandra:2.2
`
Give that a minute to properly start up, and then start KairosDB:
`
docker run -d --name kairosdb --link cassandra -e "CASSANDRA_HOST_LIST=cassandra:9160" -p 8083:8083 -p 4242:4242 wangdrew/kairosdb
`
You can start sending metrics to localhost:4242 using telegraf's opentsdb output. KairosDB web UI is available on localhost:8083.
