### ISSUE TITLE
Possible race condition on ThreadReporter

### ISSUE THREAD

**Issue by lcoulet** [kairosdb/kairosdb#479]
ThreadReporter is used in several places to report KairosDB  metrics.

It looks to me that since it's using static methods instead of a builder pattern that this class is subject to race conditions between different modules.
For instance different module start adding/clearing tags and adding datapoints resulting in undefine behaviours.

I suggest transforming the static ThreadReporter builder-like pattern, to a genuine builder (keeping a static factory method).

**Comment by jsabin** [comment]
This is using ThreadLocal which is stored on the local thread. There should not be a race condition.
