### ISSUE TITLE
text can not find

### ISSUE THREAD

**Issue by lgr123** [kairosdb/kairosdb#483]
cannot find kairosdb.properties text under the conf
where is it？

**Comment by jsabin** [comment]
The source does not have a conf directory.  In the source tree the properties file is found in src/main/resources/kairosdb.properties.  Installers for KairosDB can be [found here](https://github.com/kairosdb/kairosdb/releases). These will install to /opt/kairosdb and will put kairosdb.properties in /opt/kairosdb/conf.
