### ISSUE TITLE
When kairosdb.query_cache.cache_dir is set, /tmp/kairos_cache is still created

### ISSUE THREAD

**Issue by philrz** [kairosdb/kairosdb#49]
I'm running KairosDB 0.9.3. I've noticed that in kairosdb.properties, if I uncomment the line that sets "kairosdb.query_cache.cache_dir" and point it to a location, I now get cache directories created in my specified target _and_ still one in /tmp/kairos_cache.

I've looked at the source, but alas, my Java skills are not great and the role of the @Inject code is opaque to me, so I'm not quite sure of the right way to fix. If someone could point me in the right direction, I'd gladly test out the fix and submit back to the project. Thanks.

**Comment by brianhks** [comment]
This was fixed when post construct init methods were added to injected objects in Kairos.
