### ISSUE TITLE
fix gzip encoding headers

### ISSUE THREAD

**Issue by sspieker** [kairosdb/kairosdb#493]
I just stumbled upon the way KairosDB handles zipped content. Looking at [Line 268](https://github.com/kairosdb/kairosdb/blob/247ce74e4b6ae28d9b229fdc33a4096d90f6eb49/src/main/java/org/kairosdb/core/http/rest/MetricsResource.java#L268), that implementation is not quite "clean": `@Consumes("application/gzip")`

According to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-3.1.2.2) the following header should be used: `Content-Encoding: gzip`

Could you fix that, please?
Btw, I think the KairosDB Client needs to be fixed, too: [Line 67](https://github.com/kairosdb/kairosdb-client/blob/3b44aa508c6b2ca722f40565fef3316f178bf8ea/src/main/java/org/kairosdb/client/HttpClient.java#L67)
Maybe this could be synchronized...

**Comment by jsabin** [comment]
Fixed in 8fca7e93c8336ab85109437a9d2d2a0d38d0894c in KairosDB and in the client 46095eb937a38964401fce556bb5ff683f55b359.
