### ISSUE TITLE
Kairosdb doesn't overwrite the data points.

### ISSUE THREAD

**Issue by Abouzeid** [kairosdb/kairosdb#496]
The query response: 
    "values": [                       
                        [
                            1539600000000,
                            3.84500026702881
                        ],
                        [
                            1539600000000,
                            25
                        ]           
                    ]
How do I force KairosDb to overwrite datapoints with the same timestamp?
The goal is not to keep both values for a TS and only return one.

Thank you in advance.

**Comment by lcoulet** [comment]
Hello, you have different data types: long and double. Therefore they belong to two different series. You need to use a delete query first then you can reinsert.
If you wish to always post floating point values, you can push with specifying the type in the rest API.

**Comment by Abouzeid** [comment]
Hi @lcoulet ,

Got it.
I didn't pay attention to the type before.

Thank you so much.
