### ISSUE TITLE
Rollups not being reassigned on restart

### ISSUE THREAD

**Issue by 6palace** [kairosdb/kairosdb#507]
We're running kairos through container orchestration, and are encountering an issue with rollup assignment after restart:

1. create multiple rollups
1. perform restart of kairos containers, which creates new host ids
1. on restart, only some of the rollups are re-assigned to the new hosts. When getting the rollup status, the un-assigned rollups retain the pre-restart host ids
1. although active hosts in the casssandra store are up to date (ie old hosts are getting deleted from `_Hosts:Active`), AssignmentManager's scheduled task never re-assigns the rollups to the active hosts

Not sure if this is a documented problem somewhere, or if there is a workaround. Currently we are deleting and recreating the rollups every time we redeploy.

Version running: 1.2.1

**Comment by jsabin** [comment]
Sounds like there is a bug that needs to be fixed. However, my suggestion is to set the machine name as the pod name so it does not change. If not, the hosts tag in all your metrics will grow to be unreasonably large.

I will look into reproducing the problem and fixing the bug.

**Comment by jsabin** [comment]
Another option to consider as a temporary fix is to set the name of the kairos host in the config file. If you set the property kairosdb.hostname, this will be used as the name rather than Kairos getting the name from the os.

**Comment by jsabin** [comment]
fixed in commit 640102ca58caee375b13746262fb6fce895cfb6a.

**Comment by 6palace** [comment]
Thanks!
