### ISSUE TITLE
Delete one tag but whole metric is deleted

### ISSUE THREAD

**Issue by hinstw** [kairosdb/kairosdb#509]
# Spontaneous deletion
{"version": "KairosDB 1.2.0-1.20180201074909"}
It appears that sometimes when a request to delete some values is sent to KairosDB, a significantly larger number of values can be deleted.
I the dataBase there is a metric where tags are used to separate values one from another. For example
id=1, id=2, id=3 and so on
Inside each id there are many values

### Request all
1. go to KairosDB web UI
2. enter metric name
3. group by tag=id
4. aggregators = average one day, to prevent output overflow

### Request single id
1. go to KairosDB web UI on a new page
2. enter same metric name
3. Tags: id=2

### Reproduction
1. Execute request-all: observe timeCourses (about 10..20 lines in my case)
2. Execute request-single-id: observe one timeCourse
3. Click "Delete Data". KairosDB WebUI asks for confirmation; then asks if graph should be refreshed. Click Yes, refresh. The graph is now empty
5. Go to page with request-all. Click "Graph". Now the graph is empty.  However it should not be empty because only one id was deleted

### Notes about reproduction
1. It is also possible to verify the presence of bug by looking at the Sample Size field in KairosDB WebUI. Suppose I get 10k items from request-all. Then I get 1k items from request-single-id. Then I click Delete. 10k - 1k equals 9k. However, the Sample Size I observed was 0.
2. I reproduced this bug multiple times. At first I thought that something is wrong with my code, but later I reproduced the bug in KairosDB webUI
3. I reproduced this bug on KairosDB version=1.2.0-1.20180201074909 on a system running Linux & ScyllaDB. I later tried to reproduce the bug on my laptop running Windows & DataStax, however I could not reproduce it. On Windows I observed normal deletion: only one id was deleted from db. The version of KairosDB i have on laptop is 1.2.1-1.20180331130457
4. I also reproduced this bug on a much larger metric, which had about 1000 ids and about 300M values, and I also observed spontaneous delition
5. Sometimes, not all values are deleted, but only some values are deleted, for example about 50% of the values in the metric are deleted while other values remain intact

This bug seems dangerous because it might cause undesired data deletion. It caused undesired data deletion for me on a test system. At this moment it is not clear to me why or how the spontaneous deletion happens.

Thanks

**Comment by hinstw** [comment]
I later learned that this bug is not reproduced on 1.2.1 even on Linux system so I guess it is fixed in 1.2.1

**Comment by brianhks** [comment]
Excellent, good to hear.
