### ISSUE TITLE
1.3 beta multiple regex patterns on same tag bug

### ISSUE THREAD

**Issue by DanoOM** [kairosdb/kairosdb#515]
I just noticed that if I have tag, with 2 regex expressions (Observed from grafana), the second regex pattern appears to be ignored.
The JSON IN QUESTION:
`{"metrics":[{"name":["kafka.ack.poll.ts.event"],"aggregators":[{"name":"div","divisor":"20"}],"tags":{"host":["regex:.*wdc-tst.*","regex:.*vdc-tst.*"]},"group_by":[{"name":"tag","tags":["host"]}]}],"cache_time":0,"start_relative":{"value":"15","unit":"minutes"}}
`

**Comment by brianhks** [comment]
The code only handles one regex per tag.  This is because what you want can be done by changing up the the regex a bit: ".*(wdc|vdc)-tst.*"

Essentially what you want is to match one regex or the other so you can put that right in a single regex.
