### ISSUE TITLE
Create Roll-up Task BUG

### ISSUE THREAD

**Issue by boka9174120** [kairosdb/kairosdb#519]
I created one roll-up,but I can't findit start-time.Only .addAggregator(AggregatorFactory.createSumAggregator(2, TimeUnit.HOURS));
I can only find it is start from before time.
so,that is a start-time or how often is it called.
II hope you can reply me as soon as possible.
thank you .

**Comment by jsabin** [comment]
Sorry for the long delay in my response. 

The roll-up is a new metric with a different name (based on what you called it). The roll-up is executed based on the execution schedule (ie. hourly, daily, weekly, etc). Make sure that your execution time is greater that your last sampling aggregator.
