### ISSUE TITLE
Cassandra/Scylla compression

### ISSUE THREAD

**Issue by mamoit** [kairosdb/kairosdb#528]
A nice to have would be kairos cassandra module exposing the ability to create/alter the tables in order to compress the sstables.
Right now I'm doing this manually after the namespace and tables creation.

**Comment by brianhks** [comment]
Can you post an example of what you are doing?

**Comment by mamoit** [comment]
You stated [here](https://github.com/kairosdb/kairosdb/issues/23#issuecomment-66723592) that the best compaction strategy would be `DateTieredCompationStrategy`.

So I'm trying out that compaction strategy with compression too:
```
ALTER TABLE data_points WITH compression = { 'sstable_compression': 'LZ4Compressor' } AND compaction = { 'class': 'DateTieredCompactionStrategy' };
```
I got between 55% and 70% disk space usage savings.

**Comment by mamoit** [comment]
:heart:
