### ISSUE TITLE
Rollups not working

### ISSUE THREAD

**Issue by biswaKL** [kairosdb/kairosdb#530]
Hi, I have set multiple rollups, they are getting triggered as well, but i am not getting new metrics.
When i checked the log i am getting **" data point count of 0"** 

But if i trigger the query manually i am getting data, and if i add **Save As** aggregation, its getting saved as well.

**Comment by jsabin** [comment]
I have reworked roll-ups which should have solved this problem. Checked into the develop branch. Commit #401143ca309ac5d8a0db3152379fb268c87dc98e.

**Comment by biswaKL** [comment]
Thanks a lot.. its a great help...
