### ISSUE TITLE
why row_key_index is empty 

### ISSUE THREAD

**Issue by ziflyingyo** [kairosdb/kairosdb#532]
I run kairosdb with datasource scylladb, and insert many data into it, I can query the data from kairosdb, but where I exec in cqlsh:
cqlsh> select * from  kairosdb.row_key_index ;

 key | column1 | value
-----+---------+-------

(0 rows)

why the row_key_index  is empty?

**Comment by brianhks** [comment]
row_key_index is an old table.  It is kept around for backward compatibility in the code.  Now data is stored in a combination of row_keys and row_key_time_index
