### ISSUE TITLE
Trying to resolve straight answers on performance...

### ISSUE THREAD

**Issue by joeyhub** [kairosdb/kairosdb#535]
I think in any situation the user must be willing to do the science and confirm their ideas about performance, that is write little scripts to test that. Someone has already asked for something like that or if anyone else has done it.

While the user has some responsibility, the tool must also have some performance intentions otherwise it would be a bit pointless. I'd imagine there must be some tests somewhere.

That aside the first performance document that comes up for a search isn't helpful even when it comes to covering basic usage. It's quite cryptic and potentially counter productive. It doesn't really explain things well and in some areas it really makes no sense at all,

There are cases where it seems to jump into low level aspect where as it might be better to just say what kind of schema it establishes in for example cassandra allowing users to look at cassandra specs for specifics.

### Data:

* number of unique metric names
* number of unique tag names
* number of unique tag values
* number of unique times
* overlap and other complexities

### Access patterns:

Are tags:

* and
* or

I assume or but the documentation is a little tight lipped about it:

> It is possible to filter the data returned by specifying a tag. The data returned will only contain data points associated with the specified tag. Filtering is done using the “tags” property.

It talks a little too much in the singular about a plural, however we find out they're ors here:

> Tags narrow down the search. Only metrics that include the tag and matches one of the values are returned. Tags is optional.

This should probably be only the metrics that match as least one of the tag key value combinations will be returned. This I'm still left unsure. An array of values obviously would be an or but what about two key names? Though it would be a bit dysfunctional for those to be and. Most people would want `(a = 1 AND b = 2) OR (a = 2 AND b = 1)` not `(a = 1 OR a = 2) AND (b = 2 OR b = 1)`? Just `a IN (1, 2) OR b IN(1, 2)` would make more sense. Though the example with customer as well as hosts would imply they're AND between multiple key names. Will people flip key and value to get AND to work? Are people not asking the questions I am getting incorrect metrics without knowing (often it's worse as excess tends to appear more valid than deficit or vice versa in most cases)?

For when people want and, the only solution to that is to DIY, that is:

```
tags = {hotel: 123, room: 321, person: 666};
keys = Object.keys(tags).sort();
values = keys.map(key => tags[key]);
tags[JSON.stringify(keys)] = JSON.stringify(values);
query = JSON.stringify({metrics: [{tags}]});
```

This would allow to search for "for how long during this period did person ? stay in room ? of the hotel ?".

Concerns like this depend on actual usage and access. In this case it's quite common to want to want:

* How many stays (a day) were there for the hotel ? during the period ?.
* During the period ?, how many stays were there in room ? of hotel ?.

Many people might do something simpler than the above and just have `room: [hotel, room].join(delim)`. It's quite common to have a usage pattern where your lookup tends to consist of a list of possible ands (like a and b and c) but may only want out of those either a, a and b or a and b or c but not just b or a and c.

# Metric versus tags: **Fight**

Starting out you must define both a metric and a tag for a datapoint. A problem here is that all basic use cases involving and/or can be both managed with metrics and tags. Whenever starting out with a single first use case it's very much neither here not there which works best to use more of. It's not until you start piling on the use cases that things start to become apparent.

You might say well surely it's obvious when your queries are ten times bigger with using metrics (unless it turns out it secretly takes an array for multiple items like tag values do) or based on it spamming rows but it's not immediately obvious if that will be the case and the line between when to use metrics or tags is blurred especially where performance is concerned.

Yes, I have seen people using metrics in place of tags. It happens, probably quite often. Then the moment you need to add another access pattern it quickly becomes insufficient. For tags you can easily add them or stop populating them with little impact but metrics has a lot of impact. This should be considered in any design, what will happen with tags versus metrics when different access patterns are needed.

My view on the matter is keep metrics quite shallow and use tags by default. By shallow it's usually as in whichever first set of ands you'll always want. As in `(application = hotels AND type = stays) AND (a = 1 OR a = 2 AND b = 1)` then for that initial static part in brackets that might make a good metric but for the part that's very dynamic based on use case then that should be tags.

Another rule of thumb (obvious one) should be to use metrics for any data that's always isolated, as in never included together with a query, should also use a separate metric. If it's separate data, use a separate metric.

As I see it by default more metrics is bad but tags can build up until that's bad as well and there's then probably a kind of to and fro between splitting things up a bit with metrics than tags but generally the preference should be on tags, not metrics. I think you'l always have cases where either it turns out a portion of a metric should have been a tag or a tag should have been a metric.

It's technically possible to make an abstraction that can switch between the two approaches for performance testing. It's also technically possible to make a profiling mode where given the appropriate usage patterns indicates if it appears a tag should be a metric or vise versa (usually by identifying that when reduced to metrics there's no overlap or that two metrics needed to be used for otherwise the same query).

I never saw a database system where you can insert your use cases like rather than just insert a = 1, b = 2, insert `a = 1 AND b = 2;a = 1;a IN(1)` though that's probably out of the scope of this.

The battle becomes even more epic when you pit group by against the other alternatives.

### Schema

What is a row key? What do the indexes actually look like? Are there composite indexes? Are they ordered? Are they hashes? Is there a plan to expose left to right indexes?

Rather than trying to explain it, it might be easier to just give the definitions used on the most concise level, IE in cassies syntax for example.

# Buckets you say?

This immediately stands out as it gives the impression that's all their is. As in you always end up fetching at least three weeks of data for a given metric and time range. I assume that's not actually the case but if I were looking at this database at a glance and saw that I'd quickly walk if for example my use case consisted of a lot of small range lookups across a busy (populated with a lot of data) metric within a retention period of a fortnight.

I would assume in reality cassandra provides a sparse array implementation and allows you to say you want from this column to that column? That raises the question because sparse columns are just an abstraction. Usually they're backed by either a hash map or a tree structure (though in some cases simplre or more complex solutions). If it's a map then that tends to preclude the possibility of a range lookup.

# WHAT?

> Similar to a query but only returns the tags (no data points returned). This can potentially return more tags than a query because it is optimized for speed and does not query all rows to narrow down the time range. This queries only the Row Key Index and thus the time range is the starting time range. Since the Cassandra row is set to 3 weeks, this can return tags for up to a 3 week period. See Cassandra Schema.

> {"start_absolute": 1357023600000, "end_relative": {"value": "5", "unit": "days"},

Kick the bucket, bad bucket.

**Comment by brianhks** [comment]
This is all over the place, are you referencing the documentation?  It would be nice to reference which docs with each paragraph.

**Comment by joeyhub** [comment]
Basically this one is pretty bad: https://github.com/kairosdb/kairosdb/wiki/Query-Performance

It also only covers one topic which isn't necessarily going to be the first one. The first thing a lot of people encounter is going to be how to tags actually work (not well explained that I could see) from a usage perspective and at least some notion of when to use tags vs metrics. It's hard to discuss the performance of something when it's not even clearly established what that thing actually does, the layout of the indexes it talks about will be intrinsic to that.

It talks about numbers which don't explain this:

`[1, 2, 3] x [A, B, C]` is 9 unique combinations of length 2, so presumably the indexes of:

`[1, A], [1, B], [1, C], [2, A], [2, B], [2, C], [3, A], [3, B], [3, C]`

Is this index combination based or permutation based? Is it nested or concatenated?

As in, what if I just want `tag2 = A`? What's implied here and that's really disturbing if true (I assume not) is that it gives the impression it creates indexes for every possible combination of values rather than those actually given.

What that implies is that if I have a thousand hotels, each has a thousand rooms and in a year each is visited by 100 globally unique people then it will create two hundred and fifty trillion indexes?

I suspect in reality it only creates indexes for the combinations it actually sees at least?

I assume that if I insert [1,A], [2,B], [3,C] then in reality I should only actually get those indexes? If I then look for [2,C] it'll surely just say nope no index no data? Assuming AND here. That also doesn't answer the question of only wanting one tag in particular.

If that's really the case that's not what people are going to think looking at that documentation. They're just going to see N * N * N which directly translates to money (as in how many computers you'll need as in = the $ scaling) and just say nope to that.

The point of scaling is not to allow throwing unlimited amounts of money exponentially at a problem (IE, 10 customers costs are 10% of revenue, 1000 customer costs are 1000% of revenue). It's usually to deal with problems where even when you've gotten it down to the best complexity it's still not enough and still needs to scale. Turning something from log n to n is quite bad but from log n to at least geometric complexity or worse is really bad.

That's probably not what's happening but it's what you say you're doing in your documentation. It's no wonder in that case people are raising questions about the cardinality. It might also if it's not true be what's causing people in the wild to use metrics when they should be using tags (that and it doesn't even clearly explain what tags do).

When you're indicating the presence of such a ballooning number of tags it's also no surprise that people have been questioning about the write performance. It's then strange that the statement says nope this has no impact which would to a lot of people might not appear in a great light.

It's not just that write up on query performance picks a very odd and narrow target, yet is vague and cryptic but also that it gives the impression of the worst possible case and then just brushes it off.

**Comment by joeyhub** [comment]
It's saying or implying that:

```
{
    prod: ['p1', 'p2', 'p3'],
    cust: ['c1', 'c2', 'c3']
}
```

Resolves to: `(prod === 'p1' || prod === 'p2' || prod === 'p3') && (cust === 'c1' || cust === 'c2' || cust === 'c3')`. In SQL that might be `prod IN ('p1', 'p2', 'p3') AND cust IN ('c1', 'c2', 'c3')`. It's also `('p1', 'p2', 'p3') JOIN ('c1', 'c2', 'c3')`.

Normally for that you would specify an index not just based on the data but also the usage pattern. Here an index of simply (prod -> cust) would suffice. That might simply be a 3 dimensional hash map. In terms of the loop iterating it then you would have 3 times 3.

That's typical for the kind of query about but the above is one use case of many. The document implies that an index is created for that use case representing the JOIN of the two value sets for the two tag names.

So if I insert: `{cust: 'c1', prod: 'p1'}` then it simply creates the index entry of:

`[['c1', 'p1']]`

But, if I then insert `{cust: 'c2', prod: 'p2'}` then it's saying that it creates the additional indexes:

`[['c2', 'p2'], ['c2', 'p1'], ['c1', 'p2']]`

Even if in fact it only creates the indexes it sees (so here would only actually establish the index `['c2', 'p2']` you'd still see the above behaviour if you actually insert those other two combinations as well. The latter case is more forgivable but still needs some awareness.

Things rapidly descend however because if it then has to look all of those up in a non-progressive fashion during a query then the query is still having to unroll all of the possible permutations. It might seem like it's potentially slow on insert but O(1) on read where as in fact it may be slower on read than on write if write is index the permutations seen and read is consider all the possible permutations. Luckily, that's likely mostly confined to the stated use case above if that is the case, as in simply wanting 'prod = ? && cust = ?' should be O(1).

**Comment by brianhks** [comment]
Some corrections are in order:  The index stores combinations and NOT permutations.  Tags and values are sorted before using them as a key so {a=1, b=2} is the same as {b=2, a=1}.  Tags are only stored as they are seen, the code does not generate combinations that have not been seen.  I mention this in the document "This assumes that each customer can be on either host." so as to clarify I'm talking about the worst case scenario.

The document was designed to address why some queries are faster than others and it addresses it on a very low level.  One of the pitfalls with Kairos is that you can insert crazy data (lots of tag combinations) and it all inserts really fast but when you query it, some queries return faster than others.

As the document points out there are two phases to the query, the first is to find the row keys that hold the data and the second is to get the actual data.  Scaling your cluster helps with the second portion.  The first tends to be the sticking point for getting a fast query.  When anyone is planning out their data they should load up kairos with a large sample set and then see how it performs.  Honestly you should do that with any time series system.  Every one out there has some weakness and you want to make sure your data and query patterns will work with it.

Query performance is very subjective to the query being performed, this is why there isn't a single go to document to tell you how fast it works because everyone's data is different and they won't make the same queries against it.

Ingest performance on the other hand is easy to measure at least for Kairos as it doesn't matter what your data looks like for ingest.  A great article on the matter is https://www.scylladb.com/2018/03/20/kairosdb-scylla-performance-scalability/

**Comment by joeyhub** [comment]
That makes sense, it's generally a bad case or worse case query that one.

The thing is the document makes it sound as if for that case kairosdb is doing something on the storage layer in accordance to that case when it seems it's really a case of: if you write a slow query then your query will be slow. Not many systems do well to optimise queries like that.

In that case, as far as I can make out, it's not strictly related to the number of tags your might store but it gives an impression of this being the case.

It's more confounding when other docs with query examples as far as I can see have that potentially particularly bad case as their example (where adding stuff means it scales poorly).

The thing is the typical user starting out is going to have a more basic question of that they want to store a lot of tags and then do simple lookups.

I want to just store tags representing the relational tree like: [city, hotel, room], [person] and generally lookups wouldn't be specifying multiple values for more than one of those which is probably a fairly common use case, IE, tags makes a little simple document with identity and relational keys.

For "safe" or "supported" simply use cases without too much fuss for performance, etc it would be good for the docs to be a bit clearer on that, as well as on how tags work and what they equate to. If it had a proper tags document in explaining how you can have a list of tag values, what that's delimited by (IE, OR) and how that combined with other tag names then it would be a natural place to mention the performance problems around adding either many small lists or more than one big list (basically multiple the counts).

It would be easy once explained as well to then create the proper cardinality calculator which as far as I'm aware is just `Object.values(tags).reduce((product, value) => typeof value === 'string' ? product : product * value.length, 1)`. As in maybe that existing doc can be reduced to:

> Q: Why is my query slow? A: Do the math, here's the formula.

**Comment by joeyhub** [comment]
For the bucket thing, its says it uses that for performance. It's deciding for the user what it think's best for them. Honestly I think that should just be a parameter or basically explicit to just set end = 'bucket' and let the user decide how they want to do it performance wise, similarly the bucket size is hard coded as a class constant. That doesn't look right to me.

**Comment by brianhks** [comment]
You have it wrong.  Tag cardinality directly effects the speed of the query.  A metric with a tag cardinality of 10 million will be a lot slower than a metric with a cardinality of 10 thousand.  During phase 1 of the query kairos must fetch all the row keys and the number is directly related to the cardinality of the tags.  So in the case of the first metric with 10million tag combinations (these are actual tags seen not just possible tags) kairos has to read 10 million keys and then filter them based on the query parameters.  For the second metric it only has to read back 10 thousand keys.  Cassandra doesn't provide any better way of doing this.  Now with that said we just added a new feature in the develop branch that lets you index on specified tags that you know have a high cardinality.  If you have two tags host and customer and you have 1 million customers you can add an index on customers and then if you specify a customer in your query it will use the customer index to find the rest of the row keys which is a lot quicker.

As for buckets, this is an optimization for C*  Most people don't understand how C* data is laid out so letting them change this is most likely going to get them into trouble.  The bucket size is optimized for both speed and space on disk.

**Comment by joeyhub** [comment]
It helps to be clear in what scope what's happening. For example a metric with a tag cardinality of a high amount could refer to either in the query or in the database. I'd say a high tag cardinality in the query alone is not something that's reasonably possible to optimise for in the worst case. As in you can improve the average case but never the worst case of having to process the full cardinality which is a point I'm trying to make, a high cardinality in a query is always going to have the potential to be slow.

What you're saying is that kairosdb just does select column1 from row_key_index where metric = ? and then doing runthrough. That's opportunistically fast in some cases versus instead trying to traverse the combinations.

But... it means that metrics are superior to tags for combinations of tags for CPU where your look ups only consider of AND (can be concatenated into the end of the metric name).

The one caveat with that is that for more than one lookup pattern it means duplicating the data. So if you have two usage patterns, `WHERE a = ?` and `WHERE a = ? AND b = ?` then you need to store two metrics: `namespace-a` and `namespace-a-b`. Basically `a` will contain all of `a-b` so it'll double the data.

A minor performance boost: It forces you to have at least one tag on insert so make that tag `'' => ''`.

I don't see the bucks anywhere in the schema/data. I'm guessing that's a little chunk of binary in column1.

What format is your binary serialization?

I don't see why it's a problem to give the user choice between speed or accuracy. It's a lost cause to try to handhold the user in that regard, though the documentation does need to be clear so that the users that can workout when and when not to have the information they need to make a determination. Some use cases for these are also important for debugging.

I'm sure a great deal of user frustration is from the documentation. Just here a bunch of things have popped up like tags not even being clearly explained which I'm sure some users are probably getting wrong and having issues because they're selecting more or less data than they expect to.

**Comment by joeyhub** [comment]
There's another thing, is it just doing `select column1 from data_points where key = ?` to get the bucket?

So basically it does...

`SELECT column1 FROM row_key_index WHERE metric = ?`

Then for each of those deserializes column1 and filters by bucket, then by tags?

Then for each of the remaining does:

`SELECT column1, value FROM data_points WHERE key = ? AND column1 BETWEEN ? AND ?`

I thought you had wide columns as in columns 0 to 1814400000 - 1 but you don't, at least in my version, which means key is repeated a lot. Maybe that's some confusion from other implementations of NoSQL.

So it must filter by buckets and tags. I assume you're able to use this TOKEN thing so the range lookup so you're not having to filter it? I see very confusing things on this subject. For some reason people only token in one direction. Then there are ordered and unordered partitions?

Does value have a use in row_key_index?

If you're going to serialize potentially large objects you should consider compressing that. Also the metric name seems redundant in column1 for row_key_index.

**Comment by brianhks** [comment]
We are discussing very low level schema design for Cassandra.  Also those two tables row_key_index and data_points were originally created using thrift.  From 1.2 on row_key_time_index and row_keys are the prefered tables, data_points is still around.

The 'column1' column in row_key_index is the same as the "key" column in data_points.  The "column1" column in data_points is a 4 byte millisecond offset from the timestamp in the key.

**Comment by joeyhub** [comment]
I think a lot is being weighed on cassadandra but at the same time it could be used better than kairosdb uses it. Though it goes against certain principles. I quickly realised some amount of duplication would be needed in some scenarios for indexing and the access pattern issue. After researching cassandra topic I'm finding the exact same, people are screaming about establishing access patterns first being important. Obviously for a generic tool like this that was a problem and it was never baked into the original the capacity for the user to inform the tool of their access patterns.

What I'm finding is really a holy nightmare, in some ways honestly, the tool should be embarrassed. We're now just moving over to Cassandra. I've replaced kairosdb with less than 1K lines of PHP that directly accesses Cassandra and that's it. It's several times faster and more adaptable. The issues I've found diving deep into the code and DB are just OMG, It's really made a huge mess for me. Now I have to spend ages cleaning up the mess KDB has made in Cassandra until only the actual data desired is left. Coming in after a few years of people using it and then having to pick up the mess, it really is a disaster. It's a consensus that the technical decision was awful and I've made the technical decision to move beyond KDB (though some of your commercial ventures actually look interesting).

There is though maybe a least a bit of an opportunity in the codebase's structure. It have two storag impls and seems made for that? Why not try making one for other systems like MySQL and MongoDB? It doesn't look like too much. You can also have more than one Cassandra impl. Before abandoning KDB I considered this but after making an impl in PHP just as a standalone client it was pretty redundant, KDB just becomes an expensive and meaningless client application.

**Comment by brianhks** [comment]
I'm glad you found something that works for you.
