### ISSUE TITLE
with cassandra cluster backend, one metric will store on one cassandra node or serveral casandra nodes?

### ISSUE THREAD

**Issue by ziflyingyo** [kairosdb/kairosdb#536]
I wonder about the data distribution of kairosdb. For example, with cassandra cluster backend, kairosdb stores one metric  on only one cassandra node or serveral casandra nodes?

**Comment by brianhks** [comment]
Cassandra is like a big hashtable, keys get distributed all over the cluster.  In the case of kairos a key is made up of the metric name, the tags,  a 3 week timestamp and some other bits.  The chances are very high that the data is distributed evenly around the cluster.
