### ISSUE TITLE
pass data_points as a bind parameter

### ISSUE THREAD

**Issue by brianhks** [kairosdb/kairosdb#537]
data_points has been hard coded into the CQL query but there are reports that doing that will prevent the client from sending the query to the right C* node.

**Comment by kmuthukk** [comment]
Thx @brianhks .

Yes. Say you had a table  T(pk1 int, pk2 int, val int) and PRIMARY KEY((pk1, pk2)) where pk1+pk2 where both partition key columns in a compound primary key. 

Then if the insert was:

`INSERT INTO T(pk1, pk2, v) VALUES (?, ?, 20);`  --> then a smart client is able to route it to the correct server owning the key in the cluster.

But if the insert was:

`INSERT INTO T(pk1, pk2, v) VALUES (?, 10, 20);` --> then a smart client is not able to route it to correct server, and will typically incur an extra hop on the server side to go to the correct node.

Same is true for SELECTs as well. A `WHERE pk1=? and pk2=20` will not be routed optimally.

I can speak for YugaByte DB, but suspect this is an issue with Apache Cassandra, DataStax, and ScyllaDB as well. The CQL wire-protocol is capable of telling the client, after a statement is prepared, which of the bind variables are part of the partition key -- but the server (which parses the statement on the initial prepare) doesn't tell the client about literal values that it has parsed out.

Without having the exact values of pk1 and pk2, a client is then unable to do the right hash calculations and send the statement to the correct server. Technically, the client could do a light weight parse of the statement on the client side itself to find these literals and match with the schema of the table to determine if that's a PRIMARY KEY partition column - but most client drivers (of other DBs too) will not do that. When done as bind variables, the client can easily do the hash calculations each time, and send the request to the correct node.
