### ISSUE TITLE
Cleaning up KairosDB metrics

### ISSUE THREAD

**Issue by joeyhub** [kairosdb/kairosdb#538]
I've noticed that over time usage in kairosDB goes up even though most of the inserts have a TTL.

I've noticed that kairos DB is storing lots of its own metrics for at least a year due to:

https://kairosdb.github.io/docs/build/html/Statistics.html

which is effectively a persistent memory leak.

This leads me to a couple of questions:

Managing load:

Is there a way to easily view what's using the most storage in terms of metrics, etc?

So far all I have is to try to do it manually.

Something as simple as being able to get the metrics list with the first bucket date included so people can check for where TTL hasn't been set.

Also points stored per metric.

Managing the statistics:

The documentation doesn't say anything about TTL for that, only turning it off.

It's also not explained if there are any utilities or ways to clean out that data.

**Comment by joeyhub** [comment]
Doing a google search you've got a properties file somewhere in the repo with the reporter on by default and set to report regularly. That should be quickly commented out or set to a lower frequency. There's a support ticket if you search from an IBM product having issues with that. In their case the solution seems to have been to just delete the data.

**Comment by brianhks** [comment]
If you haven't already you should look through the config file comments as it documents all the options and what they do.  You will also find a default ttl that can be set on all metrics.  If a metric comes in without a ttl the default is applied, this will then ttl the kairos internal metrics.
