### ISSUE TITLE
Sanity check: Where are slow queries stored?

### ISSUE THREAD

**Issue by joeyhub** [kairosdb/kairosdb#539]
If they're stored in the same database queries are being looked up from, they can impact the time of queries and then boom!

It should be possible to have kairos metrics going to another cassandra cluster.

**Comment by brianhks** [comment]
So slow queries are typically a result of the query itself and not the system as a whole.  Slow queries are stored in Cassandra and are quick to query.  In fact we were just tracking down a slow query that was causing resource issue and we used it.

As for storing kairos metrics in a different cluster it is a good idea and you can do that now with the Kairos-remote plugin.  It forwards metrics that match a filter on to a remote kairos cluster.  In this case you can configure it to only forward the internal kairos metrics.

https://github.com/kairosdb/kairos-remote
