### ISSUE TITLE
Support enhanced HTTP communication protocols

### ISSUE THREAD

**Issue by joeyhub** [kairosdb/kairosdb#541]
HTTP in it's traditional form wasn't made symmetric, that is, it always assumed people would just submit small things and receive big things.

It should be possible however to have requests work like responses which opens up a few feature requests: Support binary encoding and gzip in requests.

So basically...
```
(
    # Yes you can do this, if you manipulate HTTP to your own needs version it something like this or something, it's your HTTP server so you do what you want, but also have BC support.
    echo 'POST /datapoints KAIROSDB/1.0';
    # Can be gz, deflate, lzma, lzma1, etc, note make sure to strip preamble from lzma, lzma at level one tend to destroy gz level 9 on all fronts but often there's little point to have lzma past level 1.
    # If accept isn't used, either these are used to determine output or if not present defaults are used.
    echo 'Content-Encoding: lzma2';
    # Can be msgpack, whatever.
    echo 'Content-Type: application/bson';
    echo;
    run python or something and pipe into xz or something
) | nc localhost port | run python or something
```

**Comment by brianhks** [comment]
There are plugins that support receiving carbon https://github.com/kairosdb/kairos-carbon, influx format from telegraph https://github.com/kairosdb/telegraf-plugin and let you read data from a kafka queue https://github.com/kairosdb/kairos-kafka.

Kairos will also accept gziped http data if you the content-type to application/gzip.  This was a bit unconventional so in 1.3 you can pass the content-encoding as gzip as well.
