### ISSUE TITLE
Implement binary safety.

### ISSUE THREAD

**Issue by joeyhub** [kairosdb/kairosdb#542]
For performance reasons, people may which to use binary rather than Java and JSON's default UTF8. Generally speaking, there's no obvious reason for the system to be concerned with character encoding other than the one it gets lumped with from JavaLand. Even if it were that would probably be more of a UserLand thing. I'm not sure there's much use case for collations, etc? If there is that would be added on top as an extra option. Out of the box binary "supports everything" except the validation you get and collation both of which seem neither here nor there (people really should have already validated and appropriate collation can often be achieved with conversion with readback cases wanting to preserve being rare).

It should at least be clear in documentation that the system is unicode and B64 encoding should be used for binary safety.

For example this wont be binary safe: `size++; //Add one for null at end of string`

**Comment by brianhks** [comment]
I'm sorry but that is extremely unclear what you are requesting.

**Comment by joeyhub** [comment]
Right now everything is utf8. Such as your metric names. For example it'll do buffer.toString('utf-8'). On top of that it also store null terminated strings rather than with a length specifier.

The result of that is that if anyone wants to use anything other than utf8, they can't without base64 encoding it which inflates the size.

Even if you used a binary encoding to talk to the API the system internally will still treat byte arrays as utf8 rather than byte arrays. Basically, it treats byte arrays as strings. In C a string is just a byte array but in things like Java it's a character array so technically speaking it's the wrong type to use.

**Comment by brianhks** [comment]
The entire system was designed around using strings as metric names and tags.  Changing the system to allow binary data for a metric name would be way more work then it is worth at this point.
