### ISSUE TITLE
Version command is within versioned endpoint catch 22

### ISSUE THREAD

**Issue by joeyhub** [kairosdb/kairosdb#543]
To get the version to use for kairos API I need to know the version, for example: /api/v1/version

This means I can't use the version end point to know which version to use.

Happy April's Fools!

**Comment by brianhks** [comment]
There are two versions:  api version and kairos build version.  /api/v1/version returns the build version.  If I were to enhance the version api to take some parameters that breaks the old one, then I would add a new api /api/v2/version but I would leave /api/v1/version there for backwards compatibility.
