### ISSUE TITLE
Can I lose data from Cassandra cluster when updating Kairos?

### ISSUE THREAD

**Issue by viktorsmari** [kairosdb/kairosdb#547]
We have Kairos version 1.1.0-1.20151117201521 running on one server and 3 server cluster Cassandra and want to update Kairos.

I want to run a new Kairos version 1.2.2-1.20181109205636 on a new server (in case I need to switch back).

1. Can I try this without the possibility of loosing data from the Cassandra cluster?

2. And can I simply revert back if something goes wrong?

I also asked this on [StackOverflow](https://stackoverflow.com/questions/55812904/can-i-lose-data-from-cassandra-cluster-when-updating-kairos)

**Comment by brianhks** [comment]
So 1.2 can read 1.1 data but 1.1 cannot read 1.2 data.

You can install the new 1.2 server and verify that it can see your old data.  Then switch over ingest traffic to 1.2, once you do this 1.1 will not be able to see the new data (old data will still be available).  Lots of people have done this upgrade and you should be fine.
