### ISSUE TITLE
cache files not deleted correctly

### ISSUE THREAD

**Issue by sspieker** [kairosdb/kairosdb#549]
I'm using KairosDB 1.2.2.

I'm having a recurring problem with my temporäry cache folder (the one which is set by property `kairosdb.query_cache.cache_dir` in the config). Apparently, KairosDB does not delete the files (file handles?) correctly so the space is still used. This leads to constantly increasing space usage.

Here's what I see with the Unix df command (disk usage):
```
# df -h | grep kairosdb_tmp
[...]  4.0G  540M  3.5G  14% /opt/tsdb/kairosdb_tmp
```
Obviously, there's 540MB used, which is 14%.

Now, using the Unix du command (file disk usage) it shows an empty folder:
```
# du -sm /opt/tsdb/kairosdb_tmp
0	cache
```

Why the difference? This can be answered looking through the open files with the Unix lsof command:
```
# lsof | grep kairosdb_tmp
java	62768  63132	kairosdb  226u      REG	253,3  89827088    2097234 /opt/tsdb/kairosdb_tmp/cache/kairosdb/1556099270075/f5728414a3a20be47ff34752a3aaf430.data (deleted)
[... the above line is repeated 892 times ...]
```
Notice the "deleted" at the end of line which can't be the way it's supposed to be.

Seems like KairosDB keeps the filehandles of temporary files.
A KairosDB restart always solves this problem.

**Comment by brianhks** [comment]
I'm trying to reproduce this and I'm not able to.

What version of java and what file system are you using? 
Does it just do this for *.data files or are there others?

**Comment by brianhks** [comment]
The issue appears in conjunction with setting
kairosdb.datastore.cassandra.query_limit=1000000

Issue is discussed in the forum: https://groups.google.com/forum/#!topic/kairosdb-group/GfZONxxRWgI

**Comment by sspieker** [comment]
@brianhks , are you planning to release v1.3 anytime soon?

This particular issue is still bugging us: we've reduced the impact somewhat by increasing the limit to 10 mio datapoints, but nevertheless there's always guys querying more datapoints. So disabling the limit completely is not an option for us because this would lead to huge pressure in our C* cluster.

**Comment by brianhks** [comment]
I have a beta of metrics4j out which was my goal so I'm focused 100% on making this release by Christmas.
