### ISSUE TITLE
Hotfix for reporting issue

### ISSUE THREAD

**Issue by joeyhub** [kairosdb/kairosdb#551]
The documentation for various various of KairosDB for how to turn off the reporter is incorrect. Commenting out the line for the service doesn't stop it being loaded. Some people are using the scheduling instead to try to stop it.

While the documentation says to comment out or remove this line:

`kairosdb.service.reporter=org.kairosdb.core.reporting.MetricReportingModule`

That does not disable it, most likely because for injection it's meant to be an override.

As far as I can tell this *might* make it a noop...

`kairosdb.service.reporter=com.google.inject.servlet.ServletModule`

Though you can be really brutal and just set it to some junk (at the cost of some whining in the log at startup).

`kairosdb.service.reporter=null`

This is important for people to be aware of as under various loads with default settings the reporter can generate vast amounts of surplus data and disabling it isn't at least for versions below 1.2.* as presented in the current documentation.

**Comment by joeyhub** [comment]
In an old google group thread it also suggests `<disabled>`. Not sure if this would work in the same way null works or if it's the right way to explicitly tell the injection library to not load it.

**Comment by brianhks** [comment]
Yes the documentation needs to be updated to make that clear.

**Comment by jsabin** [comment]
Fixed in commit cda627e8e90b03c5a1fa9e1f1bb0b67c24a605f9.
