### ISSUE TITLE
next release date??

### ISSUE THREAD

**Issue by kopens** [kairosdb/kairosdb#552]
next release date??

**Comment by mamoit** [comment]
One thing about open source projects...
You don't ask for release dates.

**Comment by brianhks** [comment]
I said by the new year and then I thought maybe the Chinese new year.  There are just a few items left on the 1.3 milestone and I'm hacking away at those until a coworker finishes a feature that will let you identify and kill queries on the server.  At this point I'm expecting another beta in a few days followed by a release in about a month.
