### ISSUE TITLE
There some datas can not be inserted.

### ISSUE THREAD

**Issue by flykarry** [kairosdb/kairosdb#553]
I have 100 parameters, It's work normally, But I don't know when there is some point can not be inserted, I restart the kariosdb or cassandra is doesn't work. And maybe some time later, it work normally too, but the data lost at that time range.
I debug the code, It can pass, but I can't query the point at the kairosdb web console or my program.
And there is no any error log at kairosdb , cassandra.
I don't why, but It is appear at 2 our project. I don't when and why

Below is a demo screenshot of my code, Is there anything wrong? 
customerId and datatype is only one value. paramId has 100 different value.
the PoolingClient is a fork of the official Java Client added http client pool
this is my fork https://github.com/flykarry/kairosdb-client
![image](https://user-images.githubusercontent.com/14309127/57672604-6162cb00-764b-11e9-897a-c19722c1264a.png)

**Comment by jsabin** [comment]
My guess is that the timestamp is being written in seconds and not milliseconds. Do a query back to the beginning of time (Jan 1, 1970) and you will probably see the data you have written.

**Comment by flykarry** [comment]
I reviewed my code in production environment, the timestamp is being written in milliseconds. Because I set the time use calander.getTime().getTime()

**Comment by guifengcheng** [comment]
check if you have empty fileds

**Comment by flykarry** [comment]
there is no empty fields.

**Comment by brianhks** [comment]
Have you resolved this issue?  You said it worked at one time and then stopped.  Can you query back to the time when it stopped?  Or when you query it doesn't return anything anymore when it used to?

**Comment by flykarry** [comment]
Sorry, I can't replicate it. Maybe It's due to the cluster of cassandra in my opinion.
