### ISSUE TITLE
Timezone selection is not woking

### ISSUE THREAD

**Issue by biswaKL** [kairosdb/kairosdb#554]
Hi Team, i have installed Kairos with Cassandra in my server where the timezone is IST,
But i am not trying to query the data in any other time zone but the data points coming in the graph shows the same, IST time zone only.

**Comment by jsabin** [comment]
All times specified in the query are UTC. The timezone in the UI is used by sampling aggregators and not used by the UI to display the results of the query. The UI graph displays the data according to the browser timezone.

This is not clear in the UI. Perhaps the UI needs to be modified to make this clear.

**Comment by kyleboyle** [comment]
I've improved timezone functionality on the web UI with the pull request here: https://github.com/kairosdb/kairosdb/pull/593

Perhaps try voting for it to get it merged, thanks.

**Comment by brianhks** [comment]
I merged @kyleboyle pull request to address this.
