### ISSUE TITLE
Support - Need help / details on some use case

### ISSUE THREAD

**Issue by iamshreeram** [kairosdb/kairosdb#556]
We have use case for pushing the log data (events) of driving app into KairosDB. 
Note : This app is currently running in `Elastic search` -> `grafana` tech stack

Below is the sample log -
```
source,timestamp,method,componentName,service,country,regionID,driverid,status,latency
198.162.1.10,06/Jul/2019:10:42:56,POST,localtionApp,finder/serviceA,IN,5233,sram,1,50
198.162.1.10,06/Jul/2019:10:42:57,POST,localtionApp,finder/serviceB,IN,2301,sram,0,68
```

We would want to retrieve below insights from above data -
For each country, find list of region
For each region find list of drivers 
For each drivers, find list of components he has used
and lot of similar use cases. 

Below is what I'm trying to do - 
```
{
    "name": "kairosdb.datastore.$componentName.$service.$country.$regionID.$driverid.$method.hits",
    "timestamp": $timestamp,
    "type": "int",
    "value": 1,
    "tags":{"sourceip":$source}
}
```
I'm persisting the hits as 1. But, the problem with above approach is, I'm unable to retrieve the insights that I'm looking for. E.g., Find list of driverid's for list of region.

Is `KairosDB` a good tool for my use case? or should i continue to use Elastic search?
Is this valid approach?  

If not, can you please suggest what would be right approach to store the data in Kairos?

**Comment by iamshreeram** [comment]
@brianhks , Can you please check my use case and point your suggestion. Thanks!

**Comment by jsabin** [comment]
I'm not sure I totally understand the use case and not sure that time series is the right way to go. However, if you make $country.$regionID.$driverid separate tags instead of part of the metric name, you could filter or group components by these 3 fields. Thus you could filter a component by a specific country, region, and/or driver id.

**Comment by brianhks** [comment]
I don't think Kairos is the right tool for what you are looking at.  Kairos is better for answer the question of how may hits did a driver have over the past month.  For the questions you have a simple relational DB would work better or leave it in elastic.
