### ISSUE TITLE
Rollups not working after some time.

### ISSUE THREAD

**Issue by kunalmanch** [kairosdb/kairosdb#558]
KairosDB - 1.2.2
Cassandra - 3.11

I have triggered multiple rollups and they work fine for 2 days (give or take). After that, the rollups just don't get triggered. However, there's data in the target metric during that period. Further, I don't see any rollup related logs nor do I see any error in the logs. Thus, I don't have any meaningful logs to share. But the list rollup API is showing the correct set of rollups that I have triggered.

Please advise if you need anything else from me.

Thanks.

**Comment by jsabin** [comment]
Yes, there is a bug in rollups that has been fixed in the develop branch.

**Comment by kunalmanch** [comment]
Thanks. Will check it out.
