### ISSUE TITLE
Unable to connect to Azure CosmosDB (cassandra)

### ISSUE THREAD

**Issue by biswaKL** [kairosdb/kairosdb#566]
I created client keystore using [this tutorial](https://docs.datastax.com/en/developer/java-driver/3.1/manual/ssl/)

then tried running kairos using:
`./kairosdb.sh run -Djavax.net.ssl.keyStore=/root/client.keystore -Djavax.net.ssl.trustStorePassword=mypass>`

but then i am getting error like:

`03:20:24.262 [main] INFO  [NettyUtil.java:73] - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.`
`03:20:24.680 [main] ERROR [CassandraModule.java:136] - Unable to setup cassandra schema`
`com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host <mydomain>/<myip>:10350: Cql request had unsupported headers Compression
`

**Comment by brianhks** [comment]
I should have read your questions in the right order.  We need to make the compression configurable.

**Comment by biswaKL** [comment]
Thanks for this, after that also i made some changes for adding trust-store certificates, i will create a branch and raise a merge request

**Comment by brianhks** [comment]
Yes please
