### ISSUE TITLE
Data is going in Queue

### ISSUE THREAD

**Issue by biswaKL** [kairosdb/kairosdb#568]
My all data is going into queue folder.
Why is that happening, and what is the procedure to push those queue data into Cassandra ?

**Comment by brianhks** [comment]
Kairos uses a queue in order to efficiently batch data to Cassandra.  The data is flushed out of the queue frequently based on configuration parameters.

Are you not seeing any data in Cassandra?

**Comment by biswaKL** [comment]
In Windows, i can see the queue files, Cassandra is also running, but those queues are not getting cleared. Tried by restarting both as well.
I cleared entire queue folder, then the fresh data starts getting pushed inside Kairos

**Comment by brianhks** [comment]
If you are using the FileBackedQueue it will always put data in the queue.  The queue is there for resiliency if Kairos crashes before data is sent to C*.

Is the data showing up in Cassandra?  Can you query it from the UI?

The queue files should automatically rotate if data is going into C*, are you seeing any errors in the log file?

**Comment by biswaKL** [comment]
Dont know buddy, i didnt got time to check that. I am closing this issue and i will re-open if i get it next time.
