### ISSUE TITLE
Reflect Cross-site Scripting on error message (WEB UI / view.html, graph.js)

### ISSUE THREAD

**Issue by k1tten** [kairosdb/kairosdb#569]
Hello,

I want to report a Reflect Cross-site scripting issue on `view.html`.

## Vulnerability
A function call on [view.html, Line 48](https://github.com/kairosdb/kairosdb/blob/master/webroot/view.html#L48) will append error message by `showErrorMessage` function.

`showErrorMessage` function was declared in [js/graph.js](https://github.com/kairosdb/kairosdb/blob/master/webroot/js/graph.js#L352)
The error message will append to html without any escape.
```
function showErrorMessage(message) {
	var $errorContainer = $("#errorContainer");
	$errorContainer.show();
	$errorContainer.html("");
	$errorContainer.append(message);
}
```

So we can create a malicious error query and then trigger the XSS easily:
``` 
/view.html?q={"metrics":[{"tags":{},"name":"123","group_by":[{"name":"tag","tags":["1"]}],"aggregators":[{"name":"sum","sampling":{"value":"<script>alert(document.domain)</script>","unit":"milliseconds"}}],"limit":"1"}],"plugins":[],"cache_time":0,"start_absolute":1570723200000,"end_absolute":1571241600000}&d=[{"scale":true}]
```
![](https://images.plurk.com/66c3wUonYsoKea3rdmhAwO.png )

## Fix
You can escape the malicious code or fix with url encode `append(htmlEncode(message))` before append to html.

Best Regards.

**Comment by brianhks** [comment]
Nice hacking.

**Comment by brianhks** [comment]
Honestly how did you find that?

**Comment by k1tten** [comment]
@brianhks 

I was test my Grafana Apps then.
I saw something weird in kairosdb's error message, so I started to trace code and find out the bug.
