### ISSUE TITLE
File backed queue rapid size increase

### ISSUE THREAD

**Issue by sizzles** [kairosdb/kairosdb#573]
Hi

I've had some instances of the queue size rapidly increasing on the KairosDB machine - which is plugged into a Scylla cluster.

Where by data is being ingested into Scylla, however the Kairos queue starts to rapidly increase in size and using the available disk space.

I am trying to understand the cause / possible actions to take?  Perhaps disabling the file back queue or limiting its size?

Thanks
Alex

From looking at the logs of Kairos - I see the below - the 'Page file queue/kairos_queue/index/page-1093.dat was just deleted' coincides with the queue size rapidly increasing. 

(I've seen the same in logs on another occasion)

11-08|18:28:00.431 [cluster1-nio-worker-26] INFO  [RequestHandler.java:646] - Query INSERT INTO data_points (key, column1, value) VALUES (?, ?, ?) USING TTL ? AND TIMESTAMP ? is not prepared on SCYLLA2, preparing before retrying executing. Seeing this message a few times$
11-08|18:31:05.298 [cluster1-nio-worker-0] INFO  [RequestHandler.java:646] - Query INSERT INTO row_key_time_index (metric, table_name, row_time) VALUES (?, 'data_points', ?) USING TTL ? is not prepared on SCYLLA2, preparing before retrying executing. Seeing this message $
11-08|18:31:05.299 [cluster1-nio-worker-27] INFO  [RequestHandler.java:646] - Query INSERT INTO row_keys (metric, table_name, row_time, data_type, tags, mtime) VALUES (?, 'data_points', ?, ?, ?, now()) USING TTL ? is not prepared on SCYLLA2, preparing before retrying exe$
11-08|18:31:05.300 [cluster1-nio-worker-30] INFO  [RequestHandler.java:646] - Query INSERT INTO row_keys (metric, table_name, row_time, data_type, tags, mtime) VALUES (?, 'data_points', ?, ?, ?, now()) USING TTL ? is not prepared on SCYLLA2, preparing before retrying exe$
11-08|18:31:31.453 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/index/page-1090.dat was just deleted.
11-08|18:31:31.460 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/index/page-1091.dat was just deleted.
11-08|18:31:31.466 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/index/page-1092.dat was just deleted.
11-08|18:31:31.472 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/index/page-1093.dat was just deleted.
11-08|18:31:31.478 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/index/page-1094.dat was just deleted.
11-08|18:31:31.484 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/index/page-1095.dat was just deleted.
11-08|18:31:31.489 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/index/page-1096.dat was just deleted.
11-08|18:31:31.499 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-2631.dat was just deleted.
11-08|18:31:31.508 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-2632.dat was just deleted.
11-08|18:31:31.518 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-2633.dat was just deleted.
11-08|18:31:31.527 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-2634.dat was just deleted.
11-08|18:31:31.536 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-2635.dat was just deleted.
11-08|18:31:31.545 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-2636.dat was just deleted.
11-08|18:31:31.553 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-2637.dat was just deleted.
11-08|18:31:31.562 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-2638.dat was just deleted.
11-08|18:31:31.571 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-2639.dat was just deleted.
11-08|18:31:31.580 [Ingest worker-622] INFO  [MappedPageFactory.java:217] - Page file queue/kairos_queue/data/page-2640.dat was just deleted.

![kairos_queue](https://user-images.githubusercontent.com/20998784/68578129-54435f00-0469-11ea-80be-bec42b83a177.png)

**Comment by jason-es** [comment]
Can you provide info on what you did to fix the issue? @sizzles
