### ISSUE TITLE
Duplicate Datapoints for same Timestamp

### ISSUE THREAD

**Issue by biswaKL** [kairosdb/kairosdb#574]
Why i have 2 different data points for the same timestamp and same tags..?? 

![image](https://user-images.githubusercontent.com/18054617/69032737-35157600-0a03-11ea-9dd6-7b8ff27fc16a.png)

**Comment by biswaKL** [comment]
FYI, both are of same datatype
[1572978600000, 0], 
[1572978600000,1 ],

**Comment by sspieker** [comment]
From experience, I believe you are forgetting about another tag. If the metric does have another tag, use groupby or filter to separate those datapoints.

**Comment by biswaKL** [comment]
I also feel the same, but i added all the tags available in the drop down.

**Comment by brianhks** [comment]
So you can have duplicates if one is sent as a long value '0' and the other is sent as a double value '1.0'.  Kairos stores them separately.  You need to make sure they are all sent the same way have a look a the data on its way in.

**Comment by biswaKL** [comment]
@brianhks , I would like to inform you that i am pushing only float values into it.  However i found this error only once till now, so cant take a decision. Closing the issue for now, will do a deep dive into this when it comes next time.
