### ISSUE TITLE
Data Missing in Kairos

### ISSUE THREAD

**Issue by biswaKL** [kairosdb/kairosdb#583]
OS: Windows

While pushing the data into KairosDB i am getting status 204, but when i see in the graph data wont be there. This is happening randomly, there is no fixed time interval. CPU utilization is 90% always. Could that be a reason for this?

**Comment by brianhks** [comment]
Well I need more information on the missing data.  I would expect Kairos to log some error if it is unable to send data to Cassandra.

How can you tell it is missing?  Describe the data you are inserting.

**Comment by biswaKL** [comment]
@brianhks , i found that it was cpu issue, when we found a significant decrease in the number of missing data points.
