### ISSUE TITLE
Add support for descriptions of metric

### ISSUE THREAD

**Issue by burtonator** [kairosdb/kairosdb#59]
If you have system with thousands of metrics with unique names, you're going to need a way to manage these.

Descriptions of what they do are going to be valuable... including an API for setting and querying them.

It might also be nice to tag the descriptions so that you can get results that way.  For example, find all metrics produced with stats for the JVM, or stats for cassandra, or internal stats from your company.

**Comment by brianhks** [comment]
Adding extra data about your metrics is what the metadata api was created for: http://kairosdb.github.io/docs/build/html/restapi/Metadata.html
This was added in 1.2
