### ISSUE TITLE
Provide detailed information for ExecutionException: "Failed to read key index"

### ISSUE THREAD

**Issue by hinstw** [kairosdb/kairosdb#591]
I have been getting a weird error from KairosDB:

> Failed to read key index

I get this text from client.query(queryBuilder).getErrors(). There is only one item in getErrors() list.
The problem is that this information is somewhat insufficient to understand what exactly is wrong. The only thing I have is this string: "Failed to read key index".
The error happens sometimes when  save-as aggregator is used. My guess is that save-as aggregator is one of the infrequently used aggregators, so there might be a bug somewhere in it.

I saw this code in KairosDB:

		catch (ExecutionException e)
		{
			throw new DatastoreException("Failed to read key index", e);
		}

The proposed change is to add at least executionException.message to the string, so that we have (hopefully) more information about the exception.

Thanks

**Comment by brianhks** [comment]
Details of the error should be logged on the Kairos server.  The error is likely a problem communicating with Cassandra in some ways.

**Comment by hinstw** [comment]
Ok I see. I did not know that those errors are logged. I saw the information I was looking for in log files. The error was "timeout". I guess there is no need to provide more logs in API response. I believe the issue can be closed
