### ISSUE TITLE
how to install 2 kairosdb in one server

### ISSUE THREAD

**Issue by ghookas** [kairosdb/kairosdb#594]
is there a  way to install more than one instance of kairosdb in a server?

**Comment by kyleboyle** [comment]
What problems are you having? You will at least need to configure different jetty ports for each, and other ports if using telnet server, tls endpoint, etc.

**Comment by brianhks** [comment]
Easiest is to run out of two different install directories.  As @kyleboyle points out you will need to set different ports for each service to listen on in the kairosdb.conf file (kairosdb.properties if on 1.2.2)
