### ISSUE TITLE
Official helm chart for kairosdb.

### ISSUE THREAD

**Issue by rcosnita** [kairosdb/kairosdb#606]
It might come handy to have an official helm chart which can be used to deploy kairosdb in kubernetes clusters.

The helm chart should only contain the kairosdb deployment and a way to control the configuration through config maps.

The helm chart should reference the official kairosdb image built in #288 . Of course, this is just the default value, but this can be changed through custom values file.

For the moment, I would recommend keeping the helm chart within the same repository as the rest of the code and then we can contribute it to https://github.com/helm/charts once we are satisfied with the implementation.

**Comment by brianhks** [comment]
Sure, but as I know nothing of helm charts do you have a suggestion of one to start with?  Adding it to the source would be a good idea.

**Comment by rcosnita** [comment]
I will contribute one in the following days. I am currently working on this in a different project. By the end of next week I should be able to open a relevant PR.

**Comment by brianhks** [comment]
Excellent

**Comment by rcosnita** [comment]
For the moment, I published a kairosdb version under my dockerhub account. @brianhks it would be great if you can create the official dockerhub id so that we can start publishing the official builds and use them in the helm chart as well.
