### ISSUE TITLE
Not possible to disable statistics metrics?

### ISSUE THREAD

**Issue by hinstw** [kairosdb/kairosdb#615]
Good day

I set `kairosdb.service.reporter=<disabled>`  in config but statistics metrics are still being written

Steps to reproduce:

1. Set `kairosdb.service.reporter=<disabled>` in `conf/kairosdb.properties`
1. Restart kairosDB
1. Delete ALL metrics using KairosDB API
1. Go to KairosDB Web UI, refresh the page
1. Look at the list of metrics in the dropdown box
1. Observe that the list of metrics is totally empty
1. Enter metric name: "a"
1. Click `Graph` button
1. Observe the empty output
1. Click `Update metric names` button
1. Expand metric name dropdown

Expected result:
1. The list of metrics is still empty

Actual result:
1. Observe that there are 8 new metrics with names starting with `kairosdb.`

`{"version": "KairosDB 1.2.2-1.20181109205636"}`

**Comment by brianhks** [comment]
Try also setting kairosdb.queries.aggregate_stats=true

**Comment by hinstw** [comment]
Thanks for the advice. I tried changing the suggested setting and statistics metrics stopped appearing.
