### ISSUE TITLE
Metric names are truncated

### ISSUE THREAD

**Issue by burtonator** [kairosdb/kairosdb#62]
This isn't fun...

http://i.imgur.com/v31uGUo.png

http://i.imgur.com/xoYrzbw.png

.... either way the UI is rather difficult to use because I can't see the full metric name.

I'll hacked the CSS for now but this probably should be fixed.

There are only three places where this applies.  In the HTML there's a manually coded width.. and there two places in the CSS where this needs to be fixed.

But I think the fact that the current UI doesn't reflow is problematic.

I guess a short term fix could be to widen the UI by like 300px... 

But in the long term having a solution that can handle longer metric names might be nice.

**Comment by jsabin** [comment]
The field in the UI has been expanded.
