### ISSUE TITLE
/metadata api claims content-type as json but returns text

### ISSUE THREAD

**Issue by djzort** [kairosdb/kairosdb#624]
From a quick curl

curl -v http://monitor01:8080/api/v1/metadata/MetricService/collectd.cpu/Description
*   Trying 172.29.0.124:8080...
* TCP_NODELAY set
* Connected to monitor01 (172.29.0.124) port 8080 (#0)
> GET /api/v1/metadata/MetricService/collectd.cpu/Description HTTP/1.1
> Host: monitor01:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Pragma: no-cache
< Cache-Control: no-cache
< Expires: 0
**< Content-Type: application/json; charset=UTF-8**
< Vary: Accept-Encoding, User-Agent
< Transfer-Encoding: chunked
< Server: Jetty(8.1.16.v20140903)
< 
* Connection #0 to host monitor01 left intact
**CPU Usage**

**Comment by djzort** [comment]
This is in 1.2.2

**Comment by brianhks** [comment]
This is a tricky one.  The api is designed to give back whatever it is you stuck in without changing it, as I could see that being annoying.  So if you didn't put in valid json, why should it return valid json?  I could change it to send and receive plain text but that makes it difficult for applications that are using json as most rest libraries only work if the content type is json.

**Comment by brianhks** [comment]
I think I'll leave it as is unless a good suggestion is made on how to deal with it.

**Comment by djzort** [comment]
Why not have the content type a just text/plain?

**Comment by brianhks** [comment]
OK so how about this.  There are two methods and depending on what accept header you pass it will return with the appropriate header.  So if you want to stick in text or json you can and get it out how you like.  Granted I won't do anything to validate or change the content, kairos will just set the header.

**Comment by djzort** [comment]
Responding the accept header is appropriate.
