### ISSUE TITLE
Numerous grammar errors on "Logging" documentation page

### ISSUE THREAD

**Issue by wittekm** [kairosdb/kairosdb#626]
https://kairosdb.github.io/docs/build/html/Logging.html

![image](https://user-images.githubusercontent.com/578530/86194056-59414580-bb02-11ea-8d97-4e5d03a9a8e4.png)

Ideally these would be
1st:
KairosDB creates its 

2nd:
well-known

3rd:
its

**Comment by brianhks** [comment]
I will sack our tech writer right away.

**Comment by wittekm** [comment]
Hah
