### ISSUE TITLE
Enabling row caching in cassandra doesn't get the performance improvement I expect

### ISSUE THREAD

**Issue by colindavra** [kairosdb/kairosdb#632]
I have been using kairosdb 1.1.1 with cassandra 2.1 for some time now. Recently the number of tags associates with a metric have risen and now the time to read the row_key_index is taking quite a bit of time, ~1.5-2 seconds for 15k entries. 

To remedy this, I enabled the row cache on cassandra and configured row caching on the row_key_index with the assumption that removing disk seeks from reading the index I would get a performance boost.

I with some testing I could see that the row cache was not being populated and no improvement materialised.

I upgraded to cassandra 3.11 and kairosdb 1.2.2, the data remained in the old schema (this seemed reasonable). However there was still not hits on the row cache.

Finally I wiped my db and imported all the data again to populate the new cassandra schema. I also enabled row caching on the row_keys table, with the same assumption: cached rows avoid disk seeks boosting query performance

This time I could see that the row_cache was being hit but query performance degraded.

Am I missing a configuration step here or am I beyond the reasonable use limits of kairosdb?

**Comment by brianhks** [comment]
First off you should have a look at: https://github.com/kairosdb/kairosdb/wiki/Query-Performance
It breaks down each phase of the query and what is going on.

Next what are you putting in as tags?  How far back are you queries typically?

**Comment by colindavra** [comment]
Thanks Brian,

The typical tags used would be a UUID of a sensor, this would be a stable but potentially vast population. I am benchmarking for 100k distinct tuples. 

There is no typical timerange my users would be requesting but I would favour retrieving data over the most recent 7 days. If I understand the schema correctly this would whittle down to a single data row for one sensor

It appears that the majority of the time is taken-up with transmitting the row_keys over the wire to be further filtered by kairosdb.

I would like to try out the tag_indexed_row_keys setting in 1.3 but don't see info on how to set it up. The UUID would be an excellent candidate for a dedicated row index as the number of index entries returned would be orders of magnitude smaller.

Does the 1.3.0_beta_1 artifact have this feature in it and could you point me in the direction of any info to set it up?

I would be happy to contribute to the effort in testing/documenting this feature if you think that would help.

Kind Regards,
Colin
