### ISSUE TITLE
Cassandra credentials

### ISSUE THREAD

**Issue by stela-leon** [kairosdb/kairosdb#633]
Hi people, 

I am trying to spin up KairosDB on top of a Cassandra node, my problem is that I need to authenticate kairos to cassandra. 
I browsed a bit the source code here and I tried to pass the credentials via 
```
kairosdb.datastore.cassandra.auth.username=admin 
kairosdb.datastore.cassandra.auth.password=eat_me 
```
OR
`storage.cassandra.username/password `in the Values.yaml didn't work either. 

Any hint is so very welcome!

**Comment by stela-leon** [comment]
got this working via setting a secret from helm and load it in the deployment.yaml, setting the creds via env variables. 
https://github.com/kairosdb/kairosdb/pull/634 
I hope it helps, definitely I'd be interested in the feedback :)

**Comment by sevko21** [comment]
@stela-leon can you help me on this? I'm also using the helm chart

**Comment by brianhks** [comment]
Thanks for the pull request
