### ISSUE TITLE
Is there a way to log query or insert result?

### ISSUE THREAD

**Issue by soyoeml** [kairosdb/kairosdb#645]
Hi,

Is there a way to log query or insert result? I hope there is a configuration I can log all queries including insert result. I found KairosDB lost data I added. I need see the logs of all queries.

Thanks

**Comment by soyoeml** [comment]
Add log to DataStax driver can see the query succeed or failed. But cannot see cql statement.

**Comment by brianhks** [comment]
There is a trace feature you can turn on in cassandra that will do what you want I believe.  https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/cqlshTracing.html
