### ISSUE TITLE
What are the recommended way of clustering?

### ISSUE THREAD

**Issue by iudeen** [kairosdb/kairosdb#649]
What is the recommended way to cluster Kairos and Cassandra/Schyla?

**Comment by iudeen** [comment]
All our deployments are in Kubernetes, and I don't think we have any other choice but to go for Cassandra in a Kubernetes cluster. 

We have set up Cassandra with 3 replicas, with disks attached to each. And then 3 replicas of Kairos. We noticed drastic slowness in Kairos Queries. On investigation, it was noticed that Cassandra-2 was loaded fully (both CPU and Memory) while Cassandra-1 and Cassandra-0, the CPU utilization was almost negligible (memory was similar to Cassandra-2). 

This got me wondering if the clustering is not proper. Also, [there is a section in the documentation](https://kairosdb.github.io/docs/MultiCluster.html) where Multi-node clustering is discussed. Do we need to look into it?

**Comment by brianhks** [comment]
That is weird, sounds like you are doing everything right.  We had a team working on getting C* into kubernetes and they ran into all kinds of issues with networking and system utilization.  They eventually gave up.  My suggestion is to use the C* tools to make sure the cluster is healthy and everything is replicated correctly.

As for the Kairos multi clustering: it is for managing data growth and to help migrating to new clusters.  For what you are doing it has no bearing.

**Comment by brianhks** [comment]
Also sorry for the long delay in replying.  I had some personal issues that occupied my attention as of late.

**Comment by biswaKL** [comment]
NO issues @brianhks , @iudeen and me are in same team, We really appreciate your efforts.
We have one C* cluster as well (without kuberneties) that seems tobe running fine.

**Comment by iudeen** [comment]
Thanks for your reply and clarification! The issue was all at the C* cluster in Kubernetes. We had to do a deep dive into various configuration strategies to get it working. After doing that, we are now better performance.
