### ISSUE TITLE
Time Series Downsampling/Upsampling

### ISSUE THREAD

**Issue by AbdelouahabKhelifati** [kairosdb/kairosdb#652]
I am trying to downsample and upsample time series data in KairosDB. Time series database systems (TSDS) usually have an option to make the downsampling and upsampling with an operator like SAMPLE BY (1h).

Is there a possibility to downsample time series on KairosDB?

Thanks in advance!

**Comment by brianhks** [comment]
I think what you are looking for is aggregators.  https://kairosdb.github.io/docs/restapi/Aggregators.html
Also just load up the kairos ui and play with the aggregators there.  There is an option in the UI that lets you see the query that it is making so you can use it if you are calling the api directly.
