### ISSUE TITLE
Continuous Queries Support

### ISSUE THREAD

**Issue by AbdelouahabKhelifati** [kairosdb/kairosdb#653]
I am trying to evaluate the ability of KairosDB on performing continuous queries on time series data.

Continuous queries on time series data are queries that run automatically and periodically on real-time data (and maybe store query results in a specified measurement). Some Time Series Database Systems (TSDBs) have a built-in operation that allows doing this (e.g. InfluxDB, TimescaleDB).

I couldn't find in KairosDB' documentation a way to perform this type of query. Another alternative would be to program the frequency of queries in a separate programming language/system clock that would run the given query frequently and automatically every time length. This is however not guaranteed to be fair 1) to the system because the performance would depend on an independent factor (the third-party programming language) and 2) to the other systems because they provide an extra convenient feature that KairosDB does not.

My question is there an efficient way that could be used for the purpose of performing continuous queries? If not, what are the alternative I have using KairosDB in order to perform the continuous queries?

Thanks!

**Comment by brianhks** [comment]
I think I answered this sufficiently in the discussion board.  Basically you have the rollups and the save_as aggregator that lets you do what you are looking for.
