### ISSUE TITLE
How to clean data and metrics by manual ?

### ISSUE THREAD

**Issue by godliam** [kairosdb/kairosdb#658]
HI Team:
- kairosdb version: 1.2.2-1
- With 3 hosts cassrandra clusters version: apache-cassandra-3.11.3 

My cassrandra clusters serve for kairosdb only, Its uptime 2 years ago. They load are 13Tib now. 
I was deleted all data 3 months ago by RestAPI, And all requests returned 204, but the cassrandra load still are 13Tib.

The RestAPI seems not worked?
So, How to clean old data and free those occupied space ??

**Comment by brianhks** [comment]
Deleting data from C* is tricky.  There are many factors involved.  Mostly it depends on the compaction strategy you have in place.  That is ultimately when the data will get deleted is when C* compacts it away.  In version 1.3 we introduced the multi cluster concept.  We use it at our company to manage data size.  What you do is create a new cluster as your write cluster and the old one becomes a read cluster. (you can have many read clusters)  When your read cluster is old enough that you don't care about the data you just delete it.  We rotate a new cluster in every quarter and keep just over a year of data.

One strategy I've used in the past with C* is to delete old sstables.  If the file is older than a year then you are guaranteed it has data that is over a year old.  How well this works depends on your compaction strategy.

**Comment by godliam** [comment]
@brianhks thkx for your practices !!
