### ISSUE TITLE
How to do sampling query?

### ISSUE THREAD

**Issue by jim-king-2000** [kairosdb/kairosdb#666]
## requirement
Suppose we save some data one point per second. And we need to display the chart of the data within one year on web. Obviously there are too many data to display. So we are going to reduce the data. For example, we could grab 10 data points per month. So our chart would contain 120 data points. That is fairly good.

## question
How can I do the query operation described above?

**Comment by brianhks** [comment]
You need to add an aggregator to the query.  You can sum/avg/min/max (http://kairosdb.github.io/docs/restapi/Aggregators.html) over a day that will give you one data point per day.
