### ISSUE TITLE
Remove Genormous from unrelated classes (other than H2)

### ISSUE THREAD

**Issue by lcoulet** [kairosdb/kairosdb#674]
Hello, Genormous is an old artifact and we have warning reported about vulnerabilities on this library.
It should only be required for H2... So we could remove this dependency in production.

But Some other classes  like AdminResource and QueryQueuingManager use Pair class from this library that prevent from removal in operation.

**Comment by brianhks** [comment]
I did not realize that, thanks for the input.  I have a release in the works and I'll add this to it.  
1. I'll update genormous and fix any vulnerabilities
2. I'll isolate the dependencies so it can be removed when not in use.

Can you post the output of your scan and what it identifies as a vulnerability in GenOrmous?
