### ISSUE TITLE
Grouping returns incorrect results for multiple tags

### ISSUE THREAD

**Issue by jsabin** [kairosdb/kairosdb#79]
This bug exists in both 0.9.3 and 0.94.

Add Datapoints

[
   {
        name: 'kairos-test-metric',
        timestamp: 1359786400000,
        value: 17,
        tags: {
            tagname1: 'x'
        }
    },
    {
        name: 'kairos-test-metric',
        timestamp: 1359786500000,
        value: 71,
        tags: {
            tagname2: 'x'
        }
    }
]

Peform query

{
        start_absolute: 0,
        metrics: [
                     {
                       name: 'kairos-test-metric',
                       group_by: [{name: 'tag', tags: ['tagname1', 'tagname2']}]
                     }
                  ]
}

Should return a response that contains two groups like the following but instead returns a single group with both data points (see davidvgalbraith's comment below):

{"queries":
    [{"sample_size":2,
      "results":[
                    {
                      "name":"kairos-test-metric",
                      "group_by":[{"name":"tag",
                                   "tags":["tagname1","tagname2"],
                                   "group":{"tagname1":"","tagname2":"x"}}],
                      "tags":{"tagname2":["x"]},
                      "values":[[1359786500000,71]]
                   },
                   {
                    "name":"kairos-test-metric",
                    "group_by":[{"name":"tag",
                                   "tags":["tagname1","tagname2"],
                                   "group":{"tagname1":"x","tagname2":""}}],
                    "tags":{"tagname1":["x"]},
                    "values":[[1359786400000,17]]
                  }
              ]
    }]
}

**Comment by shilpisharma** [comment]
Hi. I am facing this issue while calling REST API from python script. Was this resolved?

I am using kairosdb-0.9.4-6.
