### ISSUE TITLE
Day vs month sampling disalignment

### ISSUE THREAD

**Issue by adedan** [kairosdb/kairosdb#89]
It seems that samples alignment is not done in the same way when sampling is by day or by month:

# storing 3 values
curl 'http://localhost:8081/api/v1/datapoints'  --verbose 
	-X POST -H 'Content-Type: application/json;charset=utf-8' 
	-d '{"name": "test","datapoints": [[1406840400000, 1], [1406844000000, 1], [1406847600000, 100]],"tags": {"host": "server1","data_center": "DC1"}}' 

# aggregating at daily level
curl 'http://localhost:8081/api/v1/datapoints/query'  --verbose 
	-X POST -H 'Content-Type: application/json;charset=utf-8' 
	-d '{"metrics": [{"tags": {},"name": "test","aggregators": [{"name": "sum","align_sampling": true,"sampling": {"value": "1","unit": "days"}}]}],"cache_time": 0,"start_absolute": 1406671200000,"end_absolute": 1406930400000}'

{"queries":
	[{"sample_size":3,"results":
		[{"name":"test","group_by":[{"name":"type","type":"number"}],
		  "tags":{"data_center":["DC1"],"host":["server1"]},
		  "values":[[1406840400000,2],[1406847600000,100]]}]}]}

# aggregating at monthly level
curl 'http://localhost:8081/api/v1/datapoints/query'  --verbose 
	-X POST -H 'Content-Type: application/json;charset=utf-8' 
	-d '{"metrics": [{"tags": {},"name": "test","aggregators": [{"name": "sum","align_sampling": true,"sampling": {"value": "1","unit": "months"}}]}],"cache_time": 0,"start_absolute": 1406671200000,"end_absolute": 1406930400000}'

{"queries":
	[{"sample_size":3,"results":
		[{"name":"test","group_by":[{"name":"type","type":"number"}],
		  "tags":{"data_center":["DC1"],"host":["server1"]},
		  "values":[[1406840400000,1],[1406844000000,101]]}]}]}

**Comment by brianhks** [comment]
This was fixed with the merge #82
